### PR TITLE
Data preview

### PR DESCRIPTION
**Pull request by chynamyerz**
No tests yet.

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: all files reviewed, 5 unresolved discussions (waiting on @chynamyerz)

___
*[src/schema.graphql, line 216 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisQCGE4bO07UUUIE-l:-LisQCGE4bO07UUUIE-m:b-1egf4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/schema.graphql#L216)):*
> ```GraphQL
>   A list of data preview file path.
>   """
>   dataPreviewFilePaths: [String!]!
> ```

Should be URIs rather than file paths. Maybe include "Image" in the name?
___
*[src/db/connection.ts, line 7 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisRTrf5rcJAEeUWakc:-LisRTrf5rcJAEeUWakd:bkdc9y0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/db/connection.ts#L7)):*
> ```XML
>  * A database class
>  */
> class Database {
> ```

You don't really need a class for this. Also, consider using a pool. See https://medium.com/@mhagemann/create-a-mysql-database-middleware-with-node-js-8-and-async-await-6984a09d49f4.
___
*[src/resolvers/Query.ts, line 14 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisSwh75ux4Xdw6Q0Fo:-LisSwh75ux4Xdw6Q0Fp:b-cln54a) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/resolvers/Query.ts#L14)):*
> ```XML
> // Defining the data preview interface
> interface IDataPreview {
>   dataPreviewFilePaths: string[];
> ```

Maybe drop the "dataPreview" from the property names? Maybe include "image" in the first property name?
___
*[src/resolvers/Query.ts, line 108 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisX6ukCVB9ZAhAp9YJ:-LisX6ulDQSATB0XXKhP:bl991gj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/resolvers/Query.ts#L108)):*
> ```XML
>       FROM DataPreview AS dp 
>       JOIN DataPreviewType AS dpt ON dp.previewTypeId = dpt.dataPreviewTypeId
>       WHERE dp.dataFileId = ?
> ```

Must be the ordered by the preview order.
___
*[src/resolvers/Query.ts, line 119 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisWBOS9neZcoM9FMBl:-LisWBOT3gTLXqqsjdxc:bkdgsq4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/resolvers/Query.ts#L119)):*
> ```XML
>       if (row.dataPreviewType === "Header") {
>         // Read the file that contains FITS headers as a string
>         dataPreviewFitsHeaders = fs.readFileSync(row.path, "utf-8");
> ```

Maybe rather use dataPreviewFitsHeaders += ..., in case there are more than one?

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/schema.graphql, line 216 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisQCGE4bO07UUUIE-l:-LiwVIiM2YugLCG65qFH:bs7wunb) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/schema.graphql#L216)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be URIs rather than file paths. Maybe include "Image" in the name?
</blockquote></details>

Done..
___
*[src/db/connection.ts, line 7 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisRTrf5rcJAEeUWakc:-LiwUqA55VG4VM6Hf0qF:b-tw9yzn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/db/connection.ts#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You don't really need a class for this. Also, consider using a pool. See https://medium.com/@mhagemann/create-a-mysql-database-middleware-with-node-js-8-and-async-await-6984a09d49f4.
</blockquote></details>

Nice read, thanks...
___
*[src/resolvers/Query.ts, line 14 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisSwh75ux4Xdw6Q0Fo:-LiwUwQH8UL3l-SAcJZJ:b-w8sp9z) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/resolvers/Query.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe drop the "dataPreview" from the property names? Maybe include "image" in the first property name?
</blockquote></details>

Done and kept it the same also on the schema.graphql
___
*[src/resolvers/Query.ts, line 108 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisX6ukCVB9ZAhAp9YJ:-LiwVFuU6mDtctS0_4wF:bmfxqef) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/resolvers/Query.ts#L108)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Must be the ordered by the preview order.
</blockquote></details>

Done...
___
*[src/resolvers/Query.ts, line 119 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisWBOS9neZcoM9FMBl:-LiwV4EJ-LdM_onkTXJl:bdyav2j) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/resolvers/Query.ts#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather use dataPreviewFitsHeaders += ..., in case there are more than one?
</blockquote></details>

Wondered about this. What if the files contain some headers that are the same(thinking)?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: all files reviewed, 12 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/schema.graphql, line 220 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LiwVkbhDik3wYWLli7O:-LiwVkbhDik3wYWLli7P:b-q6v3it) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/schema.graphql#L220)):*
> ```GraphQL
>   The FITS headers as a sting for the data preview
>   """
>   dataPreviewFitsHeaders: String!
> ```

We need to discuss whether its "header" or "headers"...
___
*[src/db/connection.ts, line 13 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LiwW8Ge3Sb0RZzXNTku:-LiwW8Ge3Sb0RZzXNTkv:b-7tiwfm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/efe950a9c8650abfb71230ef6a9cceb7958aa38f/src/db/connection.ts#L13)):*
> ```XML
> 
> // Creating a pool of database connections
> // It is a good practice to use a pool of connections
> ```

I'm not sure you have to state that it's good practice. Bjut if you want to highlight this, you might rather include a link to some document on the web explaining it.
___
*[src/db/connection.ts, line 15 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LiwX5uQ5NsxNbUSY2N_:-LiwX5uQ5NsxNbUSY2Na:bibjrf) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/efe950a9c8650abfb71230ef6a9cceb7958aa38f/src/db/connection.ts#L15)):*
> ```XML
> // It is a good practice to use a pool of connections
> // for database connection management purposes
> const dbConnection = mysql.createPool(config);
> ```

This should be called pool, I guess. (And so should this file.)
___
*[src/db/connection.ts, line 31 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LiwW_E6-lzHc5PUmmxw:-LiwW_E6-lzHc5PUmmxx:b-ged2us) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/efe950a9c8650abfb71230ef6a9cceb7958aa38f/src/db/connection.ts#L31)):*
> ```XML
> (dbConnection.query as any) = util.promisify(dbConnection.query);
> 
> export { dbConnection };
> ```

Why not export this as default?
___
*[src/resolvers/Query.ts, line 14 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LiwXRvxBtl4jtRA92Vp:-LiwXRvxBtl4jtRA92Vq:b-ja1mtw) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/efe950a9c8650abfb71230ef6a9cceb7958aa38f/src/resolvers/Query.ts#L14)):*
> ```XML
> // Defining the data preview interface
> interface IDataPreview {
>   imageURIs: string[];
> ```

fitsHeaders must come first to keep the linter happy. :)
___
*[src/resolvers/Query.ts, line 125 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LiwXu74ESjupfk-E-Q1:-LiwXu753bj70GGbPmE_:by6y85k) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/efe950a9c8650abfb71230ef6a9cceb7958aa38f/src/resolvers/Query.ts#L125)):*
> ```XML
>     (rows as any).forEach((row: { path: string; dataPreviewType: string }) => {
>       if (row.dataPreviewType === "Header") {
>         // Read the file that contains FITS headers,
> ```

Maybe say:

// Read in the file, which contains a FITS header.
// If there are multiple FITS header files, all headers are combined in a single string.
___
*[src/resolvers/Query.ts, line 130 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LiwYR1v6tExvMO1aS_d:-LiwYR1v6tExvMO1aS_e:bfbpb4d) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/efe950a9c8650abfb71230ef6a9cceb7958aa38f/src/resolvers/Query.ts#L130)):*
> ```XML
>       } else if (row.dataPreviewType === "Image") {
>         // Add all the image URIs to the list
>         results.imageURIs.push(row.path);
> ```

Note that you are still returning a file path, not an URI.

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: 3 of 7 files reviewed, 14 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/createServer.ts, line 181 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjLNo-u6nW0z1IHnM7v:-LjLNo-v2H4T93mO2iqR:b4cmh50) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/52e79298ba86f4ff1455fd5aa9b36931615fa90a/src/createServer.ts#L181)):*
> ```XML
> 
>   /**
>    * Endpoint for downloading the data file preview iamge.
> ```

typo image
___
*[src/createServer.ts, line 201 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjLPE31CpyTADTytkBP:-LjLPE31CpyTADTytkBQ:b-cmldmk) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/52e79298ba86f4ff1455fd5aa9b36931615fa90a/src/createServer.ts#L201)):*
> ```XML
> 
>       // Get all the params from the request
>       const { dataFileId, dataPreviewFileName } = req.params;
> ```

why need a dataPreviewFileName?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: all files reviewed, 11 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

___
*[src/createServer.ts, line 201 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjLPE31CpyTADTytkBP:-LjLPvSt8kyArPcfl6_o:byylr0a) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/52e79298ba86f4ff1455fd5aa9b36931615fa90a/src/createServer.ts#L201)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

why need a dataPreviewFileName?
</blockquote></details>

For two reasons:
* dataFileId does not uniquely identify a preview file.
* It is more user-friendly.
___
*[src/createServer.ts, line 211 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjLRk8N7sN0l0JSHR4p:-LjLRk8O3Fzj-_miXY15:bhes14r) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/52e79298ba86f4ff1455fd5aa9b36931615fa90a/src/createServer.ts#L211)):*
> ```XML
>       AND dp.dataPreviewFileName = ?
>     `;
>       // Querying the data preview image path
> ```

path will be undefined if the requested preview file does not exist. You should raise a notFound error in this case.
___
*[src/createServer.ts, line 215 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjLS_4i-KAQ61C-6tXm:-LjLS_4i-KAQ61C-6tXn:b-teu1vd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/52e79298ba86f4ff1455fd5aa9b36931615fa90a/src/createServer.ts#L215)):*
> ```XML
> 
>       // Download the data request file
>       res.download(path, dataPreviewFileName, err => {
> ```

You are assuming that the path in the database is a real file path. However, that isn't necessarily the case; there could very well be a base path before it, to be defined in an environment variable and used in the root option of res.download (cf. https://expressjs.com/en/api.html#res.download and https://expressjs.com/en/api.html#res.sendFile).
___
*[src/createServer.ts, line 218 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjLS11H4NY8rOPoBI3U:-LjLS11H4NY8rOPoBI3V:b5gqge5) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/52e79298ba86f4ff1455fd5aa9b36931615fa90a/src/createServer.ts#L218)):*
> ```XML
>         if (err) {
>           if (!res.headersSent) {
>             res.status(404).send(notFound);
> ```

The requested file *should* exist if you get here, and as such any error at this stagec should be considered an internal server error. So a status code of 500 and a generic error message might be more appropriate.
___
*[src/resolvers/Query.ts, line 119 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LisWBOS9neZcoM9FMBl:-LjLZjkHDDfWMF7UKGWe:b5h4433) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b3f0699cd1138cc12267948a54a64bc68e315a0f/src/resolvers/Query.ts#L119)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Wondered about this. What if the files contain some headers that are the same(thinking)?
</blockquote></details>

I'm not sure I'd worry.
___
*[src/resolvers/Query.ts, line 133 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjLZ4iJ1VUqQbiA68Fk:-LjLZ4iJ1VUqQbiA68Fl:b-q8dtsm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/52e79298ba86f4ff1455fd5aa9b36931615fa90a/src/resolvers/Query.ts#L133)):*
> ```XML
>           // If there are multiple FITS header files,
>           // all headers are combined in a single string.
>           results.fitsHeader += fs.readFileSync(row.path, "utf-8");
> ```

You are assuming that the path in the database is a real file path. However, that isn't necessarily the case; there could very well be a base path before it, to be defined in an environment variable.

**Review by chynamyerz — COMMENTED** [review]
Please check the latest commit.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-:-LjMGmIZ1wqoc5xATVAg:b9grlhy)* status: 5 of 7 files reviewed, 11 unresolved discussions (waiting on @chynamyerz, @Eb-Zeero, and @hettlage)

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @chynamyerz, @Eb-Zeero, and @hettlage)

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: all files reviewed, 8 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

**Review by chynamyerz — COMMENTED** [review]
Please check the mysql mock.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-:-LjQjiDA5AZ-Rfwao1Od:bpb0t5a)* status: 7 of 9 files reviewed, 8 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: all files reviewed, 10 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

___
*[src/__mocks__/mysql.ts, line 3 at r7](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjQt1iY8EFCLSPLdr4k:-LjQt1iY8EFCLSPLdr4l:bbq723r) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e4b52414edbd4b83c58670376585e42341cf329b/src/__mocks__/mysql.ts#L3)):*
> ```XML
> const mysql: any = jest.genMockFromModule("mysql");
> 
> const pool = (mysql.createPool = jest.fn(() => {
> ```

Why do you have the "const pool ="?
___
*[src/__tests__/passwordReset.test.ts, line 76 at r7](https://reviewable.io/reviews/saltastroops/data-archive-backend/19#-LjQshyKBIsOdD1L-Usl:-LjQshyLArIzRA23EFcu:bbbu3a1) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f964cbef4e193085673ec995db54a3459996bbf9/src/__tests__/passwordReset.test.ts#L76)):*
> ```XML
>     expect(prisma.user).toHaveBeenCalled();
>     expect(prisma.updateUser).toHaveBeenCalled();
>     expect(transporter.sendMail).not.toHaveBeenCalled();
> ```

Please revert back to ".not.toHaveBeenCalled". :)

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: all files reviewed, 10 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/19)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
