### PR TITLE
Include midas files

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/194)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 916 of 916 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/194)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 464 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/194#-Msivmr-2lFv3UJ47-aA:-Msivmr-2lFv3UJ47-aB:b-rvdeta) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c2f1e2f88ace01c7b33a08159e8e72c5af3356ae/src/util/zipDataRequest.ts#L464)):*
> ```XML
>     );
>   }
>   switch (m[1]) {
> ```

you are switching between arms while you only need the Blue arm.
I thing If else can work better here

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/194)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/util/zipDataRequest.ts, line 464 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/194#-Msivmr-2lFv3UJ47-aA:-MsixqYWAh33cFiEMYuo:bo3jqxo) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c2f1e2f88ace01c7b33a08159e8e72c5af3356ae/src/util/zipDataRequest.ts#L464)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

you are switching between arms while you only need the Blue arm.
I thing If else can work better here
</blockquote></details>

I'm not sure... You would at least need an or condition in the if (`m[1] == 'R' || m[1] == 'H'`), and at least conceptually, you are considering all instruments here. I'd rather keep the switch.

**Review by Eb-Zeero — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1823 of 1823 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/194)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
