### PR TITLE
Added fits header file download endpoint

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/22)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/22)* status: all files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

___
*[src/createServer.ts, line 2 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/22#-Lk-CQgd8W-Em6mMgSRD:-Lk-CQgd8W-Em6mMgSRE:b-vl7ykl) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/2f5478cadd9c64a30bdba0fada175ee2ee92b62f/src/createServer.ts#L2)):*
> ```XML
> import * as Sentry from "@sentry/node";
> import bcrypt from "bcrypt";
> ```

I'll make some small changes.

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/22)* status: all files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/22)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/createServer.ts, line 2 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/22#-Lk-CQgd8W-Em6mMgSRD:-Lk-G3oSEJvuvA1muNKa:b-9755fa) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/2f5478cadd9c64a30bdba0fada175ee2ee92b62f/src/createServer.ts#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'll make some small changes.
</blockquote></details>

Thank you.

**Review by chynamyerz — COMMENTED** [review]
It won't allow to merge this side, it should though on your side. Please go ahead.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/22#-:-Lk-GDrm9xa0AgsYU--T:b-5se8j)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
