### PR TITLE
Fixed indentation issue on README file

### LINKED ISSUE #125: Read me table not allighned

### PR DESCRIPTION
**Pull request by Lonwabo11**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/130)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/130)* status: all files reviewed, 5 unresolved discussions (waiting on @Lonwabo11)

___
*[src/util/zipDataRequest.ts, line 72 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P6o3_4XzYq4BVqnED:-M4P6o3_4XzYq4BVqnEE:bbicvpq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L72)):*
> ```XML
>                LEFT OUTER JOIN observations.proposal obsp ON obs.proposal_id = obsp.proposal_id
>                LEFT OUTER JOIN observations.instrument ins on obs.instrument_id = ins.instrument_id
>                LEFT OUTER JOIN observations.observation_group obs_group on obs_group.observation_group_id= obs.observation_group_id
> ```

For consistency: observation_group_id= ---> observation_group_id = [i.e, with a space before the equals sign]
___
*[src/util/zipDataRequest.ts, line 288 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P6DmfC_8V_fFSbYNd:-M4P6DmfC_8V_fFSbYNe:b-l4hj08) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L288)):*
> ```XML
> (if requested) the standard taken nearest to an observation is included.`;
>   // The title of the table
>   const tableTitle = `The requested files\r\n===================\r\n\n`;
> ```

I'd suggest you just use \n, not \r\n (everywhere in this file).
___
*[src/util/zipDataRequest.ts, line 291 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P9fwG47qth7IqMvAm:-M4P9fwG47qth7IqMvAn:bwcgjpi) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L291)):*
> ```XML
> 
>   // The table containing the data request file names and type of the product data contained by the file
>   const table = tableHeader + tableBody + `\r\n`;
> ```

It seems that an empty line is missing just above the table. On the other hand, there is one empty line too many below the main heading.
___
*[src/util/zipDataRequest.ts, line 316 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P5O4M-KenYhmolisO:-M4P5O4M-KenYhmolisP:b-ogdkt3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L316)):*
> ```XML
> should be written as a footnote:
> 
> *based on observations made with the Southern African Large Telescope (SALT)"
> ```

paper title* ---> paper title
*based ---> "based
___
*[src/util/zipDataRequest.ts, line 328 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P6_211te4h7jq7mDs:-M4P6_211te4h7jq7mDt:b-kik8if) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L328)):*
> ```XML
> Pickering, T.E., Potter, S., Romero Colmenero, E., Vaisanen, P., Williams, T.,
> Zietsman, E., 2010. PySALT: the SALT Science Pipeline.
> SPIE Astronomical Instrumentation, 7737-82\r\n\n`;
> ```

There should only be one newline.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/130)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 72 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P6o3_4XzYq4BVqnED:-M4rpDLU3m4HgAAiXiFN:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency: observation_group_id= ---> observation_group_id = [i.e, with a space before the equals sign]
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 288 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P6DmfC_8V_fFSbYNd:-M4rx1to8--rA_5amoYk:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L288)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest you just use \n, not \r\n (everywhere in this file).
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 291 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P9fwG47qth7IqMvAm:-M4rx2Gy2jRmryprPo9n:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L291)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems that an empty line is missing just above the table. On the other hand, there is one empty line too many below the main heading.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 316 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P5O4M-KenYhmolisO:-M4rqhgb01aL81m_vKlL:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L316)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

paper title* ---> paper title
*based ---> "based
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 328 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4P6_211te4h7jq7mDs:-M4rqrbN5hqqovJxoG4e:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9fc0fe6387447c8d8b3b481bb9fb5f368b6c40f5/src/util/zipDataRequest.ts#L328)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should only be one newline.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/130)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[src/util/zipDataRequest.ts, line 277 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4s2_DMB-r3ZMiYsfLA:-M4s2_DMB-r3ZMiYsfLB:b-ef5unr) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e607c9e4b2e8a0f23bbf679eba2821592040e5ca/src/util/zipDataRequest.ts#L277)):*
> ```XML
>       tableRowContent += `| ${file.fileDescription}${" ".repeat(
>         fileDescriptionStrLength - file.fileDescription.length
>       )} |\r`;
> ```

I think this \r can be removed.
___
*[src/util/zipDataRequest.ts, line 333 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4s2woXBZcF9M3oCGNF:-M4s2woXBZcF9M3oCGNG:b-gatrhl) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e607c9e4b2e8a0f23bbf679eba2821592040e5ca/src/util/zipDataRequest.ts#L333)):*
> ```XML
>   const readMeFileContent = tableTitle + calibrationsMessage + table + policy;
> 
>   const fileSaver = require("fs");
> ```

This code seems to have been added for testing and thus should be removed. :)

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/130)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 277 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4s2_DMB-r3ZMiYsfLA:-M4sHUlNAmLYlVmYtfBm:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e607c9e4b2e8a0f23bbf679eba2821592040e5ca/src/util/zipDataRequest.ts#L277)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this \r can be removed.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 333 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/130#-M4s2woXBZcF9M3oCGNF:-M4sHWGC3mHMjzSDd2sS:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e607c9e4b2e8a0f23bbf679eba2821592040e5ca/src/util/zipDataRequest.ts#L333)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This code seems to have been added for testing and thus should be removed. :)
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/130)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
