### PR TITLE
Reject empty data data request.

### LINKED ISSUE #118: Empty data requests should be refused
uests

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/119)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/119)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/resolvers/dataRequest.ts, line 29 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/119#-M3kiZ4T5z5miMk4uYki:-M3kiZ4T5z5miMk4uYkj:bpuwea4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f212d7a2acdd1be23f7399fbb65cc264414d577f/src/resolvers/dataRequest.ts#L29)):*
> ```XML
> 
>   // check if there are data files
>   if (!dataFiles) {
> ```

!dateFiles --> dataFiles.length !==0

Empty arrays are truthy in JavaScript.
___
*[src/resolvers/dataRequest.ts, line 30 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/119#-M3khrfN4bNGv-aj99tn:-M3khrfN4bNGv-aj99to:b-a2nw8r) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f212d7a2acdd1be23f7399fbb65cc264414d577f/src/resolvers/dataRequest.ts#L30)):*
> ```XML
>   // check if there are data files
>   if (!dataFiles) {
>     throw new Error("You can not create an empty data request.");
> ```

can not ---> cannot

Or how about: A data request must contain at least one file.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/119)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/dataRequest.ts, line 29 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/119#-M3kiZ4T5z5miMk4uYki:-M3l2LWd0sJCkORisRyg:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f212d7a2acdd1be23f7399fbb65cc264414d577f/src/resolvers/dataRequest.ts#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

!dateFiles --> dataFiles.length !==0

Empty arrays are truthy in JavaScript.
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 30 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/119#-M3khrfN4bNGv-aj99tn:-M3l2M4Z0j-zr-3Dh15z:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f212d7a2acdd1be23f7399fbb65cc264414d577f/src/resolvers/dataRequest.ts#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

can not ---> cannot

Or how about: A data request must contain at least one file.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/119)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/resolvers/dataRequest.ts, line 29 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/119#-M3kiZ4T5z5miMk4uYki:-M3pgRtO8CC-H0vkaFLQ:b9n0xas) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f212d7a2acdd1be23f7399fbb65cc264414d577f/src/resolvers/dataRequest.ts#L29)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops. This should have been `dataFiles.length === 0` or, if you prefer, `!dataFiles.length`.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/119)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/resolvers/dataRequest.ts, line 28 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/119#-M3pgxGy7TDYpFNOdc66:-M3pgxGy7TDYpFNOdc67:b9q2uov) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9f4a9891a1c0b8edc5e89885dc02b14f7c0ee9aa/src/resolvers/dataRequest.ts#L28)):*
> ```XML
>   }
> 
>   // check if there are data files
> ```

Oops. This should have been `dataFiles.length === 0` or, if you prefer, `!dataFiles.length`. My `!==` was nonsense, of course.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/119)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/resolvers/dataRequest.ts, line 28 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/119#-M3pgxGy7TDYpFNOdc66:-M3yoAp_9aIAvCFpObia:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/96d46a48a150bc513d6e39d4036f1f6b44f4ccf3/src/resolvers/dataRequest.ts#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oops. This should have been `dataFiles.length === 0` or, if you prefer, `!dataFiles.length`. My `!==` was nonsense, of course.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/119)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
