### PR TITLE
Data request fail

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

___
*[src/util/zipDataRequest.ts, line 335 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/124#-M3vtyII9ixf3tRwSuA8:-M3vtyIJ3PPZHWl4Yk3y:b-asesmo) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e2ec9786cc71204c7c10ce5a17dd19e97bba1234/src/util/zipDataRequest.ts#L335)):*
> ```XML
>   // append a file from string
>   archive.append(readMeFileContent, { name: "README.txt" });
>   const rawRequested = requestedCalibrationLevels.has("RAW");
> ```

Thanks for fixing the issue!

It seems that you can simplify the code:

```
dataFiles.forEach((file: { filepath: string; name: string }) => {
       archive.file(`${process.env.FITS_BASE_DIR}/${file.filepath}`, {
        name: file.name
      });
}
```

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 335 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/124#-M3vtyII9ixf3tRwSuA8:-M3ymFhk9lLkA0B9pM2i:b-nrhujy) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e2ec9786cc71204c7c10ce5a17dd19e97bba1234/src/util/zipDataRequest.ts#L335)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thanks for fixing the issue!

It seems that you can simplify the code:

```
dataFiles.forEach((file: { filepath: string; name: string }) => {
       archive.file(`${process.env.FITS_BASE_DIR}/${file.filepath}`, {
        name: file.name
      });
}
```

</blockquote></details>

I do not want to archive everything.
I need to archive row path if raw is selected and need to also archive reduced if redused is selected.
if both are selected I need to archive both.
either I loop once like I did or loop two time with your approach. 
and I eill still check 
requestedCalibrationLevels.has("REDUCED"); or requestedCalibrationLevels.has("RAW");

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/util/zipDataRequest.ts, line 335 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/124#-M3vtyII9ixf3tRwSuA8:-M3yuxaqDUjI04zm_aWJ:b-atiazz) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e2ec9786cc71204c7c10ce5a17dd19e97bba1234/src/util/zipDataRequest.ts#L335)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I do not want to archive everything.
I need to archive row path if raw is selected and need to also archive reduced if redused is selected.
if both are selected I need to archive both.
either I loop once like I did or loop two time with your approach. 
and I eill still check 
requestedCalibrationLevels.has("REDUCED"); or requestedCalibrationLevels.has("RAW");
</blockquote></details>

Yes, but the decision whether to store raw/reduced data is made already when populating the dataFiles array earlier on:

```
for (const df of artifacts) {
    for (const calibrationLevel of Array.from(requestedCalibrationLevels)) {
        ...
        dataFiles.push(...);
    }
}
```

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 335 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/124#-M3vtyII9ixf3tRwSuA8:-M3yz10n6biS74FkIejO:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e2ec9786cc71204c7c10ce5a17dd19e97bba1234/src/util/zipDataRequest.ts#L335)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, but the decision whether to store raw/reduced data is made already when populating the dataFiles array earlier on:

```
for (const df of artifacts) {
    for (const calibrationLevel of Array.from(requestedCalibrationLevels)) {
        ...
        dataFiles.push(...);
    }
}
```
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/util/zipDataRequest.ts, line 335 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/124#-M3vtyII9ixf3tRwSuA8:-M3z-oCJ7_kNRyEPELKQ:b-xydg6f) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e2ec9786cc71204c7c10ce5a17dd19e97bba1234/src/util/zipDataRequest.ts#L335)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And now the rawRequested and reducedRequested constants have become unnecessary... :)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 335 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/124#-M3vtyII9ixf3tRwSuA8:-M3zAdR2ARVhKOsF4WgG:b-tfyzrx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e2ec9786cc71204c7c10ce5a17dd19e97bba1234/src/util/zipDataRequest.ts#L335)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

And now the rawRequested and reducedRequested constants have become unnecessary... :)
</blockquote></details>

I pushed on a wrong branch sorry

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/124)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
