### PR TITLE
language changes

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/5)

### CODE REVIEW

**Review by chynamyerz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/5)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[__tests__/userAuthentication.spec.ts, line 93 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/5#-LYelM7C4FVNRxf0Fi0F:-LYelM7C4FVNRxf0Fi0G:ba3hv51) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c01eddf1f55de8ba7f9403287dc2c7704c97b1c6/__tests__/userAuthentication.spec.ts#L93)):*
> ```XML
>     // Expect the error message to be meaningful
>     expect(JSON.parse(response.text).message).toContain(
>       "username or password"
> ```

What about the them?
Shouldn't we be specific that one of them is wrong?

**Review by saltastroops — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/5)* status: all files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

___
*[__tests__/userAuthentication.spec.ts, line 93 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/5#-LYelM7C4FVNRxf0Fi0F:-LYewQ_RCxQuKlV6ai9D:b-jy6gch) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c01eddf1f55de8ba7f9403287dc2c7704c97b1c6/__tests__/userAuthentication.spec.ts#L93)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

What about the them?
Shouldn't we be specific that one of them is wrong?
</blockquote></details>

A perfectly valid point. But this makes the test slightly more brittle - imagine you replace "wrong" with "invalid". .. If you want to change it, though, go ahead! :-)

**Review by saltastroops — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/5)* status: all files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

**Review by chynamyerz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
