### PR TITLE
Added file download feature

### PR DESCRIPTION
**Pull request by chynamyerz**
Please look into this pull request, it will give the direction of confirming the endpoint structure to use and the path where the data request file to download is located.

NB! "No test yet" ;-) as it is obvious the implementation is going to change.

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15)

### CODE REVIEW

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by chynamyerz — COMMENTED** [review]
I have also added an express package to deal with the lint errors

> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15#-:-LeBqTSB7_F1BGWU2QPn:banrtzi)* status: 6 of 11 files reviewed, all discussions resolved (waiting on @chynamyerz)

**Review by hettlage — DISMISSED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[.gitignore, line 21 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/15#-LeIjC3N0w9Xr_UecQKR:-LeIjC3N0w9Xr_UecQKS:ba8wcr0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/aaee1800c0ef00cd7e469609493803ebb70cc1ea/.gitignore#L21)):*
> ```ignore
> .vscode
> 
> # downloads
> ```

I'd rather exclude rather than ignore the folder, as (at least in production) the files to download arguably should not be in essentially the same place as the server code.
___
*[src/datamodel.prisma, line 29 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/15#-LeInWBk4h12k_ogBcsI:-LeInWBk4h12k_ogBcsJ:brk6wph) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/aaee1800c0ef00cd7e469609493803ebb70cc1ea/src/datamodel.prisma#L29)):*
> ```
> }
> 
> enum DataRequestStatus {
> ```

I think the Prisma schema needs some discussion.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 2 of 3 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

**Review by Eb-Zeero — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[.gitignore, line 21 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/15#-LeIjC3N0w9Xr_UecQKR:-Lekdyet9VsGbRIxkSxn:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/aaee1800c0ef00cd7e469609493803ebb70cc1ea/.gitignore#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rather exclude rather than ignore the folder, as (at least in production) the files to download arguably should not be in essentially the same place as the server code.
</blockquote></details>

Done.
___
*[src/datamodel.prisma, line 29 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/15#-LeInWBk4h12k_ogBcsI:-Leke30-89buQ5i0dDvg:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/aaee1800c0ef00cd7e469609493803ebb70cc1ea/src/datamodel.prisma#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the Prisma schema needs some discussion.
</blockquote></details>

Done.

**Review by Eb-Zeero — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/15)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Pull request closed without merging**
