### PR TITLE
Readme file

### LINKED ISSUE #97: Add more information into the README
Adding more information into the table in the README for including which instruments where used, type of file downloaded, etc

### PR DESCRIPTION
**Pull request by Lonwabo11**
Fixed the file name plus the changes you requested. Also added the file description

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[src/util/zipDataRequest.ts, line 77 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M372RZJ8CGg4gEE6PFU:-M372RZK5Q_3j805lY0o:bgcbolv) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L77)):*
> ```XML
> 
>   const dataFiles: Array<any> = [];
>   const path = require("path");
> ```

This should be an import statement at the top of the file, such as

`import { basename} from 'path';`
___
*[src/util/zipDataRequest.ts, line 79 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3730wQ0gAU4dsk1-Cd:-M3730wQ0gAU4dsk1-Ce:b-wr00hw) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L79)):*
> ```XML
>   const path = require("path");
> 
>   for (const df of artifacts) {
> ```

There should be a comment explaining what you are doing.
___
*[src/util/zipDataRequest.ts, line 97 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37CqN_3Y8iw8muRVZ7:-M37CqN_3Y8iw8muRVZ8:bxtlrdc) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L97)):*
> ```XML
>       const fileDescription = description;
> 
>       dataFiles.push({
> ```

You can somewhat simplify the code below if you handle missing data here. Similarly, you can format the date (of the night) here already, avoiding having to do it in two places.
___
*[src/util/zipDataRequest.ts, line 136 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M378RGi7ksovsyD8tHu:-M378RGi7ksovsyD8tHv:b-rsi8lo) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b60023936257ff5a388a53dc10fbd0e2e03998be/src/util/zipDataRequest.ts#L136)):*
> ```XML
>   dataFiles.forEach((file: { name: string; type: string }) => {
>     // The content of the table body
>     const tableBodyContent = `
> ```

It might be better to call the variable `tableRowContent` as `tableBodyContent` suggests it is for the whole table body content.
___
*[src/util/zipDataRequest.ts, line 154 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37G4AW9_TFxIMItLmO:-M37G4AW9_TFxIMItLmP:b-blh215) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L154)):*
> ```XML
>   archive.pipe(output);
> 
>   // Get the maximum length of the table column names
> ```

table columns, not table column names.
___
*[src/util/zipDataRequest.ts, line 165 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37FOsB6gps9b2mEsHh:-M37FOsB6gps9b2mEsHi:bmheouu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L165)):*
> ```XML
>   const proposalCodeStrLength = Math.max(
>     ...dataFiles.map((file: { proposal_code: string }) =>
>       file.proposal_code ? file.proposal_code.length : "proposal code".length
> ```

Oh, I just notice there is a flaw in the logic: If all filenames consisted of a single letter, you would get a value of 1 - shorter than the string "Proposal code".

So instead you should do something like that (using the proposal code as an example):

``` const PROPOSAL_CODE_HEADING = "Proposal code";
  const proposalCodeStrLength = Math.max(
    ...[
      PROPOSAL_CODE_HEADING.length,
      ...dataFiles.map((file: { proposal_code: string }) => file.proposal_code.length)
    ]
  );```

The same is true for all columns.
```

___
*[src/util/zipDataRequest.ts, line 202 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37EKlc1JEx8trG2zD4:-M37EKlc1JEx8trG2zD5:bzewkp8) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L202)):*
> ```XML
>     proposalCodeStrLength - "Proposal code".length
>   )} | Observation id${" ".repeat(
>     blockIdStrLength - "Observation id".length
> ```

`blockIdStrLength` should be renamed to something like `observationIdStrLength`.
___
*[src/util/zipDataRequest.ts, line 203 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M373fHTALUZruaiTZBA:-M373fHTALUZruaiTZBB:bimyg0t) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L203)):*
> ```XML
>   )} | Observation id${" ".repeat(
>     blockIdStrLength - "Observation id".length
>   )} | Date${" ".repeat(
> ```

Better: Night
___
*[src/util/zipDataRequest.ts, line 204 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37FFxtDnidjtQQdtsE:-M37FFxtDnidjtQQdtsF:b3m8thb) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L204)):*
> ```XML
>     blockIdStrLength - "Observation id".length
>   )} | Date${" ".repeat(
>     observationNightStrLength - "Date".length
> ```

`Date` should be `Night`.
___
*[src/util/zipDataRequest.ts, line 233 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37D78FAk0y2OlEgY5C:-M37D78FAk0y2OlEgY5D:b-8hlhhx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L233)):*
> ```XML
>       tableBodyContent += `| ${
>         file.proposal_code
>           ? file.proposal_code
> ```

You cannot rely on every proposal code having the same length, so you have to spaces, as yiu do for other columns.
___
*[src/util/zipDataRequest.ts, line 241 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37E0S7-vz04-58Q_O2:-M37E0S7-vz04-58Q_O3:btqd3aq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L241)):*
> ```XML
>           ? file.observation_id +
>             " ".repeat(
>               Math.max("block_id  ".length) - file.observation_id.length
> ```

`Math.max("block_id ".length)` should be `blockIdStrLength`, I suppose.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 77 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M372RZJ8CGg4gEE6PFU:-M3A3HBx2MceNtFhyAdx:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should be an import statement at the top of the file, such as

`import { basename} from 'path';`
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 79 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3730wQ0gAU4dsk1-Cd:-M3A67wVCHa-TSgm6xnE:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be a comment explaining what you are doing.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 97 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37CqN_3Y8iw8muRVZ7:-M3AErxD5VXa9jvVZXjo:bumrtls) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You can somewhat simplify the code below if you handle missing data here. Similarly, you can format the date (of the night) here already, avoiding having to do it in two places.
</blockquote></details>

I handled the date here but i don't get how i can handle the missing data at this stage
___
*[src/util/zipDataRequest.ts, line 136 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M378RGi7ksovsyD8tHu:-M3AAHQV0MjZClDq_fel:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b60023936257ff5a388a53dc10fbd0e2e03998be/src/util/zipDataRequest.ts#L136)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be better to call the variable `tableRowContent` as `tableBodyContent` suggests it is for the whole table body content.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 154 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37G4AW9_TFxIMItLmO:-M3A6Yb35Z_pzJScIMmT:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L154)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

table columns, not table column names.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 165 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37FOsB6gps9b2mEsHh:-M3A719v2nP22Ad22Mpi:b3y5f3n) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L165)):*
>     PROPOSAL_CODE_HEADING.length
What is PROPOSAL_CODE_HEADING in this instance. 
___
*[src/util/zipDataRequest.ts, line 202 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37EKlc1JEx8trG2zD4:-M3A7RaI1pUHZrL5Rqzj:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L202)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`blockIdStrLength` should be renamed to something like `observationIdStrLength`.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 203 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M373fHTALUZruaiTZBA:-M3A9mRB8kbGhZF8QFTR:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L203)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Better: Night
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 204 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37FFxtDnidjtQQdtsE:-M3A9qepD_XKiCUu4aRz:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L204)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`Date` should be `Night`.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 233 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37D78FAk0y2OlEgY5C:-M3ABd6m83QHxM8bvEpH:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L233)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You cannot rely on every proposal code having the same length, so you have to spaces, as yiu do for other columns.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 241 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37E0S7-vz04-58Q_O2:-M3ADVjr265rF0qCso9i:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L241)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`Math.max("block_id ".length)` should be `blockIdStrLength`, I suppose.
</blockquote></details>

Done.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 97 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37CqN_3Y8iw8muRVZ7:-M3Au18K9XOB8Ntv5psx:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L97)):*
<details><summary><i>Previously, Lonwabo11 (Lonwabo Zaula) wrote…</i></summary><blockquote>

I handled the date here but i don't get how i can handle the missing data at this stage
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 165 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M37FOsB6gps9b2mEsHh:-M3AtrEz5M8OFkq1sRlN:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L165)):*
<details><summary><i>Previously, Lonwabo11 (Lonwabo Zaula) wrote…</i></summary><blockquote>

>     PROPOSAL_CODE_HEADING.length
What is PROPOSAL_CODE_HEADING in this instance. 

</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[src/util/zipDataRequest.ts, line 79 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3730wQ0gAU4dsk1-Cd:-M3AS7CkDSx4fuyFMsE4:b425nmu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b15580386b04cdff4124e7b7f5f1cd82a49dc049/src/util/zipDataRequest.ts#L79)):*
<details><summary><i>Previously, Lonwabo11 (Lonwabo Zaula) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. : Here would be my suggestion, based on yours: For each requested file and calibration level we create the object to be used when creating the rows of the table of files. This includes a description of the file(s) based on the instrument and calibration level.
___
*[src/util/zipDataRequest.ts, line 109 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3Ay-Gn7LaIzjRfI5oL:-M3Ay-Gn7LaIzjRfI5oM:bqa8iv3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L109)):*
> ```XML
>         night: moment(df.night).format("YYYY-MM-DD"),
>         observation_id: df.observation_id ? df.observation_id : "",
>         proposal_code: df.proposal_code ? df.proposal_code.length : "",
> ```

`df.proposal_code.length` > `df.proposal_code`
___
*[src/util/zipDataRequest.ts, line 160 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3B0pwi0DkGvzwabFCD:-M3B0pwi0DkGvzwabFCE:bocubxg) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L160)):*
> ```XML
>   archive.pipe(output);
> 
>   // Get the maximum length of the table columns
> ```

I'd suggest to use constants for the table column names.
___
*[src/util/zipDataRequest.ts, line 189 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3B0Wa9DOi7gKLHBVzC:-M3B0Wa9DOi7gKLHBVzD:b-4nh4gw) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L189)):*
> ```XML
>       ...dataFiles.map((file: { observation_id: string }) =>
>         file.observation_id
>           ? file.observation_id.length
> ```

Needs updating.
___
*[src/util/zipDataRequest.ts, line 194 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3B-AvG35PJR7OWPhZr:-M3B-AvG35PJR7OWPhZs:b-br52k0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L194)):*
> ```XML
>     ]
>   );
>   const NightStrLength = Math.max(
> ```

Should start with a lowercase 'n'.
___
*[src/util/zipDataRequest.ts, line 201 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3B-UCa2j356OxqkEIg:-M3B-UCa2j356OxqkEIh:b-ho1utc) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L201)):*
> ```XML
>   );
> 
>   const fileDescriptionStrLength = Math.max(
> ```

I'd include the column name as well, as for the other quantities.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 109 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3Ay-Gn7LaIzjRfI5oL:-M3BZ6G764-YvG7yPbAq:bwi5x0g) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L109)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`df.proposal_code.length` > `df.proposal_code`
</blockquote></details>

Need an explanation a little more on this
___
*[src/util/zipDataRequest.ts, line 160 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3B0pwi0DkGvzwabFCD:-M3BZG-58V-g28-GxdZy:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L160)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to use constants for the table column names.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 189 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3B0Wa9DOi7gKLHBVzC:-M3BZHZm8DU4MlBlGuor:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L189)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Needs updating.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 194 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3B-AvG35PJR7OWPhZr:-M3BZJ8a2rawZzqFxUPx:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L194)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should start with a lowercase 'n'.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 201 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3B-UCa2j356OxqkEIg:-M3BZMOTEmZbS5h2NP3C:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L201)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd include the column name as well, as for the other quantities.
</blockquote></details>

Done.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 109 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/111#-M3Ay-Gn7LaIzjRfI5oL:-M3FuOzmBIdS1_D-6EZO:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a95cbb29a88afedea0c28a0ce64fba77eff04752/src/util/zipDataRequest.ts#L109)):*
<details><summary><i>Previously, Lonwabo11 (Lonwabo Zaula) wrote…</i></summary><blockquote>

Need an explanation a little more on this
</blockquote></details>

Done.

**Review by hettlage — DISMISSED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/111)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
