### PR TITLE
Prisma to mysql

### PR DESCRIPTION
**Pull request by chynamyerz**
This is to make us updated about migrating prisma to mysql. 
A lot is happening and I don't wanna diverge to much.

Input would be really appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/30)

### CODE REVIEW

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 5 of 15 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/30)* status: 7 of 18 files reviewed, 4 unresolved discussions (waiting on @chynamyerz)

___
*[src/createServer.ts, line 15 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll6g9LD6HISkaZfqCwc:-Ll6g9LEC4N789nD19g8:bxln67o) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/createServer.ts#L15)):*
> import {saltUserById, saltUserByUsernameAndPassword} from "./util/sdbUser";
Do we need sdbUser?
___
*[src/createServer.ts, line 45 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll6h9dJ6ZgLpzjF5l_-:-Ll6h9dJ6ZgLpzjF5l_0:b4rl8dv) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/createServer.ts#L45)):*
> ```XML
>       { usernameField: "username", passwordField: "password", passReqToCallback: true},
>       async (request, username, password, done, ) => {
>         const _authProvider = authProvider(request.body.authProvider);
> ```

I am assuming by "_authProvider" you meant private, if so, rather use private authProvider
___
*[src/util.ts, line 19 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll6hj30DMlAPinjFs0N:-Ll6hj30DMlAPinjFs0O:b-veh2x6) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/util.ts#L19)):*
> ```XML
>   },
>   host: process.env.MAIL_HOST,
>   port: 2525
> ```

I think we should use environment variables here. 
___
*[src/util/authProvider.ts, line 152 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll5zRUG4-0EPxM6lH6W:-Ll5zRUG4-0EPxM6lH6X:bdg1ifr) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/util/authProvider.ts#L152)):*
> ```XML
> }
> 
> class SDBAuthProvider extends AuthProvider {
> ```

Wouldn't it be better if we put SSDAAuthProvider, SDBAuthProvider in their own files. I am thinking when SAAOAuthProvider comes this may prone unnecessary errors, human typing error especially.

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/30)* status: 6 of 18 files reviewed, 4 unresolved discussions (waiting on @chynamyerz)

___
*[src/createServer.ts, line 15 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll6g9LD6HISkaZfqCwc:-Ll7U_LS2tXaIwjbYUJX:b-noaner) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/createServer.ts#L15)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

> import {saltUserById, saltUserByUsernameAndPassword} from "./util/sdbUser";
Do we need sdbUser?
</blockquote></details>

I *think* it has become obsolete.
___
*[src/createServer.ts, line 45 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll6h9dJ6ZgLpzjF5l_-:-Ll7Ud7t3AfbwmWofTN3:bsej8aw) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/createServer.ts#L45)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

I am assuming by "_authProvider" you meant private, if so, rather use private authProvider
</blockquote></details>

Nope. The name "authProvider" was used for the function authProvider already... :)
___
*[src/util.ts, line 19 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll6hj30DMlAPinjFs0N:-Ll7UCgNCL1gTCSJa6u_:bb7867m) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/util.ts#L19)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

I think we should use environment variables here. 
</blockquote></details>

Yup!
___
*[src/util/authProvider.ts, line 152 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll5zRUG4-0EPxM6lH6W:-Ll7UNCj3vFFjg7xD89A:b74sx6f) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/util/authProvider.ts#L152)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Wouldn't it be better if we put SSDAAuthProvider, SDBAuthProvider in their own files. I am thinking when SAAOAuthProvider comes this may prone unnecessary errors, human typing error especially.
</blockquote></details>

I'm not overly concerned, but feel free to move the classes into separate files.

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 1 of 5 files at r5, 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/30)* status: 8 of 19 files reviewed, 3 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/createServer.ts, line 15 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll6g9LD6HISkaZfqCwc:-Ll7lMeA7NPBmBEPQUOe:b8wwntt) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/createServer.ts#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I *think* it has become obsolete.
</blockquote></details>

removed file and it imports
___
*[src/createServer.ts, line 45 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll6h9dJ6ZgLpzjF5l_-:-Ll7lQme5LgHFfSdU_cI:bbwdfa) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/createServer.ts#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nope. The name "authProvider" was used for the function authProvider already... :)
</blockquote></details>

umm, okay.
___
*[src/util/authProvider.ts, line 152 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/30#-Ll5zRUG4-0EPxM6lH6W:-Ll7lmYoAFkmU0lgOKGg:bsxgfz9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4a91ce667f2f2f251ce3ec30aab3e11ea997636e/src/util/authProvider.ts#L152)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not overly concerned, but feel free to move the classes into separate files.
</blockquote></details>

Skipped it for now. :-)

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 15 files at r1, 4 of 13 files at r2, 4 of 11 files at r4, 2 of 5 files at r5, 6 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/30)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

**Pull request merged**
