### PR TITLE
Include calibrations

### LINKED ISSUE #95: Function for getting calibrations
Extend the function for adding calibrations to cover all the requested calibrations.

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/107)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/107)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/resolvers/Mutation.ts, line 250 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/107#-M1jIrhEAPaQJoc2edFu:-M1jIrhF6PSEtvz6_Qsm:b-skhmup) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9051cff9b80eb54b0c452b163cd7172ab10c813/src/resolvers/Mutation.ts#L250)):*
> ```XML
>     createDataRequest(
>       dataFiles,
>       new Set(requestedCalibrationTypes as CalibrationType[]),
> ```

missing calibration levels as args

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/107)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/resolvers/Mutation.ts, line 250 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/107#-M1jIrhEAPaQJoc2edFu:-M1jUXEU68VbzKUJ_ugH:b-8l1svu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9051cff9b80eb54b0c452b163cd7172ab10c813/src/resolvers/Mutation.ts#L250)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

missing calibration levels as args
</blockquote></details>

Yes - but this is consistent with the current version of the development branch, and this pull request doesn't care about that function. :)

**Review by Eb-Zeero — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/107)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Eb-Zeero — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/107)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
