### PR TITLE
Fix linting issues and unit tests

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/45)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 3 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/45)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

___
*[tslint.json, line 8 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/45#-LsHQ_ekDEz6enaWdOjP:-LsHQ_ekDEz6enaWdOjQ:b-jt9gpo) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/48d894f4ddb2fc8e938eb6cf6a29e96a4550002c/tslint.json#L8)):*
> ```JSON
>     },
>     "no-implicit-dependencies": [true, "dev"],
>     "no-submodule-imports": [false]
> ```

Just disabling the whole rule might be a bit drastic.
___
*[src/util/user.ts, line 51 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/45#-LsHsAxOD7RS2dNW0wkY:-LsHRLFgCksrQZHrcf1C:b7dois3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/48d894f4ddb2fc8e938eb6cf6a29e96a4550002c/src/util/user.ts#L51)):*
> ```XML
> export type Role = "Admin";
> 
> export const getAuthProvider = (
> ```

This function should be defined in the authProvider module.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/45)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[tslint.json, line 8 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/45#-LsHQ_ekDEz6enaWdOjP:-LsHvdJg3oqhRkyVOF1L:b-83od3n) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/48d894f4ddb2fc8e938eb6cf6a29e96a4550002c/tslint.json#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Just disabling the whole rule might be a bit drastic.
</blockquote></details>

Noted
___
*[src/util/user.ts, line 51 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/45#-LsHsAxOD7RS2dNW0wkY:-LsHvezWCDf2MJlHAmAm:b-83od3n) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/48d894f4ddb2fc8e938eb6cf6a29e96a4550002c/src/util/user.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This function should be defined in the authProvider module.
</blockquote></details>

Noted

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 5 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/45)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/45)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
