### PR TITLE
New data request

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/103)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/103)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/resolvers/dataRequest.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1PnLN04e5aI91hLN0L:-M1PnLN04e5aI91hLN0M:by0ni9u) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/resolvers/dataRequest.ts#L59)):*
> ```XML
>         VALUES ($1, $2)
>     `;
>     dataFileIdStrings.map(async dataFileId => {
> ```

I don't think map is the method to use here. forEach probably is better. This applies to other uses of map in this function as well.
___
*[src/resolvers/dataRequest.ts, line 72 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1PoReaAXQSYG4ipv4x:-M1PoReaAXQSYG4ipv4y:bpddmdt) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/resolvers/dataRequest.ts#L72)):*
> ```XML
>     VALUES ($1, (SELECT id FROM level_id))
>     `;
>     requestedCalibrationLevels.map(async CalibrationLevel => {
> ```

Variable names should not start with a capital. :)
___
*[src/resolvers/dataRequest.ts, line 88 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1PogETDWXuVshvk66R:-M1PogETDWXuVshvk66S:bpddmdt) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/resolvers/dataRequest.ts#L88)):*
> ```XML
>     VALUES ($1, (SELECT id FROM type_id))
>     `;
>     requestedCalibrationTypes.map(async CalibrationType => {
> ```

Variable names should not start with a capital. :)
___
*[src/util/dataRequests.ts, line 23 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1Pp-NeARfELbgywmLj:-M1Pp-NeARfELbgywmLk:b54pyi2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/util/dataRequests.ts#L23)):*
> ```XML
> };
> 
> export const capitalizeFirstCharacter = (s: string) => {
> ```

I feel uneasy about this function. For consistency,  the calibration types should really have title case in the database.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/103)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/dataRequest.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1PnLN04e5aI91hLN0L:-M1ZtwjrDiejJGYXvxKv:b-xnfhp8) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/resolvers/dataRequest.ts#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think map is the method to use here. forEach probably is better. This applies to other uses of map in this function as well.
</blockquote></details>

The promise retured will be ignored and I need to wait for all requested calibration types
___
*[src/resolvers/dataRequest.ts, line 72 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1PoReaAXQSYG4ipv4x:-M1ZuHSS4cTOPHw4cdOt:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/resolvers/dataRequest.ts#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Variable names should not start with a capital. :)
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 88 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1PogETDWXuVshvk66R:-M1ZuM-iD2uZCIkMODiG:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/resolvers/dataRequest.ts#L88)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Variable names should not start with a capital. :)
</blockquote></details>

Done.
___
*[src/util/dataRequests.ts, line 23 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1Pp-NeARfELbgywmLj:-M1ZuOFI06Q-FjtzuRT_:bq54bma) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/util/dataRequests.ts#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I feel uneasy about this function. For consistency,  the calibration types should really have title case in the database.
</blockquote></details>

that was before title case will fix it

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/103)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/resolvers/dataRequest.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1PnLN04e5aI91hLN0L:-M1az2eg1Zq7krUKBtLU:b-u0iavv) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/resolvers/dataRequest.ts#L59)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

The promise retured will be ignored and I need to wait for all requested calibration types
</blockquote></details>

Ah, I had the same problem today. I opted for a good old for loop.
___
*[src/util/dataRequests.ts, line 23 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/103#-M1Pp-NeARfELbgywmLj:-M1azarjADlNjVmq3CPv:bpzppo2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/4183cdcdcbe317d27a5199b7a75f55d5d393faf2/src/util/dataRequests.ts#L23)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

that was before title case will fix it
</blockquote></details>

Sorry for nitpicking, but the toTitleCase function has a potentially misleading name: It turns "raw data" into "Raw data" - but (given the name) it really should turn it into "Raw Data".

As such using the title-case package might be worth considering.

**Comment by Eb-Zeero** [comment]
no need to merge.
reviews are fixed on pull request #108

**Pull request closed without merging**
