### PR TITLE
Combined the tatol count query with the datafile query

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: all files reviewed, 3 unresolved discussions (waiting on @chynamyerz)

___
*[src/resolvers/serchResults.ts, line 68 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2WSxb1PgbGNZaYnld:-Lu2WSxb1PgbGNZaYnle:bkp05da) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e5736bc6ce8a964286ba20304cfd71382a016419/src/resolvers/serchResults.ts#L68)):*
> ```XML
>   );
>   const itemSQL = `
>       SELECT ${Array.from(fields).join(", ")}
> ```

See the concerns raised in https://stackoverflow.com/questions/28888375/run-a-query-with-a-limit-offset-and-also-get-the-total-number-of-rows/28888696?noredirect=1#comment88418369_28888696 regarding the case of the offset being greater than or equal to the total count. If the tine difference isn't too bafd, the alternative query in that post might be the better option.
___
*[src/resolvers/serchResults.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2VKQp2yVXuO0lkW6V:-Lu2VKQp2yVXuO0lkW6W:bq5cn3f) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b13d923413b9b61f885eba92ba1188c700c86f16/src/resolvers/serchResults.ts#L75)):*
> ```XML
> 
>   // Get the number of search results
>   const itemsTotal = itemResults[0].items_total;
> ```

You have to handle the case that len(itemResults) === 0.
___
*[src/resolvers/serchResults.ts, line 90 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2XKuV7Tr56cvx4Ecq:-Lu2XKuV7Tr56cvx4Ecr:bkadal9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b13d923413b9b61f885eba92ba1188c700c86f16/src/resolvers/serchResults.ts#L90)):*
> ```XML
>     id: row["artifact.artifact_id"],
>     metadata: [
>       ...Object.entries(row).map(entry => ({
> ```

You probably should not include items_total in the result.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: all files reviewed, 5 unresolved discussions (waiting on @chynamyerz)

___
*[src/resolvers/serchResults.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2g0v48fTK4Kortczs:-Lu2g0v48fTK4Kortczt:b-3yt8s7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b13d923413b9b61f885eba92ba1188c700c86f16/src/resolvers/serchResults.ts#L59)):*
> ```XML
>   );
> 
>   const itemSQL = `
> ```

itemSQL ---> sql
___
*[src/resolvers/serchResults.ts, line 68 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2g4HEAOKFtKRgtGHQ:-Lu2g4HEAOKFtKRgtGHR:brbptg3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b13d923413b9b61f885eba92ba1188c700c86f16/src/resolvers/serchResults.ts#L68)):*
> ```XML
>     .length + 2}
>              `;
>   const itemResults: any = (await ssdaPool.query(itemSQL, [
> ```

itemResults ---> rtesults

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: all files reviewed, 7 unresolved discussions (waiting on @chynamyerz)

___
*[src/resolvers/serchResults.ts, line 61 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu7Tx3G7_XTAJQOF_I9:-Lu7Tx3H3lFWBNMue2ZM:b-r7onby) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/58003c2da8a0af0a965b750d3a8f79963975ea7b/src/resolvers/serchResults.ts#L61)):*
> ```XML
>   const sql = `
>      WITH cte AS (
>        SELECT ${Array.from(fields).join(", ")}
> ```

Here is an alternative query, which might be a bit clearer, makes me feel slightly less nervous about the order being correct and doesn't seem to be (much) slower:

     WITH content AS (
       SELECT ${Array.from(fields).join(", ")}
       FROM ${sqlFrom}
       WHERE ${whereDetails.sql}
     )
     SELECT *
     FROM content
          RIGHT JOIN (SELECT COUNT(*) AS items_total FROM content) AS c ON true
     ORDER BY content."observation_time.start_time" DESC
     LIMIT $${whereDetails.values.length + 1}
     OFFSET $${whereDetails.values.length + 2} 
___
*[src/resolvers/serchResults.ts, line 82 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu7W6ul3EnR5irZcJjK:-Lu7W6ul3EnR5irZcJjL:b765txx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/58003c2da8a0af0a965b750d3a8f79963975ea7b/src/resolvers/serchResults.ts#L82)):*
> ```XML
> 
>   // Get the number of search results
>   const itemsTotal = !results.length ? 0 : results[0].items_total;
> ```

There is always at least one row in the results, so:

const itemsTotal = results[0].items_total
___
*[src/resolvers/serchResults.ts, line 94 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu7XcPRET_3eKsjIcoo:-Lu7XcPRET_3eKsjIcop:buudcgk) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/58003c2da8a0af0a965b750d3a8f79963975ea7b/src/resolvers/serchResults.ts#L94)):*
> ```XML
>     startIndex
>   };
>   const dataFiles =
> ```

I think you should handle the case of no search results straight after getting the results. 
___
*[src/resolvers/serchResults.ts, line 98 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu7ZiVbE6iCzF4JH2Rn:-Lu7ZiVbE6iCzF4JH2Ro:b787tvx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/58003c2da8a0af0a965b750d3a8f79963975ea7b/src/resolvers/serchResults.ts#L98)):*
> ```XML
>       ? []
>       : results.map((row: any) => {
>           delete row.items_total;
> ```

This is a bit problematic, as you are changing the original results object. There is  nothing wrong with that as such, but you shouldn't do it in a map.

Alternatively, you could filter the object entries when creating the metadata. (Actually, this could do with filtering anyway - artifact.artifact_id, artifact.name and artifact.content_length probably shouldn't be in the metadata.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/serchResults.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2g0v48fTK4Kortczs:-Lu8exid5C_Ta57-Tvwj:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b13d923413b9b61f885eba92ba1188c700c86f16/src/resolvers/serchResults.ts#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

itemSQL ---> sql
</blockquote></details>

Done.
___
*[src/resolvers/serchResults.ts, line 68 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2WSxb1PgbGNZaYnld:-Lu8evqN2UorAJsGzNMQ:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e5736bc6ce8a964286ba20304cfd71382a016419/src/resolvers/serchResults.ts#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the concerns raised in https://stackoverflow.com/questions/28888375/run-a-query-with-a-limit-offset-and-also-get-the-total-number-of-rows/28888696?noredirect=1#comment88418369_28888696 regarding the case of the offset being greater than or equal to the total count. If the tine difference isn't too bafd, the alternative query in that post might be the better option.
</blockquote></details>

Done.
___
*[src/resolvers/serchResults.ts, line 68 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2g4HEAOKFtKRgtGHQ:-Lu8ewPh-i6hdW-5htk1:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b13d923413b9b61f885eba92ba1188c700c86f16/src/resolvers/serchResults.ts#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

itemResults ---> rtesults
</blockquote></details>

Done.
___
*[src/resolvers/serchResults.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2VKQp2yVXuO0lkW6V:-Lu8ezeCBKBoVuFIZ3Wr:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b13d923413b9b61f885eba92ba1188c700c86f16/src/resolvers/serchResults.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You have to handle the case that len(itemResults) === 0.
</blockquote></details>

Done.
___
*[src/resolvers/serchResults.ts, line 90 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu2XKuV7Tr56cvx4Ecq:-Lu8f0wmEjRD4xjG7K5v:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b13d923413b9b61f885eba92ba1188c700c86f16/src/resolvers/serchResults.ts#L90)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You probably should not include items_total in the result.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: all files reviewed, 5 unresolved discussions (waiting on @chynamyerz)

___
*[src/resolvers/serchResults.ts, line 80 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu8xXuHCzZEW_RsYcYn:-Lu8xXuHCzZEW_RsYcYo:b-owfdr5) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/1d32e05d3a55e9fdfc343c30d92b4715f115d5f5/src/resolvers/serchResults.ts#L80)):*
> ```XML
> 
>   // Check if there are search results
>   if (results.length === 1 && results[0].items_total === "0") {
> ```

The check results.length  === 1 should be unnecessary.

It might be worth adding a comment like:

// Due to the RIGHT JOIN in the SQL query, there is guaranteed to be at least one row.
___
*[src/resolvers/serchResults.ts, line 110 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu8yWXz8ad8KeDs9LZM:-Lu8yWXz8ad8KeDs9LZN:b9fir65) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/1d32e05d3a55e9fdfc343c30d92b4715f115d5f5/src/resolvers/serchResults.ts#L110)):*
> ```XML
>         .filter(
>           entry =>
>             !["artifact.name", "artifact.content_length"].includes(entry[0])
> ```

What about artifact.artifact_id and items_total?

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/serchResults.ts, line 61 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu7Tx3G7_XTAJQOF_I9:-LuBWaq2E032Ok3Jbau7:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/58003c2da8a0af0a965b750d3a8f79963975ea7b/src/resolvers/serchResults.ts#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here is an alternative query, which might be a bit clearer, makes me feel slightly less nervous about the order being correct and doesn't seem to be (much) slower:

     WITH content AS (
       SELECT ${Array.from(fields).join(", ")}
       FROM ${sqlFrom}
       WHERE ${whereDetails.sql}
     )
     SELECT *
     FROM content
          RIGHT JOIN (SELECT COUNT(*) AS items_total FROM content) AS c ON true
     ORDER BY content."observation_time.start_time" DESC
     LIMIT $${whereDetails.values.length + 1}
     OFFSET $${whereDetails.values.length + 2} 

</blockquote></details>

Done.
___
*[src/resolvers/serchResults.ts, line 94 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu7XcPRET_3eKsjIcoo:-LuBWtvf9oPxsye9iYdG:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/58003c2da8a0af0a965b750d3a8f79963975ea7b/src/resolvers/serchResults.ts#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you should handle the case of no search results straight after getting the results. 
</blockquote></details>

Done.
___
*[src/resolvers/serchResults.ts, line 98 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu7ZiVbE6iCzF4JH2Rn:-LuBWvrQBEtgo0O1I2Xf:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/58003c2da8a0af0a965b750d3a8f79963975ea7b/src/resolvers/serchResults.ts#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is a bit problematic, as you are changing the original results object. There is  nothing wrong with that as such, but you shouldn't do it in a map.

Alternatively, you could filter the object entries when creating the metadata. (Actually, this could do with filtering anyway - artifact.artifact_id, artifact.name and artifact.content_length probably shouldn't be in the metadata.
</blockquote></details>

Done.
___
*[src/resolvers/serchResults.ts, line 80 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu8xXuHCzZEW_RsYcYn:-LuBWll334LSbJDLSkRY:b-ikxz9w) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/1d32e05d3a55e9fdfc343c30d92b4715f115d5f5/src/resolvers/serchResults.ts#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The check results.length  === 1 should be unnecessary.

It might be worth adding a comment like:

// Due to the RIGHT JOIN in the SQL query, there is guaranteed to be at least one row.
</blockquote></details>

We have a slight problem in the new query if omit it, but the other original query works fine (Please let discuss it before I make changes).
___
*[src/resolvers/serchResults.ts, line 110 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu8yWXz8ad8KeDs9LZM:-LuBWyKo9RyAuXdO4ZMH:b-8lgfth) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/1d32e05d3a55e9fdfc343c30d92b4715f115d5f5/src/resolvers/serchResults.ts#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about artifact.artifact_id and items_total?
</blockquote></details>

artifact.artifact_id is used on the frontend side.
Sorry about items_total missed it by mistake, now added

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/serchResults.ts, line 110 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu8yWXz8ad8KeDs9LZM:-LuBqiWUDFK710CiQRLR:b-4c7wwd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/1d32e05d3a55e9fdfc343c30d92b4715f115d5f5/src/resolvers/serchResults.ts#L110)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

artifact.artifact_id is used on the frontend side.
Sorry about items_total missed it by mistake, now added

</blockquote></details>

artifact_name is also used

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

___
*[src/resolvers/serchResults.ts, line 80 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu8xXuHCzZEW_RsYcYn:-LuBwLpdEPXJAamj8QkG:b-80tlqx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/1d32e05d3a55e9fdfc343c30d92b4715f115d5f5/src/resolvers/serchResults.ts#L80)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

We have a slight problem in the new query if omit it, but the other original query works fine (Please let discuss it before I make changes).
</blockquote></details>

Sure!
___
*[src/resolvers/serchResults.ts, line 110 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu8yWXz8ad8KeDs9LZM:-LuBsBAz1d4pVvRPo0qE:b-jicg5k) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/1d32e05d3a55e9fdfc343c30d92b4715f115d5f5/src/resolvers/serchResults.ts#L110)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

artifact_name is also used 
</blockquote></details>

But then this should be considered a frontend issue - having the same information in the response twice is not ideal. :)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/serchResults.ts, line 110 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-Lu8yWXz8ad8KeDs9LZM:-LuCUDXf1Flga0IsNpov:b7xgzaa) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/1d32e05d3a55e9fdfc343c30d92b4715f115d5f5/src/resolvers/serchResults.ts#L110)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But then this should be considered a frontend issue - having the same information in the response twice is not ideal. :)
</blockquote></details>

No issue after all, with the new changes (Please confirm if I am not missing anything)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/resolvers/serchResults.ts, line 75 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-LuWSyxA45dbxbrjOYe8:-LuWSyxA45dbxbrjOYe9:b-1caqvn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/95b8b39ddb69b84c4e3ebc0e99e0f12cf727ecb4/src/resolvers/serchResults.ts#L75)):*
> ```XML
>      ORDER BY "observation_time.start_time" DESC
>   `;
> ```

I would suggest to choose more expressive aliases and to include AS explicitly, to make the SQL a bit easier to understand:

  const sql = `
     WITH cte AS (
       SELECT ${Array.from(fields).join(", ")}
       FROM ${sqlFrom}
       WHERE ${whereDetails.sql}
     )
     SELECT *
     FROM (
       TABLE cte
       ORDER BY cte."observation_time.start_time" DESC
       LIMIT \$${whereDetails.values.length + 1}
       OFFSET \$${whereDetails.values.length + 2} 
     ) AS search_results
     RIGHT JOIN (SELECT COUNT(*) FROM cte) AS search_results_count (items_total) ON true
     ORDER BY "observation_time.start_time" DESC
  `;

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/serchResults.ts, line 75 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/63#-LuWSyxA45dbxbrjOYe8:-LuWwUOM-qVWaDpM-3Vr:b-bu91xm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/95b8b39ddb69b84c4e3ebc0e99e0f12cf727ecb4/src/resolvers/serchResults.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to choose more expressive aliases and to include AS explicitly, to make the SQL a bit easier to understand:

  const sql = `
     WITH cte AS (
       SELECT ${Array.from(fields).join(", ")}
       FROM ${sqlFrom}
       WHERE ${whereDetails.sql}
     )
     SELECT *
     FROM (
       TABLE cte
       ORDER BY cte."observation_time.start_time" DESC
       LIMIT \$${whereDetails.values.length + 1}
       OFFSET \$${whereDetails.values.length + 2} 
     ) AS search_results
     RIGHT JOIN (SELECT COUNT(*) FROM cte) AS search_results_count (items_total) ON true
     ORDER BY "observation_time.start_time" DESC
  `;

</blockquote></details>

Updated

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/63)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
