### PR TITLE
Tables

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)

### CODE REVIEW

**Review by chynamyerz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/db/tables.sql, line 83 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk2voVK495tLnSEzd-P:-Lk2voVK495tLnSEzd-Q:bbv00tz) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/768e5851411f4e818f33627d2bd0d9cee5f69ff6/src/db/tables.sql#L83)):*
> ```TSQL
> 
> DROP TABLE IF EXISTS `DataRequestFiles`;
> CREATE TABLE `dataRequest` (
> ```

dataRequest or dataRequestFile?

Take note of the naming convention (table name should start with uppercase character)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

___
*[src/db/tables.sql, line 83 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk2voVK495tLnSEzd-P:-Lk304n_2PaV5t7B6UWm:b-733219) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/768e5851411f4e818f33627d2bd0d9cee5f69ff6/src/db/tables.sql#L83)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

dataRequest or dataRequestFile?

Take note of the naming convention (table name should start with uppercase character)
</blockquote></details>

Ahh yes thank fixed now

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

___
*[src/db/tables.sql, line 83 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk2voVK495tLnSEzd-P:-Lk30GB40OiGXMZlP_r8:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/768e5851411f4e818f33627d2bd0d9cee5f69ff6/src/db/tables.sql#L83)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Ahh yes thank fixed now
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

___
*[src/db/tables.sql, line 1 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk3BBEO0U7f-6hu6Azx:-Lk3BBEP2R5TkxWbzMI0:b-3l54r4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c3633f0f40ed0e3fc0daa98389e02a404ba7945a/src/db/tables.sql#L1)):*
> ```TSQL
> use `ssda-prisma`;
> ```

Maybe rather call this something like ssda-admin?
___
*[src/db/tables.sql, line 3 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk3Sm028HKIHtQvZhmk:-Lk3Sm028HKIHtQvZhml:b9s908m) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c3633f0f40ed0e3fc0daa98389e02a404ba7945a/src/db/tables.sql#L3)):*
> ```TSQL
> use `ssda-prisma`;
> SET FOREIGN_KEY_CHECKS=0;
> --
> ```

I'd suggest to order the tables alphabetically. :)
___
*[src/db/tables.sql, line 26 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk3CdLY-o6wy4Zz0MBP:-Lk3CdLY-o6wy4Zz0MBQ:b-ikseix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c3633f0f40ed0e3fc0daa98389e02a404ba7945a/src/db/tables.sql#L26)):*
> ```TSQL
>   PRIMARY KEY (`dataRequestStatusId`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> INSERT INTO `DataRequestStatus` (`dataRequestStatus`) values ("SUCCESSFUL"), ("PENDING"), ("FAILED");
> ```

Didn't we have an option 'EXPIRED' as well?

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/db/tables.sql, line 1 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk3BBEO0U7f-6hu6Azx:-Lk8gZqA6DfuZVsVs6t1:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c3633f0f40ed0e3fc0daa98389e02a404ba7945a/src/db/tables.sql#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather call this something like ssda-admin?
</blockquote></details>

Done.
___
*[src/db/tables.sql, line 3 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk3Sm028HKIHtQvZhmk:-Lk8gaSv4_S6Zgh6_1kO:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c3633f0f40ed0e3fc0daa98389e02a404ba7945a/src/db/tables.sql#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to order the tables alphabetically. :)
</blockquote></details>

Done.
___
*[src/db/tables.sql, line 26 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk3CdLY-o6wy4Zz0MBP:-Lk8gb_i6SmaE2zqvg5g:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c3633f0f40ed0e3fc0daa98389e02a404ba7945a/src/db/tables.sql#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Didn't we have an option 'EXPIRED' as well?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: all files reviewed, 3 unresolved discussions (waiting on @chynamyerz and @Eb-Zeero)

___
*[README.md, line 33 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkPDiffACWhIo8suHu2:-LkPDiffACWhIo8suHu3:b-klrj7l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/87928ed9c4dd16218cbf3a709dfd2c1cff58e301/README.md#L33)):*
> ```Markdown
> ---- | ---- | ----
> APP_SECRET | The secret key for this server | anothertopsecretkey
> BASE_FITS_DIRS | Base directory where the fits files are located | /home/user/data
> ```

BASE_FITS_DIR should read FITS_BASE_DIR.

fits should preferably read FITS.
___
*[src/db/tables.sql, line 26 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-Lk3CdLY-o6wy4Zz0MBP:-LkPFOLeAw4vuGBxDV-_:b-izjkh1) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c3633f0f40ed0e3fc0daa98389e02a404ba7945a/src/db/tables.sql#L26)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh. I might have been wrong here. We probably decided to check whether the data request file still exists rather than relying on a database entry. Sorry.
___
*[src/db/tables.sql, line 34 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkPFoSO42osqzhBw-6g:-LkPFoSO42osqzhBw-6h:b-nqu4cl) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/87928ed9c4dd16218cbf3a709dfd2c1cff58e301/src/db/tables.sql#L34)):*
> ```TSQL
> 
> CREATE TABLE `DataRequestFile` (
>   `dataRequestId` INT(11) UNSIGNED NOT NULL  COMMENT "An Id for a table ``DataRequest",
> ```

The type of fileId will have to change, I guess.

**Review by chynamyerz — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

**Review by chynamyerz — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[README.md, line 33 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkPDiffACWhIo8suHu2:-LkUQMwKDu5jRlyvig9-:bvljs2o) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c81c815374088d9fbe8e1625c27e7e460aa8550b/README.md#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

BASE_FITS_DIR should read FITS_BASE_DIR.

fits should preferably read FITS.
</blockquote></details>

Addressed.
___
*[src/db/tables.sql, line 34 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkPFoSO42osqzhBw-6g:-LkUQPWxDvU8g3iWSkbE:b-bu91xm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c81c815374088d9fbe8e1625c27e7e460aa8550b/src/db/tables.sql#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The type of fileId will have to change, I guess.
</blockquote></details>

Updated

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/db/tables.sql, line 35 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVd2tjALA5pZr02Ns7:-LkVd2tjALA5pZr02Ns8:b-z86xj5) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c81c815374088d9fbe8e1625c27e7e460aa8550b/src/db/tables.sql#L35)):*
> ```TSQL
> CREATE TABLE `DataRequestFile` (
>   `dataRequestId` INT(11) UNSIGNED NOT NULL  COMMENT "An Id for a table ``DataRequest",
>   `fileId` INT(11) UNSIGNED NOT NULL COMMENT "An id from SSDA for a data file this need to be checked before it is created",
> ```

How about changing the comment to "The unique identifier for the data file. This must be the same as the identifier assigned in the SSDA database for this data file."?

We probably should find a decent name for "SSDA database"...
___
*[src/db/tables.sql, line 26 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVeXLY5tspRQjtmF2y:-LkVeXLY5tspRQjtmF2z:b-2fmj0n) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L26)):*
> ```TSQL
>   CONSTRAINT `fk_DataRequestDataRequestStatus` FOREIGN KEY (`dataRequestStatusId`) REFERENCES `DataRequestStatus` (`dataRequestStatusId`) ON DELETE NO ACTION ON UPDATE NO ACTION
> 
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> ```

I'd suggest to order the tables alphabetically.
___
*[src/db/tables.sql, line 28 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVefF72WPApnHvoZRX:-LkVefF72WPApnHvoZRY:b-uga216) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L28)):*
> ```TSQL
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
> ```

The handling of users needs revision.
___
*[src/db/tables.sql, line 36 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVcrmN9ghJMYzVOuoc:-LkVcrmN9ghJMYzVOuod:b98wra4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L36)):*
> ```TSQL
> CREATE TABLE `DataRequestObservation` (
>   `dataRequestObservationId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT "Primary key",
>   `dataRequestObservationName` VARCHAR(255) NOT NULL COMMENT "Data request observation name",
> ```

We might as well just call the column `name`... :-)
___
*[src/db/tables.sql, line 52 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVeMCb164fqwuLHLEh:-LkVeMCb164fqwuLHLEi:belfyhq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L52)):*
> ```TSQL
>   `dataRequestFileId` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT "Primary key",
>   `dataRequestObservationId` INT(11) UNSIGNED NOT NULL  COMMENT "An Id for a table DataRequestObservation",
>   `fileId` BINARY(16) NOT NULL COMMENT "An id from SSDA for a data file this need to be checked before it is created",
> ```

We should have a name column as well.
___
*[src/db/tables.sql, line 53 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVdrID3sVoANnVlH5l:-LkVdrID3sVoANnVlH5m:b-x7213q) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L53)):*
> ```TSQL
>   `dataRequestObservationId` INT(11) UNSIGNED NOT NULL  COMMENT "An Id for a table DataRequestObservation",
>   `fileId` BINARY(16) NOT NULL COMMENT "An id from SSDA for a data file this need to be checked before it is created",
>   PRIMARY KEY (`dataRequestFileId` ),
> ```

There is superfluous space between "`dataRequestFileId`" and ")".

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/23)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[src/db/tables.sql, line 35 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVd2tjALA5pZr02Ns7:-LkXeODZ0z_PAEeqCD2-:b-g11ifv) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c81c815374088d9fbe8e1625c27e7e460aa8550b/src/db/tables.sql#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about changing the comment to "The unique identifier for the data file. This must be the same as the identifier assigned in the SSDA database for this data file."?

We probably should find a decent name for "SSDA database"...
</blockquote></details>

We can discuss it today.
___
*[src/db/tables.sql, line 26 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVeXLY5tspRQjtmF2y:-LkXertb8icXjBP66v_G:bb6un1j) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to order the tables alphabetically.
</blockquote></details>

Done
___
*[src/db/tables.sql, line 28 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVefF72WPApnHvoZRX:-LkXeXoH1IX-N2Qcp8cv:bemtuye) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The handling of users needs revision.
</blockquote></details>

We can discuss about it today as well.
___
*[src/db/tables.sql, line 36 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVcrmN9ghJMYzVOuoc:-LkXebmb9xKlpm9kfMTm:b70fq1t) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We might as well just call the column `name`... :-)
</blockquote></details>

It was a long field bane neh :-)
___
*[src/db/tables.sql, line 52 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVeMCb164fqwuLHLEh:-LkXeTiyA2ZghhUNZtUO:b-8b11j9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We should have a name column as well.
</blockquote></details>

Added
___
*[src/db/tables.sql, line 53 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/23#-LkVdrID3sVoANnVlH5l:-LkXeUrA10EZLagmXEpL:b-ucfkn4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e14d68a2a743a28035756e8165a7abf02625463e/src/db/tables.sql#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is superfluous space between "`dataRequestFileId`" and ")".
</blockquote></details>

Thanks.

**Pull request closed without merging**
