### PR TITLE
Password reset

### PR DESCRIPTION
**Pull request by Eb-Zeero**
Backend

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/createServer.ts, line 176 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LdhZ09C6NuD_xHL8LG-:-LdhZ09C6NuD_xHL8LG0:bxrry5q) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/dec0dceed831ebc9aa523dd5d2758d4c0ed56789/src/createServer.ts#L176)):*
> ```XML
>   });
> 
>   // Returning the server
> ```

This endpoint seems unnecessary, and I've removed it.
___
*[src/util.ts, line 21 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LdiLwlN8rYMpZpNX1Hw:-LdiLwlN8rYMpZpNX1Hx:b-eh167l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14ddf12a1c0b86313fb33ccda0803b73509bb4e2/src/util.ts#L21)):*
> ```XML
> const transporter = nodemailer.createTransport({
>     auth: {
>         pass: process.env.MAIL_PASS,
> ```

Changed to MAIL_PASSWORD
___
*[src/__tests__/util.spec.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LdiGckI1E84jX8j6jIv:-LdiGckI1E84jX8j6jIw:b-8st1x2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14ddf12a1c0b86313fb33ccda0803b73509bb4e2/src/__tests__/util.spec.ts#L1)):*
> ```XML
> import { groupDataFileByPart } from "../util";
> ```

I'll remove this file as it is covered in the data-request branch.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 176 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LdhZ09C6NuD_xHL8LG-:-Ldiw4un2T91S85cB579:bu8tmp8) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/dec0dceed831ebc9aa523dd5d2758d4c0ed56789/src/createServer.ts#L176)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This endpoint seems unnecessary, and I've removed it.
</blockquote></details>

how so? because the email link take the user to this end point to check if the user if the token is still valid and it will redirect to the correct frontend page.  
___
*[src/util.ts, line 21 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LdiLwlN8rYMpZpNX1Hw:-LdivmlfCBmhvBbi7eVW:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14ddf12a1c0b86313fb33ccda0803b73509bb4e2/src/util.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Changed to MAIL_PASSWORD
</blockquote></details>

Done.
___
*[src/__tests__/util.spec.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LdiGckI1E84jX8j6jIv:-Ldivlfn3UDVJ8mJL_rV:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14ddf12a1c0b86313fb33ccda0803b73509bb4e2/src/__tests__/util.spec.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'll remove this file as it is covered in the data-request branch.
</blockquote></details>

Done.

**Review by hettlage — DISMISSED** [review]
> Reviewed 7 of 13 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[package.json, line 12 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGFIpj0PieJKUb0iTn:-LeGFIpj0PieJKUb0iTo:b-fgxn7w) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/package.json#L12)):*
> ```JSON
>     "start": "pm2 start src/index.ts --node-args='-r dotenv/config'",
>     "deploy": "export DEBUG=\"prisma\"; cd src/; prisma deploy --env-file ../.env",
>     "dev": " export DEBUG=\\\\\\\"nodemon\\\\\\\"; nodemon -e ts,graphql -x ts-node -r dotenv/config src/index.ts",
> ```

Why all these backslashes?
___
*[src/createServer.ts, line 12 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGFX-5-Xjo7PBdFRO7:-LeGFX-5-Xjo7PBdFRO8:b-7b1lms) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/createServer.ts#L12)):*
> ```XML
> // Set up Sentry
> // Sentry.init({
> //   dsn: process.env.SENTRY_DSN
> ```

These lines should be uncommented again.
___
*[src/schema.graphql, line 15 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGGEd32Vjdqha1NzpV:-LeGGEd32Vjdqha1NzpW:b-ekuefk) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/schema.graphql#L15)):*
> ```GraphQL
>   Checks if the given token is valid.
>   """
>   verifyPasswordResetToken(token: String!): Success
> ```

"Verifying" isn't querying, really. So may be this should be something like "userForResetToken" or "passwordResetTokenStatus"?
___
*[src/schema.graphql, line 104 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGHxaM9kaF9-iMdkmy:-LeGHxaM9kaF9-iMdkmz:by1x2b3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/schema.graphql#L104)):*
> ```GraphQL
> 
> 
> type Success {
> ```

Maybe a name like "Status" would be slightly more precise?
___
*[src/__mocks__/util.ts, line 1 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeHzFhHArOQatuLjmba:-LeHzFhI72kwISoalXlM:b-p4zxr4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/__mocks__/util.ts#L1)):*
> ```XML
> const transporter: any = jest.genMockFromModule("..");
> ```

That looks odd, as you do  ot seem to muck the util module.
___
*[src/__tests__/passwordReset.test.ts, line 6 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeHzWYZB2x5-M3A4zyW:-LeHzWYZB2x5-M3A4zyX:bfvihaj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/__tests__/passwordReset.test.ts#L6)):*
> ```XML
> import { prisma } from "../generated/prisma-client";
> import { resolvers } from "../resolvers";
> import { IContext, transporter } from "../util";
> ```

You should safeguard against using the transporter when testing. (This should be prevented by using a different (invalid) mail host environment variable for testing.)
___
*[src/__tests__/passwordReset.test.ts, line 138 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGO1zE8q93cD-EmK_w:-LeGO1zE8q93cD-EmK_x:bd2k5rr) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/__tests__/passwordReset.test.ts#L138)):*
> ```XML
> 
> describe("reset password", () => {
>   it("should fail if password is not given or length less that 7 and token not given", async () => {
> ```

Unit tests should be split up into different "it's".
___
*[src/resolvers/Query.ts, line 23 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeI1Y35D7C4F7WJYEa2:-LeI1Y368fPL0pPI9S4E:b-nuqgv3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/resolvers/Query.ts#L23)):*
> ```XML
>     });
>   },
>   async verifyPasswordResetToken(
> ```

See the comment on the name for the GraphQL mutation.
___
*[src/resolvers/resetPassword.ts, line 70 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGLUcR9K-jjNvlB9iv:-LeGLUcS3lUMnZu5EpLO:bvhxhhs) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14ddf12a1c0b86313fb33ccda0803b73509bb4e2/src/resolvers/resetPassword.ts#L70)):*
> ```XML
>   const hashedPassword = await bcrypt.hash(password, 10);
> 
>   // updating the user with the new password and expire the token
> ```

Wouldn't you rather delete the token?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)* status: 12 of 16 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[package.json, line 12 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGFIpj0PieJKUb0iTn:-LfV3MmD59vHMu1KnWoG:b-9ske8d) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/package.json#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why all these backslashes?
</blockquote></details>

sorry there were other  debugs beside nodemon now  removed.
___
*[src/createServer.ts, line 176 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LdhZ09C6NuD_xHL8LG-:-LfV3yCU4NdEtYgp-mSG:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/dec0dceed831ebc9aa523dd5d2758d4c0ed56789/src/createServer.ts#L176)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

how so? because the email link take the user to this end point to check if the user if the token is still valid and it will redirect to the correct frontend page.  
</blockquote></details>

Done.
___
*[src/createServer.ts, line 12 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGFX-5-Xjo7PBdFRO7:-LfV3sN_1URpouzbUWw6:b-ixaip3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/createServer.ts#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These lines should be uncommented again.
</blockquote></details>

done and condition added
___
*[src/schema.graphql, line 15 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGGEd32Vjdqha1NzpV:-LfV4qLe4PSmRJlUUDNl:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/schema.graphql#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Verifying" isn't querying, really. So may be this should be something like "userForResetToken" or "passwordResetTokenStatus"?
</blockquote></details>

Done.
___
*[src/schema.graphql, line 104 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGHxaM9kaF9-iMdkmy:-LfV4r1B-tTMt7UYNZJn:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/schema.graphql#L104)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe a name like "Status" would be slightly more precise?
</blockquote></details>

Done.
___
*[src/__mocks__/util.ts, line 1 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeHzFhHArOQatuLjmba:-LfV5557ByV5E97bs75J:b4bo6vj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/__mocks__/util.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That looks odd, as you do  ot seem to muck the util module.
</blockquote></details>

this is how nodemailer is tested or how I know to test it
___
*[src/__tests__/passwordReset.test.ts, line 6 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeHzWYZB2x5-M3A4zyW:-LfV5SG-AZ8VsU5nj0x2:boaywdr) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/__tests__/passwordReset.test.ts#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should safeguard against using the transporter when testing. (This should be prevented by using a different (invalid) mail host environment variable for testing.)
</blockquote></details>

it is actually hitting the the mock defined on __mocks__/util.ts not the real transporter
___
*[src/__tests__/passwordReset.test.ts, line 138 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGO1zE8q93cD-EmK_w:-LfV70IhBtA8iyKsU1Qm:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/__tests__/passwordReset.test.ts#L138)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Unit tests should be split up into different "it's".
</blockquote></details>

Done.
___
*[src/resolvers/Query.ts, line 23 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeI1Y35D7C4F7WJYEa2:-LfV77_SAWYVO0w_TAvX:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0f4dc6153bfccc7f9eec1a86585bbcc04e920f74/src/resolvers/Query.ts#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See the comment on the name for the GraphQL mutation.
</blockquote></details>

Done.
___
*[src/resolvers/resetPassword.ts, line 70 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/14#-LeGLUcR9K-jjNvlB9iv:-LfV79Tt7iGjZpyUGFVS:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14ddf12a1c0b86313fb33ccda0803b73509bb4e2/src/resolvers/resetPassword.ts#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't you rather delete the token?
</blockquote></details>

Done.

**Review by saltastroops — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 7 of 14 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage)

**Review by saltastroops — APPROVED** [review]
> Reviewed 2 of 13 files at r2, 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage)

**Review by saltastroops — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage)

**Review by saltastroops — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/14)* status: all files reviewed, 12 unresolved discussions (waiting on @hettlage)

**Pull request closed without merging**
