### PR TITLE
Added user authentication and tests

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)

### CODE REVIEW

**Review by saltastroops — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: 4 of 13 files reviewed, 3 unresolved discussions (waiting on @chynamyerz)

___
*[package.json, line 13 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LY8_eEG0We-QA2XrghT:-LY8_eEG0We-QA2XrghU:b-wanrcw) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a0a11b2e1f75307967d2c23bcd529237acbc671e/package.json#L13)):*
> ```JSON
>     "deploy": "cd src/; prisma deploy --env-file ../.env",
>     "dev": "nodemon -e ts,graphql -x ts-node -r dotenv/config src/index.ts",
>     "test": "jest",
> ```

Doesn't jest set NODE_ENV to test.(see https://jestjs.io/docs/en/getting-started)?
___
*[__tests__/userAthentication.spec.ts, line 19 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LY8bIuM4ctIYp8bRDH1:-LY8bIuNCgdIjs1guU3M:bbm0vl4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14b91f81b7e16346f1b6ba3937dc451a6c92237e/__tests__/userAthentication.spec.ts#L19)):*
> ```XML
> beforeAll(() => {
>   // Mocking users query
>   prisma.users = jest.fn(async () => await [{
> ```

Why do you mock resolvers later on if you've mocked Prisma already.

You might also have a look at https://jestjs.io/docs/en/manual-mocks regarding the way to mock node modules (like Prisma).
___
*[src/resolvers/Query.ts, line 6 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LY8d3b27LkpZUN-Sig1:-LY8d3b37B1pepWFYHC_:b-2ii5qr) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14b91f81b7e16346f1b6ba3937dc451a6c92237e/src/resolvers/Query.ts#L6)):*
> ```XML
> const Query = {
>   // Query for users
>   users(root: any, args: any, ctx: any) {
> ```

Where possible you should be more explicit with the argument types (i.e. don't use any).

Can you add a TODO indicating that these resolvers need to be rewritten?

**Comment by chynamyerz** [comment]
___
*[__tests__/userAthentication.spec.ts, line 19 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LY8bIuM4ctIYp8bRDH1:-LYB0qv7A_ON0FbXKXlR:b-uyiteb) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14b91f81b7e16346f1b6ba3937dc451a6c92237e/__tests__/userAthentication.spec.ts#L19)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Why do you mock resolvers later on if you've mocked Prisma already.

You might also have a look at https://jestjs.io/docs/en/manual-mocks regarding the way to mock node modules (like Prisma).
</blockquote></details>

Wow! I must admit, I didn't see it but now it makes sense, thanks.

**Comment by chynamyerz** [comment]
___
*[src/resolvers/Query.ts, line 6 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LY8d3b27LkpZUN-Sig1:-LYBRN8Z-XY5yJJUgWqA:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14b91f81b7e16346f1b6ba3937dc451a6c92237e/src/resolvers/Query.ts#L6)):*
<details><summary><i>Previously, saltastroops wrote…</i></summary><blockquote>

Where possible you should be more explicit with the argument types (i.e. don't use any).

Can you add a TODO indicating that these resolvers need to be rewritten?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: all files reviewed, 8 unresolved discussions (waiting on @chynamyerz and @saltastroops)

___
*[__tests__/userAthentication.spec.ts, line 19 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LY8bIuM4ctIYp8bRDH1:-LYQf1jT96ijoqwJ0ASE:b-ke5esk) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14b91f81b7e16346f1b6ba3937dc451a6c92237e/__tests__/userAthentication.spec.ts#L19)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Wow! I must admit, I didn't see it but now it makes sense, thanks.
</blockquote></details>

Logging in is not tested.  Some tests might not belong in this file.
___
*[src/createServer.ts, line 62 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQgsIW9dzFDms3ZgOP:-LYQgsIW9dzFDms3ZgOQ:bv7sd37) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/createServer.ts#L62)):*
> ```XML
>       rolling: false,
>       saveUninitialized: true,
>       secret: "keyboard cat",
> ```

Code contains secret
___
*[src/createServer.ts, line 116 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQhllQ-2XVDStSiZCo:-LYQhllQ-2XVDStSiZCp:bardz5h) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/createServer.ts#L116)):*
> ```XML
> };
> 
> export { createServer };
> ```

Shouldn't this be a default export?
___
*[src/schema.graphql, line 3 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQmpWDDI2UZLHuCSbY:-LYQmpWDDI2UZLHuCSbZ:b-qqqey4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/schema.graphql#L3)):*
> ```GraphQL
> # import * from './generated/prisma.graphql'
> 
> type Query {
> ```

All fields and parameters should be documented
___
*[src/resolvers/Query.ts, line 14 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQm2NR1jvjbsdigF7s:-LYQm2NR1jvjbsdigF7t:by65pv8) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/resolvers/Query.ts#L14)):*
> ```XML
>   },
> 
>   // To be well done when Authentication approved.
> ```

Please use "TODO" at the beginning of a todo, so that it can easily be picked up later.
___
*[src/resolvers/Query.ts, line 16 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQmMOa1VcscDC5SN6F:-LYQmMOa1VcscDC5SN6G:b-eovj01) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/resolvers/Query.ts#L16)):*
> ```XML
>   // To be well done when Authentication approved.
>   // Query for users
>   user(root: any, args: {}, ctx: { prisma: Prisma; user: { id: string } }) {
> ```

Define an interface for the context

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: all files reviewed, 9 unresolved discussions (waiting on @chynamyerz and @saltastroops)

___
*[src/createServer.ts, line 24 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQqsnf67ViR13CgKu-:-LYQqsng8HgOr7bA5nTo:b-f1aa3o) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/createServer.ts#L24)):*
> ```XML
>       async (username, password, done) => {
>         // Only retrieving a user with the supplied username.
>         const user = (await prisma.users({ where: { username, password } }))[0];
> ```

Password hashing is missing

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: 9 of 17 files reviewed, 9 unresolved discussions (waiting on @chynamyerz, @hettlage, and @saltastroops)

___
*[__tests__/userAthentication.spec.ts, line 19 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LY8bIuM4ctIYp8bRDH1:-LYB14xO59d8G1_rMX-2:b-tofdn2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/14b91f81b7e16346f1b6ba3937dc451a6c92237e/__tests__/userAthentication.spec.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Logging in is not tested.  Some tests might not belong in this file.
</blockquote></details>

Now added and removed unnecessary test.

Done.
___
*[src/createServer.ts, line 24 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQqsnf67ViR13CgKu-:-LYSJKyp0WH-BEdrXgY_:b9y0hkn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/createServer.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Password hashing is missing
</blockquote></details>

Password now hashed.
___
*[src/createServer.ts, line 62 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQgsIW9dzFDms3ZgOP:-LYSJPQT1huFNe8Ydp7o:b-8p22im) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/createServer.ts#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Code contains secret
</blockquote></details>

Oops! sorted.

Done.
___
*[src/createServer.ts, line 116 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQhllQ-2XVDStSiZCo:-LYSJShp6tBl-rdy8pgt:b34euu6) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/createServer.ts#L116)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be a default export?
</blockquote></details>

Default. 

Done.
___
*[src/schema.graphql, line 3 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQmpWDDI2UZLHuCSbY:-LYSJYJPArgkmT2aavX6:b-wwgrqq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/schema.graphql#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

All fields and parameters should be documented
</blockquote></details>

Added document.
___
*[src/resolvers/Query.ts, line 14 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQm2NR1jvjbsdigF7s:-LYSJevI6Gu39BNO3XRQ:bvsw36t) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/resolvers/Query.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Please use "TODO" at the beginning of a todo, so that it can easily be picked up later.
</blockquote></details>

Included TODO
___
*[src/resolvers/Query.ts, line 16 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/4#-LYQmMOa1VcscDC5SN6F:-LYSJc5T4xD69tsEVLqx:b-wjvhzj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c8b5f599d6f51a939bfb34439d064043e8b921cd/src/resolvers/Query.ts#L16)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Define an interface for the context
</blockquote></details>

Interface defined.

**Review by hettlage — DISMISSED** [review]
> Reviewed 6 of 8 files at r4, 1 of 9 files at r8, 11 of 11 files at r9.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: all files reviewed, 9 unresolved discussions (waiting on @chynamyerz, @hettlage, and @saltastroops)

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: all files reviewed, 3 unresolved discussions (waiting on @chynamyerz and @saltastroops)

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: all files reviewed, 3 unresolved discussions (waiting on @saltastroops)

**Review by hettlage — APPROVED** [review]
> Dismissed @saltastroops from a discussion.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: all files reviewed, 2 unresolved discussions (waiting on @saltastroops)

**Review by saltastroops — APPROVED** [review]
> Reviewed 2 of 13 files at r1, 2 of 7 files at r2, 3 of 8 files at r4, 1 of 9 files at r8, 11 of 11 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/4)* status: all files reviewed, 2 unresolved discussions (waiting on @saltastroops)

**Pull request merged**
