### PR TITLE
Fix observation Id in README file of donwload

### LINKED ISSUE #173: Consider using something else besides observation id in README file
The README file for the downloaded data sometimes shows observation id as "SALT-" and not "SALT-23457", because of this we should consider using something else besides observation id

### PR DESCRIPTION
**Pull request by Lonwabo11**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/180)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/180)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hettlage and @Lonwabo11)

___
*[src/util/zipDataRequest.ts, line 106 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/180#-MDEoIt4C5kKMfNu3Eoj:-MDEoIt50UTp6eoSnpld:b12inli) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/718a99d7a862551238d05cbcdbfbfad9ecce2ab5/src/util/zipDataRequest.ts#L106)):*
> ```XML
>         df.observation_id = "SALT";
>       }
> ```

There actually might be another issue here as well. Some of the observation ids are like "SALT-3ce6e624e244d914eaa69a3cd3c99edc". It would make sense to only include the first, say, eight characters after the dash (like "SALT-3ce6e6"). This can be simplified by saying that always only the first 5 (for "SALT-") + 8 = 13 characters should be used for the observation id in the README.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/180)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 106 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/180#-MDEoIt4C5kKMfNu3Eoj:-MDFMRDDA1GC2P6XVR20:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/718a99d7a862551238d05cbcdbfbfad9ecce2ab5/src/util/zipDataRequest.ts#L106)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There actually might be another issue here as well. Some of the observation ids are like "SALT-3ce6e624e244d914eaa69a3cd3c99edc". It would make sense to only include the first, say, eight characters after the dash (like "SALT-3ce6e6"). This can be simplified by saying that always only the first 5 (for "SALT-") + 8 = 13 characters should be used for the observation id in the README. 
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/180)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[src/util/zipDataRequest.ts, line 107 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/180#-MDFhVOX3JBR9j0uBArs:-MDFhVOX3JBR9j0uBArt:b-tzsgba) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9a19c1418fa0090baef7c83323d6d5fbb71fe2b5/src/util/zipDataRequest.ts#L107)):*
> ```XML
>       }
> 
>       if (df.observation_id.length > 10) {
> ```

Why 10 rather than 13?

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/180)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/util/zipDataRequest.ts, line 107 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/180#-MDFhVOX3JBR9j0uBArs:-MDJZw_g14q36fVIsIf0:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9a19c1418fa0090baef7c83323d6d5fbb71fe2b5/src/util/zipDataRequest.ts#L107)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why 10 rather than 13?
</blockquote></details>

Done.

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/180)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/180)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
