### PR TITLE
updated doc where neccessary

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/157)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/157)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

*[a discussion](https://reviewable.io/reviews/saltastroops/data-archive-backend/157#-MBUeTZJ0Yo5OjMJRoo4:-MBUeTZJ0Yo5OjMJRoo5:biazvpj) (no related file):*
For simplicity, I will "merge" my changes to the documentation with yours and submit to this branch.

---
___
*[docs/server_setup.md, line 99 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/157#-MBUeDI7DRS4LRmX8g1y:-MBUeDI7DRS4LRmX8g1z:b-w9t9gs) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/10e1ec8bb15ce21b9f7125975d1e0e7ac79f2b86/docs/server_setup.md#L99)):*
> ```Markdown
> 
> After pm2 is added glabaly, sometimes it is not recorgnized. If that is the case, the pm2 path need to be added to the system environment path.
> Using sudo privileges, open the file `/etc/environment` and the path below.
> ```

As this is a directory for a user I don't think it should be available system-wide.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/157)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hettlage)

*[a discussion](https://reviewable.io/reviews/saltastroops/data-archive-backend/157#-MBUeTZJ0Yo5OjMJRoo4:-MBYG6VUBGQcTZ6dRQB0:bwxxmos) (no related file):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For simplicity, I will "merge" my changes to the documentation with yours and submit to this branch.
</blockquote></details>

Reviewed

---
___
*[docs/server_setup.md, line 99 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/157#-MBUeDI7DRS4LRmX8g1y:-MBYFxC_71_vsdFLrShC:b-6ql483) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/10e1ec8bb15ce21b9f7125975d1e0e7ac79f2b86/docs/server_setup.md#L99)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As this is a directory for a user I don't think it should be available system-wide.
</blockquote></details>

Thanks for taking this.

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/157)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/157)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
