### PR TITLE
User registration code and tests implementation

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/7)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 10 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/7)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @chynamyerz)

___
*[src/createServer.ts, line 40 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYhkpHu1sw8noW6np3v:-LYhkpHu1sw8noW6np3w:b-aza2a1) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e3e36484d6735dc20f7537bfece708f26480a1a5/src/createServer.ts#L40)):*
> ```XML
>         // Check if the user exist and return it content for use in subsequent request.
>         if (user && (await bcrypt.compare(password, user.password))) {
>           done(null, { id: user.id, name: user.name, username: user.username });
> ```

The full user object should be used. I'll update the file accordingly.
___
*[src/datamodel.prisma, line 2 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYhlCVyBstxgIRkvNDL:-LYhlCVyBstxgIRkvNDM:bbhkpp1) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/29173eff82eb14da633451f84fd305a32a5e8e68/src/datamodel.prisma#L2)):*
> ```
> # TODO UPDATE
> type User {
> ```

Permissions are missing.
___
*[src/schema.graphql, line 27 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYhlfR8BxX6XvYgdcFY:-LYhlfR8BxX6XvYgdcFZ:b-lk44gt) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/29173eff82eb14da633451f84fd305a32a5e8e68/src/schema.graphql#L27)):*
> ```GraphQL
>     email: String!
>     affiliation: String!
>     password: String!
> ```

Should we enforce a minimum password length?

Use a custom User type. I'll update the schema accordingly.
___
*[src/__tests__/userRegistration.spec.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYi8wXjBbrzEhSFeRZp:-LYi8wXjBbrzEhSFeRZq:be2potm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/29173eff82eb14da633451f84fd305a32a5e8e68/src/__tests__/userRegistration.spec.ts#L1)):*
> ```XML
> jest.mock("../generated/prisma-client");
> ```

I'd suggest you test the resolvers rather than making HTTP requests..

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/7)* status: 4 of 11 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 40 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYhkpHu1sw8noW6np3v:-LYlSMuN2cE8yFcE9SqR:b-9755fa) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/e3e36484d6735dc20f7537bfece708f26480a1a5/src/createServer.ts#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The full user object should be used. I'll update the file accordingly.
</blockquote></details>

Thank you.
___
*[src/datamodel.prisma, line 2 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYhlCVyBstxgIRkvNDL:-LYlSIt2-wnfKdgoLSry:b-bsb3nw) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/29173eff82eb14da633451f84fd305a32a5e8e68/src/datamodel.prisma#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Permissions are missing.
</blockquote></details>

role property added.
___
*[src/schema.graphql, line 27 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYhlfR8BxX6XvYgdcFY:-LYlS1Hb1M8SBz4_y-xH:b-ptzzkd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/29173eff82eb14da633451f84fd305a32a5e8e68/src/schema.graphql#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should we enforce a minimum password length?

Use a custom User type. I'll update the schema accordingly.
</blockquote></details>

required password should now enforce more than 6 characters.

Thank you for the updates
___
*[src/__tests__/userRegistration.spec.ts, line 1 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYi8wXjBbrzEhSFeRZp:-LYlRkid0eaizmYqaLsa:b-29kybn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/29173eff82eb14da633451f84fd305a32a5e8e68/src/__tests__/userRegistration.spec.ts#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest you test the resolvers rather than making HTTP requests..
</blockquote></details>

Now testing revolvers.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/7)* status: 10 of 11 files reviewed, 9 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/datamodel.prisma, line 2 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LYhlCVyBstxgIRkvNDL:-LZ5H3MDCvcjoqBu-5YY:b-ckym4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/29173eff82eb14da633451f84fd305a32a5e8e68/src/datamodel.prisma#L2)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

role property added.
</blockquote></details>

I'll add some documentation.
___
*[src/schema.graphql, line 80 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ5IT3W0dlNQ5jOI9hk:-LZ5IT3W0dlNQ5jOI9hl:b1bibuh) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/schema.graphql#L80)):*
> ```GraphQL
>   affiliation: String!
>   """
>   Role, which define the user's permissions.
> ```

Fixed typo.
___
*[src/__tests__/userRegistration.spec.ts, line 18 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ6COPQ4RfeIoV_etdt:-LZ6COPQ4RfeIoV_etdu:b-ku06rr) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/__tests__/userRegistration.spec.ts#L18)):*
> ```XML
> 
>   // Mocking the user query
>   (prisma.user as any).mockImplementation(async (where: UserWhereInput) => {
> ```

The signatures of the mock implementations are inconsistent with those of the mocked methods.
___
*[src/__tests__/userRegistration.spec.ts, line 73 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ6CnSG4sWbmrPzsEzO:-LZ6CnSG4sWbmrPzsEzP:bcjqb1k) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/__tests__/userRegistration.spec.ts#L73)):*
> ```XML
>     expect(prisma.createUser).toHaveBeenCalled();
> 
>     const argumentsWithoutPassword = delete { ...args }.password;
> ```

delete returns true or false, not an object.
___
*[src/__tests__/userRegistration.spec.ts, line 80 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ6HzRQ-3ifOFlFzfro:-LZ6HzRQ-3ifOFlFzfrp:btd2no8) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/__tests__/userRegistration.spec.ts#L80)):*
> ```XML
> 
>     // Expect the submitted user information to have been stored in the database.
>     expect(storedDataWithoutPassword).toBe(argumentsWithoutPassword);
> ```

toBe must be toEqual.
___
*[src/__tests__/userRegistration.spec.ts, line 121 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ6kSEi5SPVYQPse6nO:-LZ6kSEi5SPVYQPse6nP:b-r7sc2m) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/__tests__/userRegistration.spec.ts#L121)):*
> ```XML
>     };
> 
>     const response = await resolvers.Mutation.signup({}, args, {
> ```

Must check for error being thrown
___
*[src/resolvers/Mutation.ts, line 31 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ6kpca5hswxj70q-nS:-LZ6kpca5hswxj70q-nT:b-bd7fb4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/resolvers/Mutation.ts#L31)):*
> ```XML
>     // Check if submitted username does not contain uppercased character(s).
>     if (/[A-Z]/.test(args.username)) {
>       return new Error(
> ```

Errors must be thrown, not returned.
___
*[src/resolvers/Mutation.ts, line 45 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ6Vvn4Cmzx4dnSizbG:-LZ6Vvn4Cmzx4dnSizbH:btid9in) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/resolvers/Mutation.ts#L45)):*
> ```XML
>     }
> 
>     // Transform the email address to lower case.
> ```

You should check that the email address is valid.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/7)* status: all files reviewed, 9 unresolved discussions (waiting on @chynamyerz and @hettlage)

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/7)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/resolvers/Mutation.ts, line 31 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ6kpca5hswxj70q-nS:-LZ92GiV8mLkztccNLhR:bvmocn5) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/resolvers/Mutation.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Errors must be thrown, not returned.
</blockquote></details>

I see it fixed, thank you.
___
*[src/resolvers/Mutation.ts, line 45 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ6Vvn4Cmzx4dnSizbG:-LZ926hwDIPedo_Ue6nS:b-v6xalu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/39c317782ad7bd55e1b8d343c32205e0f7071ff6/src/resolvers/Mutation.ts#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should check that the email address is valid.
</blockquote></details>

Added this feature with it testing

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 5 files at r4, 1 of 2 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/7)* status: all files reviewed, 7 unresolved discussions (waiting on @chynamyerz)

___
*[src/resolvers/Mutation.ts, line 55 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/7#-LZ9cxhk-SfdtUbkOF04:-LZ9cxhk-SfdtUbkOF05:bywpzy5) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/90d003148f4cd49ca2a127a974d8afe30764df04/src/resolvers/Mutation.ts#L55)):*
> ```XML
> 
>     // Check if the submitted email address is valid
>     if (!validate(args.email, { minDomainAtoms: 2 })) {
> ```

Use library for validating email address

**Pull request merged**
