### PR TITLE
Admin user

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz)

___
*[src/createServer.ts, line 212 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-Lk4U9gfCOJbyZEPaifQ:-Lk4U9gfCOJbyZEPaifR:b-ulp4wa) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/6545a02d4d47f49110ad86808388639abe5544e0/src/createServer.ts#L212)):*
> ```XML
>     };
> 
>     // Check if the user is logged in
> ```

The user does not have to be logged in; non-logged in users may still access public data.
___
*[src/createServer.ts, line 297 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-Lk4Ualh75dspcIWh8Rm:-Lk4Ualh75dspcIWh8Rn:bofba57) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/6545a02d4d47f49110ad86808388639abe5544e0/src/createServer.ts#L297)):*
> ```XML
>       };
> 
>       // Check if the user is logged in
> ```

I would have thought that preview files are public by definition.
___
*[src/resolvers/Query.ts, line 119 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-Lk4Ut1r8bPRejnecc3J:-Lk4Ut1r8bPRejnecc3K:bt4s21) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/6545a02d4d47f49110ad86808388639abe5544e0/src/resolvers/Query.ts#L119)):*
> ```XML
>    */
>   async dataPreview(root: any, args: { dataFileId: number }, ctx: IContext) {
>     // Check if the user is logged in
> ```

I would have thought that previews are public by definition.
___
*[src/util/user.ts, line 9 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-Lk4V1zoEqXPrYmcuSnl:-Lk4V1zoEqXPrYmcuSnm:b-qfwh7l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/6545a02d4d47f49110ad86808388639abe5544e0/src/util/user.ts#L9)):*
> ```XML
>   user.roles.find((role: string) => role === "ADMIN");
> 
> export { isAdmin };
> ```

How about adding a unit test...? :-)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 212 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-Lk4U9gfCOJbyZEPaifQ:-Lk9RYvN2D9kCWZZhe47:b8rhjll) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/6545a02d4d47f49110ad86808388639abe5544e0/src/createServer.ts#L212)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The user does not have to be logged in; non-logged in users may still access public data.
</blockquote></details>

removed logged in user restriction
___
*[src/createServer.ts, line 297 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-Lk4Ualh75dspcIWh8Rm:-Lk9RWqU9TDQANwL6ZEg:b-ret2oy) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/6545a02d4d47f49110ad86808388639abe5544e0/src/createServer.ts#L297)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would have thought that preview files are public by definition.
</blockquote></details>

removed restrictions
___
*[src/resolvers/Query.ts, line 119 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-Lk4Ut1r8bPRejnecc3J:-Lk9RTBX-qtxXwc9nZzM:b-36biqc) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/6545a02d4d47f49110ad86808388639abe5544e0/src/resolvers/Query.ts#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would have thought that previews are public by definition.
</blockquote></details>

removed restrictions
___
*[src/util/user.ts, line 9 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-Lk4V1zoEqXPrYmcuSnl:-Lk9RPCJACZHfCHCaMb8:b9evq2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/6545a02d4d47f49110ad86808388639abe5544e0/src/util/user.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about adding a unit test...? :-)
</blockquote></details>

now available

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: all files reviewed, 8 unresolved discussions (waiting on @chynamyerz)

___
*[src/createServer.ts, line 230 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkNkyOB18fKp64ef4Z1:-LkNkyOB18fKp64ef4Z2:b-5k0mm8) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/createServer.ts#L230)):*
> ```XML
>     const { path: previewPath, publicFrom } = results[0];
> 
>     // Check for proprietary period, if still in the proprietary period
> ```

You should check for ownership as well. This probably should be done with a utility function which at the moment would just return false.
___
*[src/createServer.ts, line 232 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLa8Da2E7zPa0fnUJG:-LkLa8Db6aszJuv1drqc:b6rpcuw) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/createServer.ts#L232)):*
> ```XML
>     // Check for proprietary period, if still in the proprietary period
>     // Check that the user may download FITS files because they are an administrator.
>     // If the user is not an ADMIN, forbid the user from downloading.
> ```

There is a small problem: If there is no user, the file download would be possible. I'd suggest to drop the "req.user &&" and handle the case of a  missing req.user in isAdmin.
___
*[src/createServer.ts, line 360 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLb9Ta1SADiLMDivWq:-LkLb9Ta1SADiLMDivWr:b-uxnbs6) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f918c71d6ab423d93a31717e8e1391d979e45814/src/createServer.ts#L360)):*
> ```XML
>   // because they own the request or because they are an administrator.
>   const mayDownload =
>     (dataRequest as any).user.id === req.user.id ||
> ```

dataRequest probably should have its own type.
___
*[src/__tests__/util/user.test.ts, line 4 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLbmiREbxuMNIfCyrp:-LkLbmiREbxuMNIfCyrq:b-x9jj9r) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/__tests__/util/user.test.ts#L4)):*
> ```XML
> 
> describe("User is admin", () => {
>   it("should retur true is user has admin role", () => {
> ```

"should return true if the user has the admin role"
___
*[src/__tests__/util/user.test.ts, line 8 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLbOUN0Ad2s-7XkR77:-LkLbOUN0Ad2s-7XkR78:b8sxyiu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/__tests__/util/user.test.ts#L8)):*
> ```XML
>   });
> 
>   it("should return false if user has roles other then admin", () => {
> ```

Maybe rather say "... has only roles other than...".
___
*[src/__tests__/util/user.test.ts, line 8 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLbb467dccNQtxdyBT:-LkLbb467dccNQtxdyBU:b-zb835i) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/__tests__/util/user.test.ts#L8)):*
> ```XML
>   });
> 
>   it("should return false if user has roles other then admin", () => {
> ```

<Pedantic>
   if user => if the user
</Pedantic>
___
*[src/__tests__/util/user.test.ts, line 12 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLbkBg8szD2JehoXRS:-LkLbkBg8szD2JehoXRT:b-zb835i) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/__tests__/util/user.test.ts#L12)):*
> ```XML
>   });
> 
>   it("should return false if user has no roles", () => {
> ```

<Pedantic>
   if user => if the user
</Pedantic>
___
*[src/util/user.ts, line 6 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLZhsB5CwLmrL0RfaM:-LkLZhsCBAmmMtUaFXzZ:b-9n6c36) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/util/user.ts#L6)):*
> ```XML
>  * @param user user information
>  */
> const isAdmin = (user: any) =>
> ```

There should be a User type, and roles should have their own type as well.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 230 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkNkyOB18fKp64ef4Z1:-LkU3szF7n4IReIyWSin:b-8b11j9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/createServer.ts#L230)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should check for ownership as well. This probably should be done with a utility function which at the moment would just return false.
</blockquote></details>

Added
___
*[src/createServer.ts, line 232 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLa8Da2E7zPa0fnUJG:-LkU3edB7zDW4Ae4Ak9E:bb6un1j) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/createServer.ts#L232)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is a small problem: If there is no user, the file download would be possible. I'd suggest to drop the "req.user &&" and handle the case of a  missing req.user in isAdmin.
</blockquote></details>

Done
___
*[src/createServer.ts, line 360 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLb9Ta1SADiLMDivWq:-LkU3gt4BVuDz-jtDhao:bd0xup7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f918c71d6ab423d93a31717e8e1391d979e45814/src/createServer.ts#L360)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

dataRequest probably should have its own type.
</blockquote></details>

Currently using prisma, and with mysql some of the data type will change, I will include it on the prisma to mysql pull request
___
*[src/__tests__/util/user.test.ts, line 4 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLbmiREbxuMNIfCyrp:-LkU3vyZC-tQkV-h-kHu:b-886gsx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/__tests__/util/user.test.ts#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"should return true if the user has the admin role"
</blockquote></details>

Fixed
___
*[src/__tests__/util/user.test.ts, line 8 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLbOUN0Ad2s-7XkR77:-LkU4-3j0W2hztbkfYPa:b-886gsx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/__tests__/util/user.test.ts#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe rather say "... has only roles other than...".
</blockquote></details>

Fixed
___
*[src/__tests__/util/user.test.ts, line 8 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLbb467dccNQtxdyBT:-LkU4095DbMXFkY2C44I:b-886gsx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/__tests__/util/user.test.ts#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

<Pedantic>
   if user => if the user
</Pedantic>
</blockquote></details>

Fixed
___
*[src/__tests__/util/user.test.ts, line 12 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLbkBg8szD2JehoXRS:-LkU45Mp79Y1tJyXO8Iu:b-886gsx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/__tests__/util/user.test.ts#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

<Pedantic>
   if user => if the user
</Pedantic>
</blockquote></details>

Fixed
___
*[src/util/user.ts, line 6 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkLZhsB5CwLmrL0RfaM:-LkU4HQy29pMhzCaBJn5:bd0xup7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/util/user.ts#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be a User type, and roles should have their own type as well.
</blockquote></details>

Currently using prisma, and with mysql some of the data type will change, I will include it on the prisma to mysql pull request

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

___
*[src/createServer.ts, line 233 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkURIkdD2iQHsbPsAWT:-LkURIkdD2iQHsbPsAWU:b-v7rh0v) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/createServer.ts#L233)):*
> ```XML
>     // Check that the user may download FITS files because they are an administrator.
>     // If the user is not an ADMIN, forbid the user from downloading.
>     if (publicFrom > Date.now() || (req.user && !isAdmin(req.user))) {
> ```

ownsDataFile must take the file id as an argument as well.

From what I can see, the condition will always give an error if the file isn't public yet. I think the correct condition would be:

if (publicFrom > Date.now() && !ownsDataFile(req.user, dataFileId) && !isAdmin(req.user)) {

The comment could be simplified to

// Check whether the data file is public or the user may access it because they own the data or are an administrator. 
___
*[src/createServer.ts, line 437 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkUT2Se7dz54k_NcW3Q:-LkUT2Se7dz54k_NcW3R:bp4nzaq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/2b478a194530dd14590af4c9fa87849daa41820d/src/createServer.ts#L437)):*
> ```XML
>   // because they own the request or because they are an administrator.
>   const mayDownload =
>     (dataRequest as any).user.id === req.user.id || isAdmin(req.user);
> ```

Maybe use a helper function ownsDataRequest?

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 233 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkURIkdD2iQHsbPsAWT:-LkXmM9j2F3qxIhZhccq:b-wwtud7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c9740f7620a47f8187e86b0f01c7a1cf3f4708de/src/createServer.ts#L233)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ownsDataFile must take the file id as an argument as well.

From what I can see, the condition will always give an error if the file isn't public yet. I think the correct condition would be:

if (publicFrom > Date.now() && !ownsDataFile(req.user, dataFileId) && !isAdmin(req.user)) {

The comment could be simplified to

// Check whether the data file is public or the user may access it because they own the data or are an administrator. 
</blockquote></details>

Updated accordingly
___
*[src/createServer.ts, line 437 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkUT2Se7dz54k_NcW3Q:-LkXkjK84f-yJyQ2vaCL:b-8b11j9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/2b478a194530dd14590af4c9fa87849daa41820d/src/createServer.ts#L437)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe use a helper function ownsDataRequest?
</blockquote></details>

Added

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz)

___
*[src/createServer.ts, line 228 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkXz85E7SteLt8NMPBB:-LkXz85F-z7tOe4jVsvj:bc4v26m) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/createServer.ts#L228)):*
> ```XML
>     }
> 
>     const { id, path: previewPath, publicFrom } = results[0];
> ```

But your query does not return an id...? Also, maybe use something like "filePath" rather than "previewPath".
___
*[src/createServer.ts, line 441 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkY--6MDzeMcjnBRbdr:-LkY--6MDzeMcjnBRbds:b-iu5osx) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/createServer.ts#L441)):*
> ```XML
>     ownsDataRequest(dataRequest, req.user) || isAdmin(req.user);
> 
>   // If the user does not own the data request to download,
> ```

One could argue that this comment repeats the previous one... ;-)
___
*[src/__tests__/util/user.test.ts, line 4 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkY-GgQ96_0xWFAblDy:-LkY-GgQ96_0xWFAblDz:bn76tdf) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/__tests__/util/user.test.ts#L4)):*
> ```XML
> 
> describe("User is admin", () => {
>   const user: IUser = {
> ```

Is there a need for this global variable?
___
*[src/util/user.ts, line 20 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkY0Zbk5HXFvmXO_Am3:-LkY0Zbk5HXFvmXO_Am4:b433ggm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/util/user.ts#L20)):*
> ```XML
>  * @param fileId data file id
>  */
> const ownsDataFile = (user: IUser | undefined, fileId: number) => false;
> ```

If we use a UUID as id this presumably should be a string.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 228 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkXz85E7SteLt8NMPBB:-LkY4qnD9eqmmuodeY0P:b-2bohwa) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/createServer.ts#L228)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But your query does not return an id...? Also, maybe use something like "filePath" rather than "previewPath".
</blockquote></details>

id is not supposed to be there, removed.
Changed to filePath
___
*[src/createServer.ts, line 441 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkY--6MDzeMcjnBRbdr:-LkY6IzM5Li36kzG3f3R:b-80bnvp) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/createServer.ts#L441)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

One could argue that this comment repeats the previous one... ;-)
</blockquote></details>

True.
___
*[src/__tests__/util/user.test.ts, line 4 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkY-GgQ96_0xWFAblDy:-LkY5igs9kbeg9CjPtas:b-hd7h8n) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/__tests__/util/user.test.ts#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there a need for this global variable?
</blockquote></details>

Unless it is unnecessary but it is also used in the user.test.ts file.
If we are to enforce type, in the future, anywhere where user object is used, we might need it. But can argue otherwise :-)
___
*[src/util/user.ts, line 20 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkY0Zbk5HXFvmXO_Am3:-LkY5csQCUNmUOh4eD51:b-ghqr00) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/util/user.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If we use a UUID as id this presumably should be a string.
</blockquote></details>

yes yes yes

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: all files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

___
*[src/__tests__/util/user.test.ts, line 4 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkY-GgQ96_0xWFAblDy:-LkY99FX2QAB9rZoCj5e:b-hrcdel) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/__tests__/util/user.test.ts#L4)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Unless it is unnecessary but it is also used in the user.test.ts file.
If we are to enforce type, in the future, anywhere where user object is used, we might need it. But can argue otherwise :-)
</blockquote></details>

I think you misunderstood me. I'll explain in person what I meant - sorry for being clear as mud.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/__tests__/util/user.test.ts, line 4 at r6](https://reviewable.io/reviews/saltastroops/data-archive-backend/24#-LkY-GgQ96_0xWFAblDy:-LkZOfLdCefnZburp-hV:b9nkumd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/b6e3d90082bd900a67308c3af62271e88f1997a4/src/__tests__/util/user.test.ts#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think you misunderstood me. I'll explain in person what I meant - sorry for being clear as mud.
</blockquote></details>

create user helper function for testing should be in place now

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/24)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
