### PR TITLE
Fixed data request file name

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

___
*[src/createServer.ts, line 462 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-C9qXT8l2Z7nUIrIYe:-M-C9qXV0i2bEChtE67q:b9bvda6) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/92aa6e08a9c945f223356e5099cbfb4c84bfff02/src/createServer.ts#L462)):*
> ```XML
> 
>   filename =
>     process.env.NODE_ENV === "test"
> ```

I don't think you should define a name for the tests. Instead you should modify the tests.
___
*[src/createServer.ts, line 464 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-C6fSu2HGuVTd5iqte:-M-C6fSu2HGuVTd5iqtf:b-f3itr3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/92aa6e08a9c945f223356e5099cbfb4c84bfff02/src/createServer.ts#L464)):*
> ```XML
>     process.env.NODE_ENV === "test"
>       ? "data-file-request.zip"
>       : `${moment().format("Y-MM-DD_HH:mm:ss")}.zip`;
> ```

You commented that the ':' is replaced with '_'. I suspect that's the browser avoiding colons in filenames. But then perhaps we should use a dash rather than a colob for separating hours, minutes and seconds.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 462 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-C9qXT8l2Z7nUIrIYe:-M-DqLty5d73nCmo4QZl:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/92aa6e08a9c945f223356e5099cbfb4c84bfff02/src/createServer.ts#L462)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you should define a name for the tests. Instead you should modify the tests.
</blockquote></details>

Done.
___
*[src/createServer.ts, line 464 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-C6fSu2HGuVTd5iqte:-M-DqM_F4LWlaSji-UaN:b48px8h) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/92aa6e08a9c945f223356e5099cbfb4c84bfff02/src/createServer.ts#L464)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You commented that the ':' is replaced with '_'. I suspect that's the browser avoiding colons in filenames. But then perhaps we should use a dash rather than a colob for separating hours, minutes and seconds.
</blockquote></details>

Thought so, thank you.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/createServer.ts, line 464 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-C6fSu2HGuVTd5iqte:-M-EBkh-5LWKBPEWr0xF:botcxek) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/92aa6e08a9c945f223356e5099cbfb4c84bfff02/src/createServer.ts#L464)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Thought so, thank you.
</blockquote></details>

My suggestion stands: replace the colons with dashes, or an empty string, or remove the whole time string.
___
*[src/__tests__/requestDataDownload.test.ts, line 76 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-ECCfJ6oOBhhDA3Kq0:-M-ECCfJ6oOBhhDA3Kq1:bftv1ji) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a14a797cd925ea491b4286d42bcc483c92da8f38/src/__tests__/requestDataDownload.test.ts#L76)):*
> ```XML
>     // Expect the disposition to use "data-file-request.zip" as filename
>     expect(response.header["content-disposition"]).toContain(
>       `${moment().format("Y-MM-DD_HH:mm:ss")}.zip`
> ```

That is a bit dangerous, because there is no guarantee that the time will be the same as that for createServer. So you should just test the format is correct. (The alternative would be to use a service, which could then be faked in the tests.)
___
*[src/__tests__/requestDataDownload.test.ts, line 123 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-ECmZR7n9X1h_uqSd9:-M-ECmZR7n9X1h_uqSdA:b-otilcs) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a14a797cd925ea491b4286d42bcc483c92da8f38/src/__tests__/requestDataDownload.test.ts#L123)):*
> ```XML
>     // Expect the disposition to use "data-file-request.zip" as filename
>     expect(response.header["content-disposition"]).toContain(
>       `${moment().format("Y-MM-DD_HH:mm:ss")}.zip`
> ```

See comment above.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 464 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-C6fSu2HGuVTd5iqte:-M-ELXsH0gZvM821VPfO:bwj599p) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/92aa6e08a9c945f223356e5099cbfb4c84bfff02/src/createServer.ts#L464)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

My suggestion stands: replace the colons with dashes, or an empty string, or remove the whole time string.
</blockquote></details>

Removed time part.
___
*[src/__tests__/requestDataDownload.test.ts, line 76 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-ECCfJ6oOBhhDA3Kq0:-M-EL_Qf1vibyE279l6H:bzehyh0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a14a797cd925ea491b4286d42bcc483c92da8f38/src/__tests__/requestDataDownload.test.ts#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That is a bit dangerous, because there is no guarantee that the time will be the same as that for createServer. So you should just test the format is correct. (The alternative would be to use a service, which could then be faked in the tests.)
</blockquote></details>

Fixed to match correct date format
___
*[src/__tests__/requestDataDownload.test.ts, line 123 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-ECmZR7n9X1h_uqSd9:-M-ELfj60wGe5lxYEKLl:bc5kl05) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a14a797cd925ea491b4286d42bcc483c92da8f38/src/__tests__/requestDataDownload.test.ts#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Resolved as well.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/__tests__/requestDataDownload.test.ts, line 123 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-ECmZR7n9X1h_uqSd9:-M-EMuGQ2LBAX-mSrjub:b-otilcs) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a14a797cd925ea491b4286d42bcc483c92da8f38/src/__tests__/requestDataDownload.test.ts#L123)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Resolved as well.
</blockquote></details>

See comment above.
___
*[src/__tests__/requestDataDownload.test.ts, line 76 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-EMPpdCYA0nq9kLuRg:-M-EMPpdCYA0nq9kLuRh:b7x991n) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7042fcce05349d084144b801f3f697629efb55e9/src/__tests__/requestDataDownload.test.ts#L76)):*
> ```XML
>     // Expect the disposition to use the correct format "Y-MM-DD.zip" as filename
>     expect(
>       moment(response.header["content-disposition"], "Y-MM-DD")
> ```

You are just testing that you get a non-null result, and I wonder whether will just be a moment object with an invalid date. I think you should test against a regular expression.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/__tests__/requestDataDownload.test.ts, line 123 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-ECmZR7n9X1h_uqSd9:-M-ETNQp6syAy6DAh6ZR:b4z38xl) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a14a797cd925ea491b4286d42bcc483c92da8f38/src/__tests__/requestDataDownload.test.ts#L123)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment above.
</blockquote></details>

Resolved as well
___
*[src/__tests__/requestDataDownload.test.ts, line 76 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-EMPpdCYA0nq9kLuRg:-M-ETKNQAsNP9h11liwX:b-ebl2y0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/7042fcce05349d084144b801f3f697629efb55e9/src/__tests__/requestDataDownload.test.ts#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are just testing that you get a non-null result, and I wonder whether will just be a moment object with an invalid date. I think you should test against a regular expression.
</blockquote></details>

Used regulat expression

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: all files reviewed, 3 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/createServer.ts, line 461 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-Eapqe8nAuNJgIj0-1:-M-Eapqe8nAuNJgIj0-2:b1kklrq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/59fcc8ff52a038100d530c891ebacd96f7979441/src/createServer.ts#L461)):*
> ```XML
>   }
> 
>   filename = `${moment().format("Y-MM-DD")}.zip`;
> ```

Sorry, I missed that earlier: Shouldn't there be a "DataRequest-" in the name? And irt should be in the filename of the file saved to (backend) disk as well.
___
*[src/__tests__/requestDataDownload.test.ts, line 32 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-EaMV_CZTppluyCRJq:-M-EaMV_CZTppluyCRJr:b-cjo3x7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/59fcc8ff52a038100d530c891ebacd96f7979441/src/__tests__/requestDataDownload.test.ts#L32)):*
> ```XML
> function matchDateFormatFilename(date: string) {
>   return !!date.match(
>     /([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])\.(zip))/g
> ```

As we don't check for valid dates, it's probably sufficient to check againat

/^DataRequest-\d{4}-\d{2}-\d{2}\.zip$

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/__tests__/requestDataDownload.test.ts, line 31 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-EjBDo9C157uXWmNQh:-M-EjBDo9C157uXWmNQi:b54xjf2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9338f5c13b393d82857be4d4a0a1200432bb85e4/src/__tests__/requestDataDownload.test.ts#L31)):*
> ```XML
> // A helper function to check the correct data request filename format.
> function matchDateFormatFilename(date: string) {
>   return !!date.match(/DataRequest-\d{4}-\d{2}-\d{2}.zip/g);
> ```

Why the g flag?

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 461 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-Eapqe8nAuNJgIj0-1:-M-Ek3Ow8yipgvv949iJ:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/59fcc8ff52a038100d530c891ebacd96f7979441/src/createServer.ts#L461)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry, I missed that earlier: Shouldn't there be a "DataRequest-" in the name? And irt should be in the filename of the file saved to (backend) disk as well.
</blockquote></details>

Done.
___
*[src/__tests__/requestDataDownload.test.ts, line 32 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-EaMV_CZTppluyCRJq:-M-Ek4oODUoiQP3xdC-E:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/59fcc8ff52a038100d530c891ebacd96f7979441/src/__tests__/requestDataDownload.test.ts#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

As we don't check for valid dates, it's probably sufficient to check againat

/^DataRequest-\d{4}-\d{2}-\d{2}\.zip$
</blockquote></details>

Done.
___
*[src/__tests__/requestDataDownload.test.ts, line 31 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/85#-M-EjBDo9C157uXWmNQh:-M-EjrwD51TYV41xkhgo:b9sfxfc) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9338f5c13b393d82857be4d4a0a1200432bb85e4/src/__tests__/requestDataDownload.test.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the g flag?
</blockquote></details>

Umm, yes, we do not need it.
Removed.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/85)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
