### PR TITLE
check if user data was taken while was a member

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/155)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/155)* status: all files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

___
*[src/util/user.ts, line 646 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/155#-MAk6au93ocjvsqNLln8:-MAk6au93ocjvsqNLln9:b-hwk71d) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/34a4c84307d9bf0ee7abed5b249ad282c0f233df/src/util/user.ts#L646)):*
> ```XML
> JOIN admin.institution_membership im ON pi.institution_user_id = im.institution_user_id
> JOIN observations.institution i ON p2.institution_id = i.institution_id
> WHERE pi.institution_user_id=$1 AND i.abbreviated_name=$2 AND a.artifact_id = ANY($3) AND obt.night BETWEEN (im.membership_start AND im.membership_end)
> ```

No. This would mean that users can't access their own data after their institution has left SALT.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/155)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/user.ts, line 646 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/155#-MAk6au93ocjvsqNLln8:-MAkAX0jECxLbPECPe3j:b89uhz) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/34a4c84307d9bf0ee7abed5b249ad282c0f233df/src/util/user.ts#L646)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No. This would mean that users can't access their own data after their institution has left SALT.
</blockquote></details>

Aaah, the issue just made realize that and thanks for the explanation

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/155)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/155)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
