### PR TITLE
Store a relative data request path instead of the full path

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/92)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/92)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/createServer.ts, line 453 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-VH9g0Bld1-DWJfdfh:-M-VH9g17JmvsNHcNYCQ:b-xwkple) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9041cb61c2c31a5decea5d3601f752cff81e7a88/src/createServer.ts#L453)):*
> ```XML
> 
>   // Get the download URI
>   const uri = dataRequest.path;
> ```

"uri" might not be the best name, as the value isn't a valid address really. Something like "relativePath" or "dataRequestPath" might better.

Also, I'm not convinced "dataRequest" is required in these local variable names.
___
*[src/createServer.ts, line 462 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-VHwEK7Gl8EGD4zBpj:-M-VHwEK7Gl8EGD4zBpk:bgjhowd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9041cb61c2c31a5decea5d3601f752cff81e7a88/src/createServer.ts#L462)):*
> ```XML
> 
>   // Get the data request base path if exist
>   const dataRequestBasePath = process.env.DATA_REQUEST_BASE_DIR || "";
> ```

I think it might be safer to raise an error rather than "guessing" a default value. (Although it is a good guess!)
___
*[src/util/zipDataRequest.ts, line 7 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-VIkONAZT2pYWXj74i:-M-VIkONAZT2pYWXj74j:b-8j6z5r) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9041cb61c2c31a5decea5d3601f752cff81e7a88/src/util/zipDataRequest.ts#L7)):*
> ```XML
> const successfullyZipDataRequest = async (dataRequestId: string) => {
>   // update data request with success status and download path
>   const path = `/${dataRequestId.toString()}.zip`;
> ```

I don't think the path should start with "/" - it's a relative path after all.
___
*[src/util/zipDataRequest.ts, line 39 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-VJ8M4BZoSW2sutAGW:-M-VJ8M4BZoSW2sutAGX:b2xm90r) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9041cb61c2c31a5decea5d3601f752cff81e7a88/src/util/zipDataRequest.ts#L39)):*
> ```XML
> 
>   // // delete file created by fs
>   fs.unlink(`/${dataRequestId.toString()}.zip`, err => {
> ```

Aren't you missing the base directory here?

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/92)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/92)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 453 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-VH9g0Bld1-DWJfdfh:-M-j1x_i0MwQOTaOkKJm:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9041cb61c2c31a5decea5d3601f752cff81e7a88/src/createServer.ts#L453)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"uri" might not be the best name, as the value isn't a valid address really. Something like "relativePath" or "dataRequestPath" might better.

Also, I'm not convinced "dataRequest" is required in these local variable names.
</blockquote></details>

Done.
___
*[src/createServer.ts, line 462 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-VHwEK7Gl8EGD4zBpj:-M-j1ymOEnQR0ijvpvzT:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9041cb61c2c31a5decea5d3601f752cff81e7a88/src/createServer.ts#L462)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think it might be safer to raise an error rather than "guessing" a default value. (Although it is a good guess!)
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 7 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-VIkONAZT2pYWXj74i:-M-j20b0E9jmKuqI7v5n:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9041cb61c2c31a5decea5d3601f752cff81e7a88/src/util/zipDataRequest.ts#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the path should start with "/" - it's a relative path after all.
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 39 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-VJ8M4BZoSW2sutAGW:-M-j227sAWzaF6tNHJls:b29erq2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9041cb61c2c31a5decea5d3601f752cff81e7a88/src/util/zipDataRequest.ts#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't you missing the base directory here?
</blockquote></details>

Thank you for that

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/92)* status: all files reviewed, 3 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/createServer.ts, line 416 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-jQeea6OFcBoqquLlz:-M-jQeea6OFcBoqquLm-:b-4gkca7) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/08e995cc3967e2ed91cfed5c50a62076b5f77dba/src/createServer.ts#L416)):*
> ```XML
>   if (!process.env.DATA_REQUEST_BASE_DIR) {
>     res.status(500).send({
>       message: "A base directory for the data request is not defined.",
> ```

How about including the name of the env variable in the error message? :)
___
*[src/__tests__/requestDataDownload.test.ts, line 57 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-jR6cP7hxXBODy64iI:-M-jR6cP7hxXBODy64iJ:b-810cvn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/08e995cc3967e2ed91cfed5c50a62076b5f77dba/src/__tests__/requestDataDownload.test.ts#L57)):*
> ```XML
>         rows: [
>           {
>             path: "/src/__tests__/data/data-file-request.zip",
> ```

Are the relative paths stored with a leading slash in the DB? (Which wouldn't be ideal...)

But looking at the code, they probably aren't. But then the test paths shouldn't have a leading slash either.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/92)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[src/createServer.ts, line 416 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-jQeea6OFcBoqquLlz:-M-jY6Fk2acHAGo7Iibf:bo174e4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/08e995cc3967e2ed91cfed5c50a62076b5f77dba/src/createServer.ts#L416)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about including the name of the env variable in the error message? :)
</blockquote></details>

Don't know if it makes sense the way I put it.
___
*[src/__tests__/requestDataDownload.test.ts, line 57 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-jR6cP7hxXBODy64iI:-M-jYE3e7OcQtERLPsNr:b8338qp) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/08e995cc3967e2ed91cfed5c50a62076b5f77dba/src/__tests__/requestDataDownload.test.ts#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Are the relative paths stored with a leading slash in the DB? (Which wouldn't be ideal...)

But looking at the code, they probably aren't. But then the test paths shouldn't have a leading slash either.
</blockquote></details>

Yep, we no longer store with the preceding slash.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/92)* status: all files reviewed, 1 unresolved discussion (waiting on @chynamyerz)

___
*[src/createServer.ts, line 416 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/92#-M-jQeea6OFcBoqquLlz:-M-jfymKAZYkbhtu8pKT:burdfzh) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/08e995cc3967e2ed91cfed5c50a62076b5f77dba/src/createServer.ts#L416)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Don't know if it makes sense the way I put it.
</blockquote></details>

The environment variable DATA_REQUEST_BASE_DIR for the data request base directory has not been set.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/92)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
