### PR TITLE
Added update user info feature.

### PR DESCRIPTION
**Pull request by chynamyerz**
Only tested successful update, please confirm if on the right direction. 
Busy with other tests.

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/10)

### CODE REVIEW

**Review by hettlage — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/10)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @hettlage)

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/10)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

___
*[src/resolvers/Mutation.ts, line 173 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/10#-Lc2HJYN9WN0Dxl5zN52:-Lc2HJYN9WN0Dxl5zN53:bewmz9e) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9c19cf4f1f8682b79c17c00960f012ad8429d43f/src/resolvers/Mutation.ts#L173)):*
> ```XML
>       }
> 
>       // Check if there already exists a user with the submitted username.
> ```

This fails if the user submits their own existing username, I think.
___
*[src/resolvers/Mutation.ts, line 200 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/10#-Lc2H0P81FVsI34GPEc3:-Lc2H0P81FVsI34GPEc4:b-vd0jbi) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/84b46903e70ffebc306028f80dff76089baacd61/src/resolvers/Mutation.ts#L200)):*
> ```XML
>       args.email = args.email.toLowerCase();
> 
>       // Check if there already exists a user with the submitted email address
> ```

This fails if the user submits their own existing email address, I think.

**Review by hettlage — DISMISSED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Eb-Zeero — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/10)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/schema.graphql, line 65 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/10#-Lc6v4__3MLunuGNKH6f:-Lc6v4__3MLunuGNKH6g:bn13njy) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/722da6590b306ec0bba1da3b205c5a0aa4b3d2ae/src/schema.graphql#L65)):*
> ```GraphQL
>     Unique user ID
>     """
>     id: ID
> ```

is is provided by the context .
I think we should only input args that need to be updated. unless admins can update someone else as well
___
*[src/schema.graphql, line 79 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/10#-Lc6uLff46pt3uk5UNhG:-Lc6uLff46pt3uk5UNhH:b-4euufj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/722da6590b306ec0bba1da3b205c5a0aa4b3d2ae/src/schema.graphql#L79)):*
> ```GraphQL
>     """
>     Username, which must not contain upper case letters.
>     """
> ```

do we also have to update the username if so then wee need username in args else no.

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by chynamyerz — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r3, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 3 files at r3, 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
