### PR TITLE
Search querying

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 6 of 14 files at r1, 3 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: 9 of 18 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/observationsQuery.ts, line 12 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/20#-LjLS7g4DvtQ0pI6UHZz:-LjLS7g51bgJMPydwHzc:bpr55ze) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/93d1be2326159c1a02986d0fe60aaab0373f5e6c/src/util/observationsQuery.ts#L12)):*
> ```XML
>  */
> 
> import { prune } from "../../../frontend/src/util/query/whereCondition";
> ```

Isn't prune on the front end hence outside of this project scope

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, 3 of 9 files at r2, 4 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: 13 of 19 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: 13 of 18 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/connection.ts, line 1 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/20#-LjM0NfX3xP9OfG0Ie3H:-LjM0NfX3xP9OfG0Ie3I:b-7okl7e) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c78c0d21b8b14a9c3824221b6b34bae6cefd741c/src/connection.ts#L1)):*
> ```XML
> import mysql from "mysql";
> ```

same as below connection
___
*[src/db/connection.ts, line 1 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/20#-LjM0Xxa54v4gQsUM0MF:-LjM0Xxa54v4gQsUM0MG:bnj7hl0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c78c0d21b8b14a9c3824221b6b34bae6cefd741c/src/db/connection.ts#L1)):*
> ```XML
> import mysql from "mysql";
> ```

same as above
___
*[src/db/connection.ts, line 15 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/20#-LjM01p2Bb5D-Q6BWBf6:-LjM01p2Bb5D-Q6BWBf7:b-gpyre2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c78c0d21b8b14a9c3824221b6b34bae6cefd741c/src/db/connection.ts#L15)):*
> ```XML
> // It is a good practice to use a pool of connections
> // for database connection management purposes
> const dbConnection = mysql.createPool(config);
> ```

we will be having more connections in the future I think it will be good to pass in config as you connect

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: 13 of 18 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/util/observationsQuery.ts, line 12 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/20#-LjLS7g4DvtQ0pI6UHZz:-LjMOKRKDIngsuSs6vyo:b6r7f9h) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/93d1be2326159c1a02986d0fe60aaab0373f5e6c/src/util/observationsQuery.ts#L12)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Isn't prune on the front end hence outside of this project scope
</blockquote></details>

Indeed. That shouldn't have been here. Thanks for catching this!

**Review by Eb-Zeero — COMMENTED** [review]
> Reviewed 2 of 8 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: 16 of 18 files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — COMMENTED** [review]
> Reviewed 4 of 14 files at r1, 2 of 9 files at r2, 4 of 8 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Eb-Zeero — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — COMMENTED** [review]
> Reviewed 3 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/20)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
