### PR TITLE
Discard any changes in the server and exit when git pul fails via git…

### PR DESCRIPTION
**Pull request by chynamyerz**
…Hub actions

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/131)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/131)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

___
*[.github/workflows/development.yml, line 82 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/131#-M52e6l29iseVAs9LSc-:-M52e6l361_Jvq36nIDL:b-exxexj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/02fe1179140f6030de8d95ac4af7dc4db2faf8f0/.github/workflows/development.yml#L82)):*
> ```YAML
>               set -eu
>               cd /home/ssda/data-archive-backend &&
>               git checkout development &&
> ```

I suspect this might fail if there are changes, at least if you switched the branch?
___
*[.github/workflows/master.yml, line 82 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/131#-M52eNkK4PZPxgSLpxk1:-M52eNkK4PZPxgSLpxk2:b-exxexj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/02fe1179140f6030de8d95ac4af7dc4db2faf8f0/.github/workflows/master.yml#L82)):*
> ```YAML
>               set -eu
>               cd /home/ssda/data-archive-backend &&
>               git checkout master &&
> ```

I suspect this might fail if there are changes, at least if you switched the branch?

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/131)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[.github/workflows/development.yml, line 82 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/131#-M52e6l29iseVAs9LSc-:-M52ezyK4sF39trNnkM-:bheqc5h) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/02fe1179140f6030de8d95ac4af7dc4db2faf8f0/.github/workflows/development.yml#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I suspect this might fail if there are changes, at least if you switched the branch?
</blockquote></details>

I tested it, it works fine:

Already on 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
Updating 263cd4d..8a7f3a1
error: Your local changes to the following files would be overwritten by merge:
        src/resolvers/Query.ts
Please commit your changes or stash them before you merge.
Aborting
___
*[.github/workflows/master.yml, line 82 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/131#-M52eNkK4PZPxgSLpxk1:-M52fSMe2ozjhgiKuqYj:b-mu5b73) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/02fe1179140f6030de8d95ac4af7dc4db2faf8f0/.github/workflows/master.yml#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I suspect this might fail if there are changes, at least if you switched the branch?
</blockquote></details>

Refer to above.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/131)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[.github/workflows/development.yml, line 82 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/131#-M52e6l29iseVAs9LSc-:-M52j3uMBtamitmeC4qs:brzyxk0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/02fe1179140f6030de8d95ac4af7dc4db2faf8f0/.github/workflows/development.yml#L82)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

I tested it, it works fine:

Already on 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
Updating 263cd4d..8a7f3a1
error: Your local changes to the following files would be overwritten by merge:
        src/resolvers/Query.ts
Please commit your changes or stash them before you merge.
Aborting
</blockquote></details>

Order in commands changed
___
*[.github/workflows/master.yml, line 82 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/131#-M52eNkK4PZPxgSLpxk1:-M52j7Zq7WcCfMuFzTxr:brzyxk0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/02fe1179140f6030de8d95ac4af7dc4db2faf8f0/.github/workflows/master.yml#L82)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Refer to above.
</blockquote></details>

Order in commands changed

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/131)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
