### PR TITLE
Requested calibrations schema

### LINKED ISSUE #98: Data request schema updates
Rename DataRequestFile to DataRequestArtifact

Add two enums, CalibrationLevel and CalibrationType

In the DataRequest type:

- Rename dataFiles to artifacts
- Add a field calibrationLevels
- Add a field calibrationTypes

### LINKED ISSUE #100: Make comments in GraphQL schema consistent
Make comments in schema.graphql consistent (i.e. use """ instead of #).

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/schema.graphql, line 191 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M-iuBYZ-KBoApB5ggim:-M-iuBY_5CRUk4OOf7pp:bixo7nl) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/70e418500ec41f6a0247a9c9b92867f9975673ce/src/schema.graphql#L191)):*
> ```GraphQL
>     Whether to include calibration files along with the requested files.
>     """
>     requestedCalibrations: [String!]
> ```

An enum should be used for the calibration type. (And the description needs to be updated.)
___
*[src/resolvers/dataRequest.ts, line 89 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M-iuoJ6CTEMU0tf3ubb:-M-iuoJ6CTEMU0tf3ubc:b-cglmc0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/70e418500ec41f6a0247a9c9b92867f9975673ce/src/resolvers/dataRequest.ts#L89)):*
> ```XML
> };
> 
> async function addCalibrations(
> ```

That needs serious reworking. As agreed, I'll look into it. :)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[src/schema.graphql, line 191 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M-iuBYZ-KBoApB5ggim:-M02_EyL4UrTney3hb1u:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/70e418500ec41f6a0247a9c9b92867f9975673ce/src/schema.graphql#L191)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

An enum should be used for the calibration type. (And the description needs to be updated.)
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 89 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M-iuoJ6CTEMU0tf3ubb:-M02_Hod77FsGoCKhQsE:b-6d25im) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/70e418500ec41f6a0247a9c9b92867f9975673ce/src/resolvers/dataRequest.ts#L89)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That needs serious reworking. As agreed, I'll look into it. :)
</blockquote></details>

please do.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: all files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/schema.graphql, line 191 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M-iuBYZ-KBoApB5ggim:-M03ox734oTVCM4NUfQk:b-kzlk1d) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/70e418500ec41f6a0247a9c9b92867f9975673ce/src/schema.graphql#L191)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe "requestedCalibrationTypes" is better?
___
*[src/schema.graphql, line 189 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M03p66f2Hct74RTgK1D:-M03p66f2Hct74RTgK1E:branu24) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/86c4166088e3e6875d17953f121e77e56cffd9c4/src/schema.graphql#L189)):*
> ```GraphQL
> 
>     """
>     Calibration files to inclunde along with the requested files.
> ```

inclunde ---> include
___
*[src/schema.graphql, line 191 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M03qFvt8bE_43S1C-SX:-M03qFvt8bE_43S1C-SY:b-llwq5e) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/86c4166088e3e6875d17953f121e77e56cffd9c4/src/schema.graphql#L191)):*
> ```GraphQL
>     Calibration files to inclunde along with the requested files.
>     """
>     requestedCalibrations: [ProductType!]
> ```

ProductType might be misleading - CalibrationType would be better. (And only calibration types should be included in the enum.)
___
*[src/schema.graphql, line 358 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M03pIdQDOk7XyFj2jVR:-M03pIdQDOk7XyFj2jVS:b-3v2udi) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/86c4166088e3e6875d17953f121e77e56cffd9c4/src/schema.graphql#L358)):*
> ```GraphQL
> }
> 
> # An enumeration of the product tpyes that are supported.
> ```

Shorter: The 

Comments should be consistent - """...""" rather than # ...

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/schema.graphql, line 191 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M-iuBYZ-KBoApB5ggim:-M0RPYVe4EwmoDTvGQu3:bb7f2mf) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/70e418500ec41f6a0247a9c9b92867f9975673ce/src/schema.graphql#L191)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe "requestedCalibrationTypes" is better?
</blockquote></details>

done
___
*[src/schema.graphql, line 189 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M03p66f2Hct74RTgK1D:-M0RPZvi3ZcfE00DuhoW:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/86c4166088e3e6875d17953f121e77e56cffd9c4/src/schema.graphql#L189)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

inclunde ---> include
</blockquote></details>

Done.
___
*[src/schema.graphql, line 191 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M03qFvt8bE_43S1C-SX:-M0RPXo462azT97DJ0cA:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/86c4166088e3e6875d17953f121e77e56cffd9c4/src/schema.graphql#L191)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

ProductType might be misleading - CalibrationType would be better. (And only calibration types should be included in the enum.)
</blockquote></details>

Done.
___
*[src/schema.graphql, line 358 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M03pIdQDOk7XyFj2jVR:-M0RPBqj9gqA-I1urCK4:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/86c4166088e3e6875d17953f121e77e56cffd9c4/src/schema.graphql#L358)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shorter: The 

Comments should be consistent - """...""" rather than # ...
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: all files reviewed, 6 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/schema.graphql, line 382 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0RRWFB9zFVcZ-heFN1:-M0RRWFB9zFVcZ-heFN2:b-wngnxn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/5c8e8b02d4ec770f01ed0456021bdedb852b84ff/src/schema.graphql#L382)):*
> ```GraphQL
> An enumeration of the product tpyes that are supported.
> """
> enum CalibrationType {
> ```

"product types" is meant to be "calibration types" in the comment I guess?
___
*[src/schema.graphql, line 387 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0RRt_LBK_Zw5k-ffha:-M0RRt_LBK_Zw5k-ffhb:bewq353) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/5c8e8b02d4ec770f01ed0456021bdedb852b84ff/src/schema.graphql#L387)):*
> ```GraphQL
>   DARK
>   FLAT
>   SCIENCE
> ```

Science is not a calibration type... :)

At least spectrophotometric and radial velocity standards will have to be added.

**Review by Eb-Zeero — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-:-M0Smq8nDg2kejapLpfe:bnfp4nl)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[src/schema.graphql, line 382 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0RRWFB9zFVcZ-heFN1:-M0Slj1h-6pbgFvolc6T:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/5c8e8b02d4ec770f01ed0456021bdedb852b84ff/src/schema.graphql#L382)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"product types" is meant to be "calibration types" in the comment I guess?
</blockquote></details>

Done.
___
*[src/schema.graphql, line 387 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0RRt_LBK_Zw5k-ffha:-M0SmlaVEbBeVn6_UIpy:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/5c8e8b02d4ec770f01ed0456021bdedb852b84ff/src/schema.graphql#L387)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Science is not a calibration type... :)

At least spectrophotometric and radial velocity standards will have to be added.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/schema.graphql, line 382 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0RRWFB9zFVcZ-heFN1:-M0U3ff89mVO2gDNHdxE:b-2fvwba) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/5c8e8b02d4ec770f01ed0456021bdedb852b84ff/src/schema.graphql#L382)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, not done... :)
___
*[src/schema.graphql, line 188 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0SzgQ1597KskGqiriV:-M0SzgQ1597KskGqiriW:b97ehj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L188)):*
> ```GraphQL
>     Requested data files.
>     """
>     artifacts: [Int!]!
> ```

I'm not convinced this should be renamed.

And the same appliews to any "artifact" in this file.
___
*[src/schema.graphql, line 191 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0SzuMt3XhquLQ6FRTh:-M0SzuMu-qJjZUUa7_Hm:bbqy3bq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L191)):*
> ```GraphQL
> 
>     """
>     the calibration types to include along with the requested files.
> ```

the ---> The
___
*[src/schema.graphql, line 195 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T5fwcC2f2A6Um6Zo0:-M0T5fwcC2f2A6Um6Zo1:bbqy3bq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L195)):*
> ```GraphQL
>     requestedCalibrationsTypes: [CalibrationType!]
>     """
>     the calibration levels to include along with the requested files.
> ```

the ---> The
___
*[src/schema.graphql, line 197 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T6543B2CFxcdZH9NQ:-M0T6543B2CFxcdZH9NR:bnygr6t) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L197)):*
> ```GraphQL
>     the calibration levels to include along with the requested files.
>     """
>     requestedCalibrationsLevels: [CalibrationLevel!]
> ```

Should be [CalibrationLevel!]!
___
*[src/schema.graphql, line 253 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T6M3LDCmcQmtwlKJR:-M0T6M3LDCmcQmtwlKJS:ba9zoaq) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L253)):*
> ```GraphQL
> 
>   """
>   Message is ever the status has one.
> ```

Maybe better: Status message.
___
*[src/schema.graphql, line 348 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T7Az1AseH9Lwp6Zd8:-M0T7Az1AseH9Lwp6Zd9:b-26399r) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L348)):*
> ```GraphQL
> Details about a data request.
> """
> type DataRequest {
> ```

Full stops should be added to the comments.
___
*[src/schema.graphql, line 362 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T7FjbEoezfxW8s-Cc:-M0T7FjbEoezfxW8s-Cd:b9o6s04) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L362)):*
> ```GraphQL
>   uri: String
>   """
>   The date a data request was made
> ```

The date and time when the data request was made.
___
*[src/schema.graphql, line 368 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T6wLvEJm3ef3C77W9:-M0T6wLvEJm3ef3C77WA:bys908f) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L368)):*
> ```GraphQL
>   The requested data files
>   """
>   artifact: [DataRequestArtifact!]!
> ```

Note (irrespective of whether dataFile is renamed to artifact), the field name must be a plural.
___
*[src/schema.graphql, line 193 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0U46XIBbFBA3nJogSj:-M0U46XIBbFBA3nJogSk:b-ezyoxl) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0203d6f396e837402cf5a7050c29291e9a7e13ab/src/schema.graphql#L193)):*
> ```GraphQL
>     the calibration types to include along with the requested files.
>     """
>     requestedCalibrationsTypes: [CalibrationType!]
> ```

requestedCalibrationsTypes ---> requestedCalibrationTypes
___
*[src/schema.graphql, line 197 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0U4HbrEs80KkZ_Rop8:-M0U4HbrEs80KkZ_Rop9:b-sv3x39) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0203d6f396e837402cf5a7050c29291e9a7e13ab/src/schema.graphql#L197)):*
> ```GraphQL
>     the calibration levels to include along with the requested files.
>     """
>     requestedCalibrationsLevels: [CalibrationLevel!]
> ```

requestedCalibrationsLevels ---> requestedCalibrationLevels
___
*[src/schema.graphql, line 445 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0U3_ycDVOA0C62NLjh:-M0U3_ycDVOA0C62NLji:bpl1fgm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0203d6f396e837402cf5a7050c29291e9a7e13ab/src/schema.graphql#L445)):*
> ```GraphQL
> enum CalibrationLevel {
>   RAW
>   REDUSED
> ```

REDUSED ---> REDUCED

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: 2 of 3 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[src/schema.graphql, line 382 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0RRWFB9zFVcZ-heFN1:-M0WLPmgDdnEq85HuX8o:b-8bb6nj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/5c8e8b02d4ec770f01ed0456021bdedb852b84ff/src/schema.graphql#L382)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No, not done... :)
</blockquote></details>

now done
___
*[src/schema.graphql, line 188 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0SzgQ1597KskGqiriV:-M0WOwyUBzy1jOMAPITE:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L188)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced this should be renamed.

And the same appliews to any "artifact" in this file.
</blockquote></details>

Done.
___
*[src/schema.graphql, line 191 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0SzuMt3XhquLQ6FRTh:-M0WLxK81NcT24i7ienD:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L191)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

the ---> The
</blockquote></details>

Done.
___
*[src/schema.graphql, line 195 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T5fwcC2f2A6Um6Zo0:-M0WJwMa6wAwrx6_WNMR:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L195)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

the ---> The
</blockquote></details>

Done.
___
*[src/schema.graphql, line 197 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T6543B2CFxcdZH9NQ:-M0WJxAiEM1lauZCmQgy:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L197)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be [CalibrationLevel!]!
</blockquote></details>

Done.
___
*[src/schema.graphql, line 253 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T6M3LDCmcQmtwlKJR:-M0WKMFW023g2-Oxx0LG:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L253)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better: Status message.
</blockquote></details>

Done.
___
*[src/schema.graphql, line 348 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T7Az1AseH9Lwp6Zd8:-M0WKk6qClIEXIPfqy2h:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L348)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Full stops should be added to the comments.
</blockquote></details>

Done.
___
*[src/schema.graphql, line 362 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T7FjbEoezfxW8s-Cc:-M0WKyMs2MbTBSixIsPO:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L362)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The date and time when the data request was made.
</blockquote></details>

Done.
___
*[src/schema.graphql, line 368 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T6wLvEJm3ef3C77W9:-M0WPIUn8kK3hPBBwD_J:b14bavg) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L368)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Note (irrespective of whether dataFile is renamed to artifact), the field name must be a plural.
</blockquote></details>

It was plural before.
or I am lost with this comment. help please
___
*[src/schema.graphql, line 193 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0U46XIBbFBA3nJogSj:-M0WLy60-BNpUt_PoJnq:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0203d6f396e837402cf5a7050c29291e9a7e13ab/src/schema.graphql#L193)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

requestedCalibrationsTypes ---> requestedCalibrationTypes
</blockquote></details>

Done.
___
*[src/schema.graphql, line 197 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0U4HbrEs80KkZ_Rop8:-M0WK3v0CGwa28FRi4dP:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0203d6f396e837402cf5a7050c29291e9a7e13ab/src/schema.graphql#L197)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

requestedCalibrationsLevels ---> requestedCalibrationLevels
</blockquote></details>

Done.
___
*[src/schema.graphql, line 445 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0U3_ycDVOA0C62NLjh:-M0WLV0y-GNmJqDt7ucO:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/0203d6f396e837402cf5a7050c29291e9a7e13ab/src/schema.graphql#L445)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

REDUSED ---> REDUCED
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/schema.graphql, line 368 at r4](https://reviewable.io/reviews/saltastroops/data-archive-backend/94#-M0T6wLvEJm3ef3C77W9:-M0WuqtW5uVzX3ZvN3UB:bx38rcv) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/88f6a02deef034941059a47162c31de62c869954/src/schema.graphql#L368)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

It was plural before.
or I am lost with this comment. help please
</blockquote></details>

That's odd. I'm pretty sure I saw a singular! Sorry for that.

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/94)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
