### PR TITLE
Save institute member

### LINKED ISSUE #137: Login with  Web Manager account impossible
You cannot login with your Web Manager account. When yiu try to do so, you are told that the username or password is wrong. On the server the following error is raised:

```
(node:12671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:12671) UnhandledPromiseRejectionWarning: error: null value in column "institution_member" violates not-null constraint
 ```

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/138)

### CODE REVIEW

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/138)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/138)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[src/util/authProvider.ts, line 211 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/138#-M6hlbxR-NU_pQzh8I1b:-M6hlbxR-NU_pQzh8I1c:b-tci3jj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a5c1bb7977853dfa6a92ae23a7f401baabc22e6c/src/util/authProvider.ts#L211)):*
> ```XML
>         familyName: user.Surname,
>         givenName: user.FirstName,
>         institutionMember: user.Partner_Code != "OTH",
> ```

!= -> !==

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/138)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[src/util/authProvider.ts, line 211 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/138#-M6hlbxR-NU_pQzh8I1b:-M6hnMxyBWWPwvVUP6k9:b-1jl013) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/a5c1bb7977853dfa6a92ae23a7f401baabc22e6c/src/util/authProvider.ts#L211)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

!= -> !==
</blockquote></details>

Fixed. Thank you!

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/138)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
