### PR TITLE
adding github actions workflow

### PR DESCRIPTION
**Pull request by chynamyerz**
This needs attention, preferable soonest

---
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)* status: 0 of 3 files reviewed, 16 unresolved discussions (waiting on @chynamyerz)

___
*[.github/workflows/development.yml, line 22 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnIB4F8P9iD--O_t8O:-LrnIB4G277en6me7uR1:b-1pr5dn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L22)):*
> ```YAML
>       # To include more versions, you can add them as follows: [8.x, 10.x, 12.x].
>       matrix:
>         node-version: [10.x]
> ```

It might be prudent to include Node 8 as well.
___
*[.github/workflows/development.yml, line 41 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnM_pQ4tWkpXm0qD5P:-LrnM_pQ4tWkpXm0qD5Q:b-n6d6ka) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L41)):*
> ```YAML
>       - run: |
>           yarn install
>           yarn test
> ```

What about linting and formatting?
___
*[.github/workflows/development.yml, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnUrm6CqgSotp16P4f:-LrnUrm6CqgSotp16P4g:b-s8sr8q) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L59)):*
> ```YAML
>         uses: actions/checkout@v1
>       # This step uses the ssh action to setup a ssh server used to ssh into the development server.
>       - name: Ssh server
> ```

Ssh -> ssh
___
*[.github/workflows/development.yml, line 69 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnVD_cBeiSuEniNuzq:-LrnVD_cBeiSuEniNuzr:bjl8yns) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L69)):*
> ```YAML
>         # user, the host username to ssh into
>         # port, the host port to ssh into
>         # command, the command to be executed inside th sshed into host.
> ```

inside th sshed ---> inside the remote host
___
*[.github/workflows/development.yml, line 71 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnSd48334bcjP0fkaT:-LrnSd48334bcjP0fkaU:b-u4vm3m) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L71)):*
> ```YAML
>         # command, the command to be executed inside th sshed into host.
>         with:
>           key: ${{ secrets.SSH_MACHINE_PRIVATE_SSH_KEY }}
> ```

Only the key or the password should  be configured.
___
*[.github/workflows/development.yml, line 77 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnbaPl3HcsFPvDnu0s:-LrnbaPl3HcsFPvDnu0t:bh3i5y2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L77)):*
> ```YAML
>           pass: ${{ secrets.SSH_MACHINE_PASSWORD }}
>           command: |
>             pwd
> ```

A comment such as the following might be useful:

# The ssh action logs into a gateway server, and we still have to connect to the machine on which the data archive is hosted.
___
*[.github/workflows/development.yml, line 78 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnatW4D6nciXpTD2Tq:-LrnatW4D6nciXpTD2Tr:b-y10j1m) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L78)):*
> ```YAML
>           command: |
>             pwd
>             ssh -o StrictHostKeyChecking=no -tt ${{ secrets.TEST_USER}}@${{ secrets.TEST_HOST}} -p ${{ secrets.TEST_PORT}} """
> ```

Maybe DEV rather than TEST?
___
*[.github/workflows/development.yml, line 80 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnVOzeC2WuTcT6_vEF:-LrnVOzeC2WuTcT6_vEG:b-2ljm7l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L80)):*
> ```YAML
>             ssh -o StrictHostKeyChecking=no -tt ${{ secrets.TEST_USER}}@${{ secrets.TEST_HOST}} -p ${{ secrets.TEST_PORT}} """
>               cd /home/ssda/data-archive-backend
>               git checkout gitactions-featuredev-test
> ```

Shouldn't that be git checkout development ?
___
*[.github/workflows/development.yml, line 84 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnTZ6a9xd0w3vyjtoS:-LrnTZ6a9xd0w3vyjtoT:ba8m0ps) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L84)):*
> ```YAML
>               yarn install
>               yarn test
>               yarn restart
> ```

I could find no restart script in packages.json?
___
*[.github/workflows/development.yml, line 87 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnThKE1Ro2J8LK8nXQ:-LrnThKE1Ro2J8LK8nXR:b-e5g9la) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L87)):*
> ```YAML
>               exit
>             """
> #  job3:
> ```

I don't think there should be job3.
___
*[.github/workflows/features.yml, line 24 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnUTR465VjpdaQ8l8G:-LrnUTR50lAF3w6BZU8l:b3i4gbh) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/features.yml#L24)):*
> ```YAML
>       # To include more versions, you can add them as follows: [8.x, 10.x, 12.x].
>       matrix:
>         node-version: [10.x]
> ```

And version 8?
___
*[.github/workflows/features.yml, line 49 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnULGI-LSBgg5EEEjd:-LrnULGI-LSBgg5EEEje:b-2axyhm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/features.yml#L49)):*
> ```YAML
>         shell: bash
> 
> #  job2:
> ```

I guess job2 can be removed?
___
*[.github/workflows/master.yml, line 22 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnU-7zAZd0Fnynzfz8:-LrnU-7zAZd0Fnynzfz9:b3i4gbh) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L22)):*
> ```YAML
>       # To include more versions, you can add them as follows: [8.x, 10.x, 12.x].
>       matrix:
>         node-version: [10.x]
> ```

And version 8?
___
*[.github/workflows/master.yml, line 41 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnU3m39ltsUXiGOdWF:-LrnU3m39ltsUXiGOdWG:b-n6d6ka) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L41)):*
> ```YAML
>       - run: |
>           yarn install
>           yarn test
> ```

What about linting and formatting?
___
*[.github/workflows/master.yml, line 71 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnUaD5A83qYf9NS8PN:-LrnUaD5A83qYf9NS8PO:beoape0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L71)):*
> ```YAML
>         # command, the command to be executed inside th sshed into host.
>         with:
>           key: ${{ secrets.SSH_MACHINE_PRIVATE_SSH_KEY }}
> ```

Only the key or the password should be configured.
___
*[.github/workflows/master.yml, line 77 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrncF0o7cFQliGQI21g:-LrncF0o7cFQliGQI21h:bh3i5y2) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L77)):*
> ```YAML
>           pass: ${{ secrets.SSH_MACHINE_PASSWORD }}
>           command: |
>             pwd
> ```

A comment such as the following might be useful:

# The ssh action logs into a gateway server, and we still have to connect to the machine on which the data archive is hosted.

**Review by hettlage — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)* status: all files reviewed, 16 unresolved discussions (waiting on @chynamyerz)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)* status: 0 of 4 files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[.github/workflows/development.yml, line 22 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnIB4F8P9iD--O_t8O:-LrnpFmz7cwSCBkghq3t:bmsspt3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be prudent to include Node 8 as well.
</blockquote></details>

version 8.x included
___
*[.github/workflows/development.yml, line 41 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnM_pQ4tWkpXm0qD5P:-LrnpL7z0NqpC95QZdyb:b-8b11j9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about linting and formatting?
</blockquote></details>

Added
___
*[.github/workflows/development.yml, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnUrm6CqgSotp16P4f:-LrnpMUOBavBb0ddpp5u:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ssh -> ssh
</blockquote></details>

Done.
___
*[.github/workflows/development.yml, line 69 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnVD_cBeiSuEniNuzq:-LrnpNWR4nO4y2AfwgMF:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

inside th sshed ---> inside the remote host
</blockquote></details>

Done.
___
*[.github/workflows/development.yml, line 71 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnSd48334bcjP0fkaT:-LrnpOgT0Mc35pCSboMP:b3r5hnm) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Only the key or the password should  be configured.
</blockquote></details>

ssh key
___
*[.github/workflows/development.yml, line 77 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnbaPl3HcsFPvDnu0s:-LrnpQVx-USQuurdma_w:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A comment such as the following might be useful:

# The ssh action logs into a gateway server, and we still have to connect to the machine on which the data archive is hosted.
</blockquote></details>

Done.
___
*[.github/workflows/development.yml, line 78 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnatW4D6nciXpTD2Tq:-LrnpSH0ASRbAqvrIqnI:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L78)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe DEV rather than TEST?
</blockquote></details>

Done.
___
*[.github/workflows/development.yml, line 80 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnVOzeC2WuTcT6_vEF:-LrnpUJjCyGgkh6NcWcx:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be git checkout development ?
</blockquote></details>

Done.
___
*[.github/workflows/development.yml, line 84 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnTZ6a9xd0w3vyjtoS:-LrnpV9U6qzF5G_ShVX-:b-8b11j9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L84)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I could find no restart script in packages.json?
</blockquote></details>

Added
___
*[.github/workflows/development.yml, line 87 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnThKE1Ro2J8LK8nXQ:-LrnpX8uCedY4Amj12n_:b8n5h8x) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/development.yml#L87)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think there should be job3.
</blockquote></details>

Yep, we should do pull requests. 
Still looking for a command line for a pull request, any help would be appreciated :-)
___
*[.github/workflows/features.yml, line 24 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnUTR465VjpdaQ8l8G:-Lrnpjhq18WMwPnNUVXX:b-a1irb9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/features.yml#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

And version 8?
</blockquote></details>

Included version 8.x
___
*[.github/workflows/features.yml, line 49 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnULGI-LSBgg5EEEjd:-LrnpnZPD-7cUcQ6rTkX:b2nhswv) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/features.yml#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess job2 can be removed?
</blockquote></details>

Yep
___
*[.github/workflows/master.yml, line 22 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnU-7zAZd0Fnynzfz8:-LrnppIDD56398u9Vn3u:b-db3ap1) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

And version 8?
</blockquote></details>

included version 8.x
___
*[.github/workflows/master.yml, line 41 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnU3m39ltsUXiGOdWF:-LrnptF_2yXLBBEfw12J:b-8b11j9) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What about linting and formatting?
</blockquote></details>

Added
___
*[.github/workflows/master.yml, line 71 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnUaD5A83qYf9NS8PN:-Lrnpuvx24CY7FRvPUa_:b3ssvfp) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Only the key or the password should be configured.
</blockquote></details>

ssk key
___
*[.github/workflows/master.yml, line 77 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrncF0o7cFQliGQI21g:-LrnpwJlAaj1ks64-C8w:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L77)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A comment such as the following might be useful:

# The ssh action logs into a gateway server, and we still have to connect to the machine on which the data archive is hosted.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)* status: all files reviewed, 6 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[.github/workflows/development.yml, line 72 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-Lro3QfZE1iQdUCbZ8JV:-Lro3QfZE1iQdUCbZ8JW:b-jgst6o) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/df4fb2d3ea189453413c9689ae56fa44bd8e22fa/.github/workflows/development.yml#L72)):*
> ```YAML
>         # port, the host port to ssh into
>         # command, the command to be executed inside the remote host.
>         # The ssh action logs into a gateway server,
> ```

Actually that comment was meant for the line with the ssh command.
___
*[.github/workflows/master.yml, line 22 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnU-7zAZd0Fnynzfz8:-Lro42y-6K_FfJQBl2M9:b-dxahz3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L22)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

included version 8.x
</blockquote></details>

You added it in the comment, but not in the actual matrix configuration... :-)
___
*[.github/workflows/master.yml, line 71 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-Lro4fUp76XdCA4OSP0g:-Lro4fUp76XdCA4OSP0h:b-jgst6o) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/df4fb2d3ea189453413c9689ae56fa44bd8e22fa/.github/workflows/master.yml#L71)):*
> ```YAML
>         # command, the command to be executed inside the remote host.
>         # The ssh action logs into a gateway server,
>         # and we still have to connect to the machine on which the data archive is hosted.
> ```

Actually that comment was meant for the line with the ssh command.
___
*[.github/workflows/master.yml, line 83 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-Lro4mFnB2XGbh7mOrMT:-Lro4mFnB2XGbh7mOrMU:bptw1nt) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/df4fb2d3ea189453413c9689ae56fa44bd8e22fa/.github/workflows/master.yml#L83)):*
> ```YAML
>               git pull
>               yarn install
>               yarn format
> ```

I don't think formatting should be applied for the master branch, to avoid surprises in production. (Asking for it was an error. Sorry! It makes sense for the other branches, though.)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[.github/workflows/development.yml, line 72 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-Lro3QfZE1iQdUCbZ8JV:-LrruaOl8CkewCMpIsJM:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/df4fb2d3ea189453413c9689ae56fa44bd8e22fa/.github/workflows/development.yml#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually that comment was meant for the line with the ssh command.
</blockquote></details>

Done.
___
*[.github/workflows/master.yml, line 22 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnU-7zAZd0Fnynzfz8:-LrrubU7EAN93TDzd9ht:biwwgsy) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You added it in the comment, but not in the actual matrix configuration... :-)
</blockquote></details>

oops... 
Done
___
*[.github/workflows/master.yml, line 71 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-Lro4fUp76XdCA4OSP0g:-LrrujpY0cYzpI7UkW8T:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/df4fb2d3ea189453413c9689ae56fa44bd8e22fa/.github/workflows/master.yml#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually that comment was meant for the line with the ssh command.
</blockquote></details>

Done.
___
*[.github/workflows/master.yml, line 83 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-Lro4mFnB2XGbh7mOrMT:-LrrulAjEsczqW3OYDjd:bu8x0ym) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/df4fb2d3ea189453413c9689ae56fa44bd8e22fa/.github/workflows/master.yml#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think formatting should be applied for the master branch, to avoid surprises in production. (Asking for it was an error. Sorry! It makes sense for the other branches, though.)
</blockquote></details>

removed for master

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)* status: all files reviewed, 2 unresolved discussions (waiting on @chynamyerz)

___
*[.github/workflows/master.yml, line 41 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnU3m39ltsUXiGOdWF:-Lrwo_wE-Sxgz93i9sCA:bhis0d6) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L41)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Added
</blockquote></details>

You've added it for the remote server but not for the tests on Github. :)
___
*[.github/workflows/master.yml, line 83 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-Lrwq5BU1_Adi393kqLN:-Lrwq5BV6W3KqSefGyyK:b-gd7azg) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/df4fb2d3ea189453413c9689ae56fa44bd8e22fa/.github/workflows/master.yml#L83)):*
> ```YAML
>               git pull
>               yarn install
>               yarn format
> ```

Hmm, I might have been wrong about including a "yarn format" anywhere... :/

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[.github/workflows/master.yml, line 41 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-LrnU3m39ltsUXiGOdWF:-LrxFUtP7u2NJIPW5zLC:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/120ee60afca1d33785f18b7656bbb1fd6103bcca/.github/workflows/master.yml#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You've added it for the remote server but not for the tests on Github. :)
</blockquote></details>

Done.
___
*[.github/workflows/master.yml, line 83 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-Lrwq5BU1_Adi393kqLN:-LrxFVRB2Af5gWp5kLVM:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/df4fb2d3ea189453413c9689ae56fa44bd8e22fa/.github/workflows/master.yml#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Hmm, I might have been wrong about including a "yarn format" anywhere... :/
</blockquote></details>

Done.

**Review by chynamyerz — COMMENTED** [review]
Updated git actions

> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42#-:-LrxWtriAO8vHRBsDrCP:b1p5wn9)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @hettlage)

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 3 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/42)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
