### PR TITLE
Fix data request query

### LINKED ISSUE #99: Update the handling of data requests
Update both storing and querying data requests (in line with #98).

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/resolvers/dataRequest.ts, line 23 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1frK_sDpH8imnUKd-K:-M1frK_sDpH8imnUKd-L:b-29frlc) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/resolvers/dataRequest.ts#L23)):*
> ```XML
>   }
> 
>   // TODO Christian is working on this part
> ```

I think we should change the logic: The additional calibrations should not be stored in the database. Hence you should handle them when creating the zip file and README.

I'll raise an issue, which should not be addressed in this pull request, please. :)

Oh, and beware of merging problems between this branch and the include-calibrations one...
___
*[src/resolvers/dataRequest.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1fq-ydBaHjIsBqzJCY:-M1fq-ye-XuWHWTa-q5q:b6zqpp5) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/resolvers/dataRequest.ts#L75)):*
> ```XML
>       await client.query(dataRequestCalibrationLevelSQL, [
>         dataRequestId,
>         titleCase(CalibrationLevel.toLowerCase().replace(/_/g, " "))
> ```

How about using a helper function for the string conversion?
___
*[src/util/loaders.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g2lnm-4_sZGo9rfI1:-M1g2lnn6S5FbgImD62p:b-asr34v) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L59)):*
> ```XML
>     ids
>   ]);
>   const calibrationLevels = calibrationLevelsRes.rows;
> ```

Maybe add a comment:

// Group the calibration levels by data request
___
*[src/util/loaders.ts, line 61 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g0wUI-060mgqtYF82:-M1g0wUI-060mgqtYF83:b-uyjaqg) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L61)):*
> ```XML
>   const calibrationLevels = calibrationLevelsRes.rows;
>   for (const row of calibrationLevels) {
>     (dataRequestCalibrationLevels.get(row.data_request_id) as any).push(
> ```

Do you really need the `as any`?
___
*[src/util/loaders.ts, line 66 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g2xRbEvvIy1pB9192:-M1g2xRbEvvIy1pB9193:bwv55ym) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L66)):*
> ```XML
>   }
> 
>   // Get the calibration levels
> ```

Should read: // Get the calibration types
___
*[src/util/loaders.ts, line 69 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g1CXO4bwBAfJ_CCFn:-M1g1CXO4bwBAfJ_CCFo:b-6rhf6l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L69)):*
> ```XML
>   const calibrationTypesSQL = `
>   SELECT data_request_id, calibration_type
>   FROM admin.data_request_calibration_type AS drcl
> ```

`drcl` should be `drct`
___
*[src/util/loaders.ts, line 70 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g1IduD6lcSfkpGEOE:-M1g1Idv38HY0DzEZgZq:bue5943) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L70)):*
> ```XML
>   SELECT data_request_id, calibration_type
>   FROM admin.data_request_calibration_type AS drcl
>   JOIN admin.calibration_type AS cl ON drcl.calibration_type_id = cl.calibration_type_id
> ```

`cl` should be `ct`
___
*[src/util/loaders.ts, line 74 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g33C20LlyUWxsD_-5:-M1g33C20LlyUWxsD_-6:bhqh8ej) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L74)):*
> ```XML
>   `;
>   const calibrationTypesRes = await ssdaPool.query(calibrationTypesSQL, [ids]);
>   const calibrationTypes = calibrationTypesRes.rows;
> ```

Maybe add a comment:

// Group the calibration types by data request
___
*[src/util/loaders.ts, line 76 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g18HG1jmNIdW2F9KS:-M1g18HG1jmNIdW2F9KT:b-uyjaqg) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L76)):*
> ```XML
>   const calibrationTypes = calibrationTypesRes.rows;
>   for (const row of calibrationTypes) {
>     (dataRequestCalibrationTypes.get(row.data_request_id) as any).push(
> ```

Do you really need the `as any`?
___
*[src/util/zipDataRequest.ts, line 52 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3m8s4zvNOKqzZo03:-M1g3m8s4zvNOKqzZo04:b-ygqhgt) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L52)):*
> ```XML
>   fileIds: string[],
>   dataRequestId: string,
>   requestedCalibrationLevels: string[]
> ```

Shouldn't this be CalibrationLevel[] ?
___
*[src/util/zipDataRequest.ts, line 189 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3M9m5pKCmfgklCW-:-M1g3M9m5pKCmfgklCW0:b-mn2g4z) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L189)):*
> ```XML
>   // append a file from string
>   archive.append(readMeFileContent, { name: "README.txt" });
>   const reducedRequested = requestedCalibrationLevels.some(
> ```

 Maybe use `!!requestedCalibrationLevels.indexOf("REDUCED") !== -1` ?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/resolvers/dataRequest.ts, line 23 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1frK_sDpH8imnUKd-K:-M1jBTyOErUKrPQ0xYkg:b-21fy35) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/resolvers/dataRequest.ts#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think we should change the logic: The additional calibrations should not be stored in the database. Hence you should handle them when creating the zip file and README.

I'll raise an issue, which should not be addressed in this pull request, please. :)

Oh, and beware of merging problems between this branch and the include-calibrations one...
</blockquote></details>

I only need artifacts Ids of additional calibrations then they will be added
I am ready for merging :)
___
*[src/resolvers/dataRequest.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1fq-ydBaHjIsBqzJCY:-M1iV0sOChecXMUCqXqJ:b-r16n3c) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/resolvers/dataRequest.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about using a helper function for the string conversion?
</blockquote></details>

it is only used twice and here just for contol we do not have Cal Level with "_"
it might seems like it is used 4 times but the other two are the opposite of this.
___
*[src/util/loaders.ts, line 61 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g0wUI-060mgqtYF82:-M1jByXb6yEDYw7ebw3r:b-ae6ce4) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really need the `as any`?
</blockquote></details>

some how intellij is rising an error/warning not sure if I need to remove it. help?
___
*[src/util/loaders.ts, line 66 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g2xRbEvvIy1pB9192:-M1jCESUCzEh4t9DzzuL:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L66)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should read: // Get the calibration types
</blockquote></details>

Done.
___
*[src/util/loaders.ts, line 69 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g1CXO4bwBAfJ_CCFn:-M1jCTX-CkNi2aVrM4HK:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`drcl` should be `drct`
</blockquote></details>

Done.
___
*[src/util/loaders.ts, line 70 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g1IduD6lcSfkpGEOE:-M1jCTwc6Fi2cCBbgYo-:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L70)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`cl` should be `ct`
</blockquote></details>

Done.
___
*[src/util/loaders.ts, line 74 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g33C20LlyUWxsD_-5:-M1jCVOj3iOUSZwRuonQ:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L74)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a comment:

// Group the calibration types by data request
</blockquote></details>

Done.
___
*[src/util/loaders.ts, line 76 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g18HG1jmNIdW2F9KS:-M1jCWPp7QCBA11hmQJe:bwwsp7f) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really need the `as any`?
</blockquote></details>

like above not sure I was getting a warning/ error
___
*[src/util/zipDataRequest.ts, line 52 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3m8s4zvNOKqzZo03:-M1jDv1xAKT-1DfNYRh4:b832tgr) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be CalibrationLevel[] ?
</blockquote></details>

Only have type CalibrationLevel defined in a schema.
Do I also have to define a new Interface CalibrationLevel?
___
*[src/util/zipDataRequest.ts, line 189 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3M9m5pKCmfgklCW-:-M1jFrdK48kz6MnxDo6s:b-xvpong) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L189)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

 Maybe use `!!requestedCalibrationLevels.indexOf("REDUCED") !== -1` ?
</blockquote></details>

there is ```level.toUpperCase() === "REDUCED"``` CalLevels are not alway upperCase

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: 4 of 5 files reviewed, 11 unresolved discussions (waiting on @hettlage)

___
*[src/util/loaders.ts, line 59 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g2lnm-4_sZGo9rfI1:-M1jXOMDCJUO3G2FPkEz:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a comment:

// Group the calibration levels by data request
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: all files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/resolvers/dataRequest.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1fq-ydBaHjIsBqzJCY:-M1jy86dCX83NmLIADws:b-hzrvoo) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/resolvers/dataRequest.ts#L75)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it is only used twice and here just for contol we do not have Cal Level with "_"
it might seems like it is used 4 times but the other two are the opposite of this.
</blockquote></details>

Yes, but you are doing three things in one line, and you repeat these. :)
___
*[src/util/loaders.ts, line 61 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g0wUI-060mgqtYF82:-M1k4n7t3xIbIYlWYqcK:b5q1y0) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L61)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

some how intellij is rising an error/warning not sure if I need to remove it. help?
</blockquote></details>

Ah, the expression might be undefined, that's why it's needed. Sorry!
___
*[src/util/loaders.ts, line 76 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g18HG1jmNIdW2F9KS:-M1k54UP8ESGbKYPLu_p:b3e7v8t) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L76)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

like above not sure I was getting a warning/ error
</blockquote></details>

Same issue as above, I guess.
___
*[src/util/zipDataRequest.ts, line 52 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3m8s4zvNOKqzZo03:-M1k5QE4EO1TzFii_wWV:b2dq4tu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L52)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Only have type CalibrationLevel defined in a schema.
Do I also have to define a new Interface CalibrationLevel?
</blockquote></details>

Let's discuss this.
___
*[src/util/zipDataRequest.ts, line 189 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3M9m5pKCmfgklCW-:-M1k5mcN-tbulbDJ31-X:b2dq4tu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L189)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

there is ```level.toUpperCase() === "REDUCED"``` CalLevels are not alway upperCase
</blockquote></details>

Let's discuss this.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: 2 of 6 files reviewed, 10 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/util/zipDataRequest.ts, line 52 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3m8s4zvNOKqzZo03:-M1k9mUy2lZh0tlBEyvx:buyyn2x) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Let's discuss this.
</blockquote></details>


now it is fixed havae a look
___
*[src/util/zipDataRequest.ts, line 189 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3M9m5pKCmfgklCW-:-M1k9shv1d0RTY9tSkS_:b-psb8lf) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L189)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Let's discuss this.
</blockquote></details>

now I use set as you do

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: 2 of 6 files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/dataRequest.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1fq-ydBaHjIsBqzJCY:-M1kC0QZ5EogeePrGZsf:b-fgpaus) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/resolvers/dataRequest.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes, but you are doing three things in one line, and you repeat these. :)
</blockquote></details>

see now this is what I meant
___
*[src/util/loaders.ts, line 61 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g0wUI-060mgqtYF82:-M1kAGF20JjuY1bmED0P:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, the expression might be undefined, that's why it's needed. Sorry!
</blockquote></details>

Done.
___
*[src/util/loaders.ts, line 76 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g18HG1jmNIdW2F9KS:-M1kAFIE1fvlEjRDLhJR:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Same issue as above, I guess.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/resolvers/dataRequest.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1fq-ydBaHjIsBqzJCY:-M1kOJQ37eRMbpH0s-BH:bp1ddu5) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/resolvers/dataRequest.ts#L75)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

see now this is what I meant
</blockquote></details>

Huh, but that is an argument in favour of a helper function... :)
___
*[src/resolvers/dataRequest.ts, line 122 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1kOsqVBSA-YTLLyMvO:-M1kOsqVBSA-YTLLyMvP:b-a38ryd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/2c6be2075fea77a3ebe44d83389339f5f1f6d887/src/resolvers/dataRequest.ts#L122)):*
> ```XML
> };
> 
> const groupByObservation = (dataFiles: [any]) => {
> ```

This code is new (according to git) but seemingly not used. Is it needed?
___
*[src/util/loaders.ts, line 66 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g2xRbEvvIy1pB9192:-M1kPhxm3CUYQryxhpyX:b-mqg0y1) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L66)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Uhm, I don't think it is done? :/
___
*[src/util/zipDataRequest.ts, line 189 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3M9m5pKCmfgklCW-:-M1kPCgHBg9ey4EmNDMA:b75099u) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L189)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

now I use set as you do
</blockquote></details>

Thank you! :)

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/dataRequest.ts, line 75 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1fq-ydBaHjIsBqzJCY:-M2YNfHJ6Q19PVAtd4Q7:btr2jms) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/resolvers/dataRequest.ts#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Huh, but that is an argument in favour of a helper function... :)
</blockquote></details>

No it is not.
 coz I do not see a use of creating a hepler function to call once and that helper function will only call build in methods
___
*[src/resolvers/dataRequest.ts, line 122 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1kOsqVBSA-YTLLyMvO:-M2YNPtA1E5qmEHgB_yW:b-9q54b5) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/2c6be2075fea77a3ebe44d83389339f5f1f6d887/src/resolvers/dataRequest.ts#L122)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This code is new (according to git) but seemingly not used. Is it needed?
</blockquote></details>

not used
___
*[src/util/loaders.ts, line 66 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g2xRbEvvIy1pB9192:-M2YN8H69vI8NZmdAnNV:b-tblxq6) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/loaders.ts#L66)):*
> Get the calibration types
done for real now
___
*[src/util/zipDataRequest.ts, line 189 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/108#-M1g3M9m5pKCmfgklCW-:-M2YMzWNAFn6_J1fU9iJ:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/9cd40ad622c271e9e3c15130e00831649ea8ddd9/src/util/zipDataRequest.ts#L189)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Thank you! :)
</blockquote></details>

Done.

**Review by hettlage — DISMISSED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/108)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
