### PR TITLE
Limiting download size

### LINKED ISSUE #176: Enforce maximum size for download requests
Data requests should be rejected if the total size of requested FITS files exceeds a limit (say, 5 GB).

### PR DESCRIPTION
**Pull request by Lonwabo11**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: all files reviewed, 6 unresolved discussions (waiting on @Lonwabo11)

___
*[src/resolvers/dataRequest.ts, line 22 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzlMSTBFWC0k3Dv-_2:-MCzlMSU2IuDEKA1YvG_:b-7mxujf) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L22)):*
> ```XML
>   requestedCalibrationLevels: Set<CalibrationLevel>
> ) {
>   const sql = `SELECT (paths).raw,
> ```

This looks as if you are duplicating code from the zipDataRequest function, and you should check if you cannot refactor the code so that there is no duplication.

You should note somewhere that the function returns MB. (But why doesn't it return just bytes?)
___
*[src/resolvers/dataRequest.ts, line 34 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzm7SH7sGRv7_Ztk1m:-MCzm7SH7sGRv7_Ztk1n:b8at6zi) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L34)):*
> ```XML
>     if (requestedCalibrationLevels.has("RAW")) {
>       filepath = process.env.FITS_BASE_DIR + df.raw;
>       fileSize += fs.statSync(filepath).size / 1000000;
> ```

I would have thought that 1 MB = 2^20 bytes = 1048576 bytes. But guess what, according to Wikipedia you are right. :)
___
*[src/resolvers/dataRequest.ts, line 38 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzzFFu24OJmCfHiodA:-MCzzFFv9YaWf2meOt4w:b6mvjyu) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L38)):*
> ```XML
>     if (requestedCalibrationLevels.has("REDUCED")) {
>       filepath = process.env.FITS_BASE_DIR + df.reduced;
>       fileSize += fs.statSync(filepath).size / 1000000;
> ```

I'd recommend to stick to bytes.
___
*[src/resolvers/dataRequest.ts, line 41 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCznhFF6R0wlMZ7XHQN:-MCznhFF6R0wlMZ7XHQO:bi897jh) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L41)):*
> ```XML
>     }
>   }
>   return Math.round(fileSize);
> ```

Why are you rounding here?
___
*[src/resolvers/dataRequest.ts, line 72 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzxcQr27A_J0EUnH-B:-MCzxcQr27A_J0EUnH-C:b-lwis1t) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L72)):*
> ```XML
>       dataFileIdStrings,
>       requestedCalibrationLevels
>     )) >= 5000
> ```

I'd recommend to stick to bytes, maybe using a constant for the maximum file size (something like `MAX_SIZE = 5 * 1000 * 1000 * 1000 // 5 GB`).
___
*[src/resolvers/dataRequest.ts, line 74 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzxTcK6KeUD9OT52ul:-MCzxTcK6KeUD9OT52um:b-ujbahh) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L74)):*
> ```XML
>     )) >= 5000
>   ) {
>     throw new Error("You are not allowed to to request files more than 5GB.");
> ```

Maybe: "The total file size for your data request exceeds 5 GB."

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/dataRequest.ts, line 22 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzlMSTBFWC0k3Dv-_2:-MD-LYwi5AqSPQYRax46:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks as if you are duplicating code from the zipDataRequest function, and you should check if you cannot refactor the code so that there is no duplication.

You should note somewhere that the function returns MB. (But why doesn't it return just bytes?)
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 34 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzm7SH7sGRv7_Ztk1m:-MD-2Srz6vzH5Y6UPqsk:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L34)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would have thought that 1 MB = 2^20 bytes = 1048576 bytes. But guess what, according to Wikipedia you are right. :)
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 38 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzzFFu24OJmCfHiodA:-MD-0Bl96tPi54TfL8PG:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd recommend to stick to bytes.
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 41 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCznhFF6R0wlMZ7XHQN:-MD-2Qj6ECenwwYQrP5B:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why are you rounding here?
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 72 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzxcQr27A_J0EUnH-B:-MD-1MreDJnPyr_IRmot:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd recommend to stick to bytes, maybe using a constant for the maximum file size (something like `MAX_SIZE = 5 * 1000 * 1000 * 1000 // 5 GB`).
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 74 at r1](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MCzxTcK6KeUD9OT52ul:-MD-1LFNBJqL80-rSIoP:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f47f1d81a662546e2233848da2ac3556f1f223d0/src/resolvers/dataRequest.ts#L74)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe: "The total file size for your data request exceeds 5 GB."
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: all files reviewed, 5 unresolved discussions (waiting on @Lonwabo11)

___
*[src/resolvers/dataRequest.ts, line 19 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFf7cQ0KAj0I31aCTm:-MDFf7cQ0KAj0I31aCTn:bwzxrtn) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/resolvers/dataRequest.ts#L19)):*
> ```XML
> 
> // limiting the data request of the user 5GB or less, we return thr limit size in bytes
> async function data_request_limit_size(
> ```

The comment might be a bit misleading this function doesn't limit, it just returns the total file size. I'd also rename the function to something like totalDataRequestFileSize. For consistency, please use camel case.
___
*[src/resolvers/dataRequest.ts, line 28 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFgezw40wiOIsi8ykQ:-MDFgezw40wiOIsi8ykR:b7jzo3a) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/resolvers/dataRequest.ts#L28)):*
> ```XML
>     requestedCalibrationLevels
>   );
>   dataFiles.map(file => {
> ```

map isn't the right function really, forEach or reduce would be more appropriate, as you aren't mapping anything really.
___
*[src/resolvers/dataRequest.ts, line 30 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFfcMp0GVF20HgoRkA:-MDFfcMp0GVF20HgoRkB:b-l6dtpt) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/resolvers/dataRequest.ts#L30)):*
> ```XML
>   dataFiles.map(file => {
>     const paths = process.env.FITS_BASE_DIR + file.filepath;
>     fileSize += fs.statSync(paths).size;
> ```

Maybe fileSize ---> totalSize or totalFileSize (to avoid the notion this is the size of a single file). 
___
*[src/resolvers/dataRequest.ts, line 57 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFfq932oTAbfXT9X1o:-MDFfq932oTAbfXT9X1p:b-wvc50f) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/resolvers/dataRequest.ts#L57)):*
> ```XML
>     dataFiles = await addCalibrations(dataFiles, requestedCalibrationTypes);
>   }
>   const MAX_SIZE = 5368709120; // 5GB
> ```

5 GB = 5000000000 bytes (see page 143 of https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf)
___
*[src/util/zipDataRequest.ts, line 51 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFgOSA9M3XV02YuEbH:-MDFgOSA9M3XV02YuEbI:b-3kyrdj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/util/zipDataRequest.ts#L51)):*
> ```XML
>   );
> };
> export async function files_to_be_zipped(
> ```

For consistency please use camel case.

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/dataRequest.ts, line 19 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFf7cQ0KAj0I31aCTm:-MDJX_6y2HWhdpJySc_0:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/resolvers/dataRequest.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The comment might be a bit misleading this function doesn't limit, it just returns the total file size. I'd also rename the function to something like totalDataRequestFileSize. For consistency, please use camel case.
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 28 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFgezw40wiOIsi8ykQ:-MDJXms56TWA9i37_jio:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/resolvers/dataRequest.ts#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

map isn't the right function really, forEach or reduce would be more appropriate, as you aren't mapping anything really.
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 30 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFfcMp0GVF20HgoRkA:-MDJYF-l0727dlAwd468:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/resolvers/dataRequest.ts#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe fileSize ---> totalSize or totalFileSize (to avoid the notion this is the size of a single file). 
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 57 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFfq932oTAbfXT9X1o:-MDJYAf12q_2nHSIfwoL:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/resolvers/dataRequest.ts#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

5 GB = 5000000000 bytes (see page 143 of https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9.pdf)
</blockquote></details>

Done.
___
*[src/util/zipDataRequest.ts, line 51 at r2](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDFgOSA9M3XV02YuEbH:-MDJYCxTAIL9edRl4i4w:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/c243817038b2409162027275bf877589ce329550/src/util/zipDataRequest.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency please use camel case.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @hettlage and @Lonwabo11)

___
*[src/resolvers/dataRequest.ts, line 18 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDL5zY50tXXffeU-h9B:-MDL5zY50tXXffeU-h9C:b-rv9h9b) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/fdf0e4e9d68fdf019f17b62a3f47c73ccfc32b44/src/resolvers/dataRequest.ts#L18)):*
> ```XML
> }
> 
> // we return the total file size for the download by the user
> ```

How about:

// Return the total (unzipped) file size for the download request
___
*[src/resolvers/dataRequest.ts, line 26 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDL3N1f1JjLq205pGox:-MDL3N1f1JjLq205pGoy:bcucc1w) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/fdf0e4e9d68fdf019f17b62a3f47c73ccfc32b44/src/resolvers/dataRequest.ts#L26)):*
> ```XML
>   const dataFiles = await filesToBeZipped(fileIds, requestedCalibrationLevels);
>   dataFiles.forEach(file => {
>     const paths = process.env.FITS_BASE_DIR + file.filepath;
> ```

paths ---> path or fullPath (sorry, I had missed that)

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage and @Lonwabo11)

**Review by Lonwabo11 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[src/resolvers/dataRequest.ts, line 18 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDL5zY50tXXffeU-h9B:-MDLC9ox4IGKAK28dG5l:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/fdf0e4e9d68fdf019f17b62a3f47c73ccfc32b44/src/resolvers/dataRequest.ts#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

How about:

// Return the total (unzipped) file size for the download request
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 26 at r3](https://reviewable.io/reviews/saltastroops/data-archive-backend/179#-MDL3N1f1JjLq205pGox:-MDLCfcj8Fr0zTmUzbyg:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/fdf0e4e9d68fdf019f17b62a3f47c73ccfc32b44/src/resolvers/dataRequest.ts#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

paths ---> path or fullPath (sorry, I had missed that)
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/179)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
