### PR TITLE
Move tests to postgres

### PR DESCRIPTION
**Pull request by chynamyerz**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 23 files at r1, 12 of 18 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 22 of 22 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: all files reviewed, 9 unresolved discussions (waiting on @chynamyerz)

___
*[.github/workflows/development.yml, line 1 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroKhCA8Ss4g_aav-8S:-LroKhCA8Ss4g_aav-8T:b4vrzgl) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/.github/workflows/development.yml#L1)):*
> ```YAML
> # The Data Archive API Development Workflow
> ```

I won't review the Github action files, abnd I'd suggest you delete them (to avoid conflicts later on). ;-)
___
*[actions/ssh/Dockerfile, line 2 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroLLdN9OnhVXal7Ptc:-LroLLdOA5cVJ8LMHauE:b-lpliwj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/actions/ssh/Dockerfile#L2)):*
> ```Dockerfile
> #Download base image ubuntu 18.04
> FROM ubuntu:18.04
> ```

Is this file required?
___
*[actions/ssh/entrypoint.sh, line 1 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroLFx95B3xoWSozsas:-LroLFx95B3xoWSozsat:b-lpliwj) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/actions/ssh/entrypoint.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

Is this file required?
___
*[src/createServer.ts, line 423 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroLbz745-DpET4HS7f:-LroLbz745-DpET4HS7g:b-wj40ky) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/createServer.ts#L423)):*
> ```XML
>     SELECT data_request_id, path, status, made_at, ssda_user_id
>     FROM admin.data_request dr
>     JOIN admin.data_request_status
> ```

I'd suggest to be consistent wrt using aliases.
___
*[src/__tests__/passwordReset.test.ts, line 82 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroPDQQ91YuTkgeEsQ4:-LroPDQQ91YuTkgeEsQ5:bk6nueh) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/__tests__/passwordReset.test.ts#L82)):*
> ```XML
>       .mockReturnValueOnce(true);
> 
>     (transporter.sendMail as any).mockReturnValueOnce("Email error");
> ```

Should mockResolvedValue be used for query and sendMail?
___
*[src/__tests__/requestDataDownload.test.ts, line 57 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroPxMy0HHW6O4gBZfy:-LroPxMzBYgXRJKR8mKo:b-2x11ns) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/__tests__/requestDataDownload.test.ts#L57)):*
> ```XML
>       });
> 
>     // Mock the bcrypt password compare to return true.
> ```

compare ---> comparison
___
*[src/resolvers/dataRequest.ts, line 27 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroRxu6ComkstA_eaTy:-LroRxu7Edg2WaWZE0LH:bxs062o) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/resolvers/dataRequest.ts#L27)):*
> ```XML
>   // check if user is logged in
>   if (!user) {
>     throw new Error("You must be logged in to a create data request");
> ```

in to a create ---> in to create a
___
*[src/util/dataRequests.ts, line 13 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroT0OV6MpMQFtSf2vX:-LroT0OV6MpMQFtSf2vY:b-ksi9hd) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/util/dataRequests.ts#L13)):*
> ```XML
>   const sql = `
>       SELECT data_request_id, status, made_at, u.ssda_user_id
>       FROM admin.data_request dr
> ```

Use of aliases should be consistent.
___
*[src/util/loaders.ts, line 24 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroTb-gENYRcYw6NIej:-LroTb-gENYRcYw6NIek:b-y6r6na) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/util/loaders.ts#L24)):*
> ```XML
>   }));
> 
>   // Use an int rather than string as id
> ```

This comment probably should be moved up a bit?

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: 32 of 38 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[.github/workflows/development.yml, line 1 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroKhCA8Ss4g_aav-8S:-LrryZ2dC64KIpw8sqEx:b-6ty45o) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/.github/workflows/development.yml#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I won't review the Github action files, abnd I'd suggest you delete them (to avoid conflicts later on). ;-)
</blockquote></details>

Yes please, now removed.
___
*[actions/ssh/Dockerfile, line 2 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroLLdN9OnhVXal7Ptc:-LrryfRVBbvqabkFfZqV:b-hfpv0l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/actions/ssh/Dockerfile#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this file required?
</blockquote></details>

removed
___
*[actions/ssh/entrypoint.sh, line 1 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroLFx95B3xoWSozsas:-Lrryi0jDEV16NeczyHd:b-hfpv0l) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/actions/ssh/entrypoint.sh#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this file required?
</blockquote></details>

removed
___
*[src/createServer.ts, line 423 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroLbz745-DpET4HS7f:-LrsLRwo7qokjEF6K6xj:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/createServer.ts#L423)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to be consistent wrt using aliases.
</blockquote></details>

Done.
___
*[src/__tests__/passwordReset.test.ts, line 82 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroPDQQ91YuTkgeEsQ4:-LrsMX8c6ANufxBI2Yq6:bjksdbo) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/__tests__/passwordReset.test.ts#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should mockResolvedValue be used for query and sendMail?
</blockquote></details>

For the query yes, because the email should not exist.
For sendMail Ummm nut really.
___
*[src/__tests__/requestDataDownload.test.ts, line 57 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroPxMy0HHW6O4gBZfy:-LrrzBaY27T_Vrn5ZCW7:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/__tests__/requestDataDownload.test.ts#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

compare ---> comparison
</blockquote></details>

Done.
___
*[src/resolvers/dataRequest.ts, line 27 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroRxu6ComkstA_eaTy:-LrrzQ_hDlCfpseTq1QZ:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/resolvers/dataRequest.ts#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

in to a create ---> in to create a
</blockquote></details>

Done.
___
*[src/util/dataRequests.ts, line 13 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroT0OV6MpMQFtSf2vX:-LrsM-ks1FGn5RJPePPg:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/util/dataRequests.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Use of aliases should be consistent.
</blockquote></details>

Done.
___
*[src/util/loaders.ts, line 24 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroTb-gENYRcYw6NIej:-Lrrzst39It9Y4R92Eoj:b-896fix) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/util/loaders.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This comment probably should be moved up a bit?
</blockquote></details>

Done.

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: 32 of 38 files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[src/__tests__/passwordReset.test.ts, line 82 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroPDQQ91YuTkgeEsQ4:-LrwRckx9WO56s7t29Of:bfc85ho) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/__tests__/passwordReset.test.ts#L82)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

For the query yes, because the email should not exist.
For sendMail Ummm nut really.
</blockquote></details>

Meant the email should exit.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/__tests__/passwordReset.test.ts, line 82 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroPDQQ91YuTkgeEsQ4:-LrwmUrR36eihjhuWI1N:b6mn27h) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/__tests__/passwordReset.test.ts#L82)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Meant the email should exit.
</blockquote></details>

But sendMail is an async function, so you would expect a mock function returning a promise...

(Maybe the difference doesn't matter because await sneaks in a promise?)

**Review by chynamyerz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: 31 of 38 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[src/__tests__/passwordReset.test.ts, line 82 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroPDQQ91YuTkgeEsQ4:-LrxBoexA3LADHAjQcBW:b-1r49la) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/__tests__/passwordReset.test.ts#L82)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But sendMail is an async function, so you would expect a mock function returning a promise...

(Maybe the difference doesn't matter because await sneaks in a promise?)
</blockquote></details>

I also addressed this in other test files.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: 35 of 38 files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/__tests__/passwordReset.test.ts, line 82 at r5](https://reviewable.io/reviews/saltastroops/data-archive-backend/41#-LroPDQQ91YuTkgeEsQ4:-LrxGQS84rzy6i0mbxW0:b87vto3) ([raw file](https://github.com/saltastroops/data-archive-backend/blob/f8c984f9f7cdd2070c72fcacb3e43917c76bfcb8/src/__tests__/passwordReset.test.ts#L82)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

I also addressed this in other test files.
</blockquote></details>

Thank you! :-)

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: 37 of 38 files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

**Review by hettlage — COMMENTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/data-archive-backend/41)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
